CREATE OR REPLACE TRIGGER ATENDIMENTOS_FATURAMENTO_TRG
 AFTER UPDATE ON ATENDIMENTOS
FOR EACH ROW
WHEN (NEW.FATURAMENTO <> OLD.FATURAMENTO)
DECLARE
BEGIN
     IF :NEW.FATURAMENTO = 'F' THEN
            UPDATE EXAMES E SET E.VALOR_PAGO = E.VALOR_HON
             WHERE E.POSTO = :NEW.POSTO
               AND E.ATENDIMENTO = :NEW.ATENDIMENTO
               AND E.SITUACAO <> 'C' 
               AND E.LIB_FAT = 'S';

     ELSIF :NEW.FATURAMENTO = 'C' THEN
            UPDATE EXAMES E SET E.VALOR_PAGO = 0
             WHERE E.POSTO = :NEW.POSTO
               AND E.ATENDIMENTO = :NEW.ATENDIMENTO
               AND E.SITUACAO <> 'C' 
               AND E.LIB_FAT = 'S';
     END IF;
END;
/