CREATE OR REPLACE TRIGGER ATENDIMENTOS_TRG
 AFTER UPDATE ON ATENDIMENTOS
FOR EACH ROW
WHEN (NEW.POSTO <> OLD.POSTO)
DECLARE
BEGIN
     UPDATE EXAMES                   SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
     UPDATE PENDENCIAS               SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
     UPDATE AMOSTRAS                 SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
     UPDATE CONTAS_ATENDIMENTOS      SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
     UPDATE COMPLEMENTO_ATENDIMENTOS SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
     UPDATE RESULTADOS               SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
     UPDATE RESULTADOS_TEXTOS        SET POSTO = :NEW.POSTO WHERE POSTO = :OLD.POSTO AND ATENDIMENTO = :NEW.ATENDIMENTO;
END;
/