CREATE OR REPLACE TRIGGER ENTRADAS_PRODUTOS_TRG
 AFTER INSERT OR UPDATE OR DELETE ON ENTRADAS_PRODUTOS
 FOR EACH ROW
DECLARE
 V_DEPARTAMENTO COMPRAS_RECEBIMENTOS.DEPARTAMENTO%TYPE;
 V_FORNECEDOR COMPRAS.FORNECEDOR%TYPE;
 V_PRODUTO PRODUTOS.PRODUTO%TYPE;
BEGIN
     IF INSERTING THEN
     	  SELECT DEPARTAMENTO INTO V_DEPARTAMENTO FROM COMPRAS_RECEBIMENTOS 
         WHERE NUMERO = :NEW.NUMERO_COMPRA AND CORREL = :NEW.CORREL_RECEBIMENTO;

        SELECT PRODUTO INTO V_PRODUTO FROM PRODUTOS_FORNECEDORES 
            WHERE PRODUTO_ID = :NEW.PRODUTO_ID;

        UPDATE PRODUTOS_COMPRA SET QTD_ENTREGUE = QTD_ENTREGUE + :NEW.QTD
            WHERE NUMERO = :NEW.NUMERO_COMPRA AND PRODUTO_ID = :NEW.PRODUTO_ID;

        UPDATE PRODUTOS_FORNECEDORES SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD
           WHERE PRODUTO_ID = :NEW.PRODUTO_ID;

        UPDATE DEPARTAMENTOS_PRODUTOS SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD
           WHERE DEPARTAMENTO = V_DEPARTAMENTO AND PRODUTO = V_PRODUTO;

     ELSIF UPDATING THEN
     	  SELECT DEPARTAMENTO INTO V_DEPARTAMENTO FROM COMPRAS_RECEBIMENTOS 
         WHERE NUMERO = :NEW.NUMERO_COMPRA AND CORREL = :NEW.CORREL_RECEBIMENTO;

        SELECT PRODUTO INTO V_PRODUTO FROM PRODUTOS_FORNECEDORES 
            WHERE PRODUTO_ID = :NEW.PRODUTO_ID;

        UPDATE PRODUTOS_COMPRA SET QTD_ENTREGUE = QTD_ENTREGUE + :NEW.QTD - :OLD.QTD
            WHERE NUMERO = :NEW.NUMERO_COMPRA AND PRODUTO_ID = :NEW.PRODUTO_ID;

        UPDATE PRODUTOS_FORNECEDORES SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD - :OLD.QTD
           WHERE PRODUTO_ID = :NEW.PRODUTO_ID;

        UPDATE DEPARTAMENTOS_PRODUTOS SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD - :OLD.QTD
           WHERE DEPARTAMENTO = V_DEPARTAMENTO AND PRODUTO = V_PRODUTO;

     ELSIF DELETING THEN
     	  SELECT DEPARTAMENTO INTO V_DEPARTAMENTO FROM COMPRAS_RECEBIMENTOS 
         WHERE NUMERO = :OLD.NUMERO_COMPRA AND CORREL = :OLD.CORREL_RECEBIMENTO;
 
        SELECT PRODUTO INTO V_PRODUTO FROM PRODUTOS_FORNECEDORES 
            WHERE PRODUTO_ID = :OLD.PRODUTO_ID;

        UPDATE PRODUTOS_COMPRA SET QTD_ENTREGUE = QTD_ENTREGUE - :OLD.QTD
            WHERE NUMERO = :OLD.NUMERO_COMPRA AND PRODUTO_ID = :OLD.PRODUTO_ID;

        UPDATE PRODUTOS_FORNECEDORES SET QTD_ATUAL = QTD_ATUAL - :OLD.QTD
           WHERE PRODUTO_ID = :OLD.PRODUTO_ID;

        UPDATE DEPARTAMENTOS_PRODUTOS SET QTD_ATUAL = QTD_ATUAL - :OLD.QTD
           WHERE DEPARTAMENTO = V_DEPARTAMENTO AND PRODUTO = V_PRODUTO;
     END IF;

END;
/
