CREATE OR REPLACE TRIGGER DEPARTAMENTOS_PRODUTOS_TRG
 AFTER INSERT OR UPDATE OR DELETE ON DEPARTAMENTOS_PRODUTOS
 FOR EACH ROW
BEGIN
     IF INSERTING AND :NEW.QTD_ATUAL > 0 THEN
        UPDATE PRODUTOS SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD_ATUAL
            WHERE PRODUTO = :NEW.PRODUTO;

     ELSIF UPDATING THEN
        IF :NEW.QTD_ATUAL > 0 AND :OLD.QTD_ATUAL > 0 THEN
           UPDATE PRODUTOS SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD_ATUAL - :OLD.QTD_ATUAL
               WHERE PRODUTO = :NEW.PRODUTO;
        ELSIF :NEW.QTD_ATUAL > 0 THEN
           UPDATE PRODUTOS SET QTD_ATUAL = QTD_ATUAL + :NEW.QTD_ATUAL
               WHERE PRODUTO = :NEW.PRODUTO;

        ELSIF :OLD.QTD_ATUAL > 0 THEN
           UPDATE PRODUTOS SET QTD_ATUAL = QTD_ATUAL + :OLD.QTD_ATUAL
               WHERE PRODUTO = :NEW.PRODUTO;
        END IF;
     ELSIF DELETING THEN
        UPDATE PRODUTOS SET QTD_ATUAL = QTD_ATUAL - :OLD.QTD_ATUAL
            WHERE PRODUTO = :OLD.PRODUTO;
     END IF;

END;
/
