CREATE OR REPLACE TRIGGER ESTOQUE_TRG
 AFTER UPDATE ON PRODUTOS_PEDIDOS
 FOR EACH ROW
-- WHEN (NEW.QTD_ENTREGUE <> OLD.QTD_ENTREGUE OR NEW.CONFIRMADO <> OLD.CONFIRMADO)
DECLARE
 V_DEPTO_ORIGEM   PEDIDOS.DEPTO_ORIGEM%TYPE;
 V_DEPTO_DESTINO  PEDIDOS.DEPTO_DESTINO%TYPE;
BEGIN
     IF :NEW.QTD_ENTREGUE <> :OLD.QTD_ENTREGUE OR :OLD.QTD_ENTREGUE IS NULL OR :NEW.QTD_ENTREGUE IS NULL THEN
        SELECT PEDIDOS.DEPTO_ORIGEM INTO V_DEPTO_ORIGEM
        FROM PEDIDOS, DEPARTAMENTOS WHERE PEDIDOS.PEDIDO = :OLD.PEDIDO AND DEPARTAMENTOS.DEPARTAMENTO = PEDIDOS.DEPTO_ORIGEM;

        IF :OLD.QTD_ENTREGUE IS NULL THEN
           UPDATE ESTOQUE SET QTD = QTD - :NEW.QTD_ENTREGUE WHERE PRODUTO = :OLD.PRODUTO AND DEPARTAMENTO = V_DEPTO_ORIGEM;
        ELSIF :NEW.QTD_ENTREGUE IS NULL THEN
           UPDATE ESTOQUE SET QTD = QTD + :OLD.QTD_ENTREGUE WHERE PRODUTO = :OLD.PRODUTO AND DEPARTAMENTO = V_DEPTO_ORIGEM;
        ELSE
           UPDATE ESTOQUE SET QTD = QTD + :OLD.QTD_ENTREGUE - :NEW.QTD_ENTREGUE WHERE PRODUTO = :OLD.PRODUTO AND DEPARTAMENTO = V_DEPTO_ORIGEM;
        END IF;

     ELSIF :NEW.CONFIRMADO <> :OLD.CONFIRMADO OR :NEW.CONFIRMADO IS NOT NULL THEN
        SELECT PEDIDOS.DEPTO_DESTINO INTO V_DEPTO_DESTINO
        FROM PEDIDOS, DEPARTAMENTOS WHERE PEDIDOS.PEDIDO = :OLD.PEDIDO AND DEPARTAMENTOS.DEPARTAMENTO = PEDIDOS.DEPTO_DESTINO;

        IF :NEW.CONFIRMADO = 'S' THEN
           UPDATE ESTOQUE SET QTD = QTD + :NEW.QTD_ENTREGUE WHERE PRODUTO = :OLD.PRODUTO AND DEPARTAMENTO = V_DEPTO_DESTINO;
        ELSE
           UPDATE ESTOQUE SET QTD = QTD - :NEW.QTD_ENTREGUE WHERE PRODUTO = :OLD.PRODUTO AND DEPARTAMENTO = V_DEPTO_DESTINO;
        END IF;
     END IF;
END;
/
