CREATE OR REPLACE TRIGGER EXAMES_SITUACAO_TRG
 AFTER UPDATE ON EXAMES
FOR EACH ROW

WHEN ((NEW.SITUACAO = 'R') AND (NEW.SITUACAO <> OLD.SITUACAO OR NEW.SITUACAO_INTERFACE <> OLD.SITUACAO_INTERFACE))
  
DECLARE
PRAGMA AUTONOMOUS_TRANSACTION; 
QT_NAO_FINALIZADOS NUMBER(4);

BEGIN
     SELECT GET_COUNT_NAO_FINALIZADOS(:NEW.POSTO, :NEW.ATENDIMENTO) INTO QT_NAO_FINALIZADOS FROM DUAL;
     IF QT_NAO_FINALIZADOS = 0 THEN
        INSERT INTO NOTIFICACOES_SMS VALUES (SQ_NOTIFICACAO_SMS.NEXTVAL,
		                                     'EXA_FINAL',
											 'N',
											 SYSDATE,
											 '',
											 :NEW.POSTO,
											 :NEW.ATENDIMENTO);
		COMMIT;									 
     END IF;
END;
/