CREATE OR REPLACE TRIGGER PRODUTOS_COMPRA_TRG
 AFTER UPDATE OR DELETE ON PRODUTOS_COMPRA
FOR EACH ROW
BEGIN
     IF :NEW.QTD <> :OLD.QTD OR :NEW.VALOR <> :OLD.VALOR THEN
        IF :NEW.TIPO_DESCONTO = 'P' THEN
           UPDATE COMPRAS SET VALOR = VALOR - (:OLD.QTD * :OLD.VALOR) + (:NEW.QTD * :NEW.VALOR), 
                              DESCONTO_PRODUTO = DESCONTO_PRODUTO - (((:OLD.QTD * :OLD.VALOR) * :OLD.DESCONTO) / 100) + (((:NEW.QTD * :NEW.VALOR) * :OLD.DESCONTO) / 100),
                              IPI   = IPI - (((:OLD.QTD * :OLD.VALOR) * :OLD.IPI) / 100) + (((:NEW.QTD * :NEW.VALOR) * :OLD.IPI) / 100) WHERE NUMERO = :NEW.NUMERO;
         ELSE
           UPDATE COMPRAS SET VALOR = VALOR - (:OLD.QTD * :OLD.VALOR) + (:NEW.QTD * :NEW.VALOR),
                              IPI   = IPI - (((:OLD.QTD * :OLD.VALOR) * :OLD.IPI) / 100) + (((:OLD.QTD * :NEW.VALOR) * :OLD.IPI) / 100) WHERE NUMERO = :NEW.NUMERO;
         END IF;

     ELSIF :NEW.DESCONTO <> :OLD.DESCONTO THEN
        IF :NEW.TIPO_DESCONTO = 'P' THEN
           UPDATE COMPRAS SET DESCONTO_PRODUTO = DESCONTO_PRODUTO - (((:NEW.QTD * :NEW.VALOR) * :OLD.DESCONTO) / 100) + (((:NEW.QTD * :NEW.VALOR) * :NEW.DESCONTO) / 100) 
                  WHERE NUMERO = :NEW.NUMERO;
        ELSE 
           UPDATE COMPRAS SET DESCONTO_PRODUTO = DESCONTO_PRODUTO - :OLD.DESCONTO + :NEW.DESCONTO WHERE NUMERO = :NEW.NUMERO;
        END IF;

     ELSIF :NEW.TIPO_DESCONTO <> :OLD.TIPO_DESCONTO THEN
        IF :NEW.TIPO_DESCONTO = 'P' THEN
           UPDATE COMPRAS SET DESCONTO_PRODUTO = DESCONTO_PRODUTO - :OLD.DESCONTO + (((:NEW.QTD * :NEW.VALOR) * :NEW.DESCONTO) / 100)
                  WHERE NUMERO = :NEW.NUMERO;
        ELSE
           UPDATE COMPRAS SET DESCONTO_PRODUTO = DESCONTO_PRODUTO - (((:NEW.QTD * :NEW.VALOR) * :OLD.DESCONTO) / 100) + :NEW.DESCONTO
                  WHERE NUMERO = :NEW.NUMERO;
        END IF;

     ELSIF :NEW.IPI <> :OLD.IPI THEN
        UPDATE COMPRAS SET IPI = IPI - (((:OLD.QTD * :OLD.VALOR) * :OLD.IPI) / 100) + (((:NEW.QTD * :NEW.VALOR) * :NEW.IPI) / 100) WHERE NUMERO = :NEW.NUMERO;

     ELSIF DELETING THEN
        IF :OLD.TIPO_DESCONTO = 'P' THEN
           UPDATE COMPRAS SET VALOR = VALOR - (:OLD.VALOR * :OLD.QTD), DESCONTO_PRODUTO = DESCONTO_PRODUTO - (((:OLD.QTD * :OLD.VALOR) * :OLD.DESCONTO) / 100),
                  IPI = IPI - (((:OLD.VALOR * :OLD.QTD) * :OLD.IPI) / 100)
                  WHERE NUMERO = :OLD.NUMERO;
         ELSE
           UPDATE COMPRAS SET VALOR = VALOR - (:OLD.VALOR * :OLD.QTD), DESCONTO_PRODUTO = DESCONTO_PRODUTO - :OLD.DESCONTO, 
                  IPI = IPI - (((:OLD.VALOR * :OLD.QTD) * :OLD.IPI) / 100)
                  WHERE NUMERO = :OLD.NUMERO;
         END IF;
     END IF;
END;
/
