CREATE OR REPLACE FUNCTION PRC_UNIDADES(V_UNIDADE               IN OUT UNIDADES.UNIDADE%TYPE,
                                         V_NOME                  IN     UNIDADES.NOME%TYPE,
                                         V_SEQ_ATEND_ATUAL       IN     UNIDADES.SEQ_ATEND_ATUAL%TYPE,
                                         V_SEQ_ATEND_ATE         IN     UNIDADES.SEQ_ATEND_ATE%TYPE,
                                         V_SEQ_INTERNO_INICIO    IN     UNIDADES.SEQ_INTERNO_INICIO%TYPE,
                                         V_SEQ_INTERNO_FIM       IN     UNIDADES.SEQ_INTERNO_FIM%TYPE,
                                         V_SEQ_INTERNO_ATUAL     IN     UNIDADES.SEQ_INTERNO_ATUAL%TYPE,
                                         V_DATA_ATUALIZA_INTERNO IN     UNIDADES.DATA_ATUALIZA_INTERNO%TYPE,
                                         V_FUNCAO IN     INT) RETURNS VOID AS $$

BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_UNIDADE.NEXTVAL INTO V_UNIDADE FROM DUAL;
     INSERT INTO UNIDADES VALUES (V_UNIDADE, V_NOME, V_SEQ_ATEND_ATUAL, V_SEQ_ATEND_ATE, V_SEQ_INTERNO_INICIO, V_SEQ_INTERNO_FIM, V_SEQ_INTERNO_ATUAL, V_DATA_ATUALIZA_INTERNO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE UNIDADES SET NOME = V_NOME, SEQ_ATEND_ATUAL = V_SEQ_ATEND_ATUAL, SEQ_ATEND_ATE = V_SEQ_ATEND_ATE,
                               SEQ_INTERNO_INICIO = V_SEQ_INTERNO_INICIO, SEQ_INTERNO_FIM = V_SEQ_INTERNO_FIM, SEQ_INTERNO_ATUAL = V_SEQ_INTERNO_ATUAL,
                               DATA_ATUALIZA_INTERNO = V_DATA_ATUALIZA_INTERNO
      WHERE UNIDADE = V_UNIDADE;
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE UNIDADES WHERE UNIDADE = V_UNIDADE;

  ELSIF V_FUNCAO = 4 THEN
     UPDATE UNIDADES SET SEQ_INTERNO_ATUAL = V_SEQ_INTERNO_ATUAL, DATA_ATUALIZA_INTERNO = V_DATA_ATUALIZA_INTERNO
      WHERE UNIDADE = V_UNIDADE;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_UNIDADES;
/
