CREATE OR REPLACE FUNCTION PRC_ACOMODACOES_POSTOS(V_POSTO                  IN ACOMODACOES_POSTOS.POSTO%TYPE,
                                                   V_ID_ACOMODACAO          IN ACOMODACOES_POSTOS.ID_ACOMODACAO%TYPE,
                                                   V_IMPRIME_APOS_LIBERACAO IN ACOMODACOES_POSTOS.IMPRIME_APOS_LIBERACAO%TYPE,
                                                   V_IMPRESSORA_LAUDOS      IN ACOMODACOES_POSTOS.IMPRESSORA_LAUDOS%TYPE,
                                                   V_FUNCAO                 IN INT) RETURNS VOID AS $$
BEGIN                                                           
  IF V_FUNCAO = 1 THEN                                          
     INSERT INTO ACOMODACOES_POSTOS VALUES(V_POSTO, V_ID_ACOMODACAO, V_IMPRIME_APOS_LIBERACAO, V_IMPRESSORA_LAUDOS);

  ELSIF V_FUNCAO = 2 THEN
            UPDATE ACOMODACOES_POSTOS SET IMPRIME_APOS_LIBERACAO = V_IMPRIME_APOS_LIBERACAO, IMPRESSORA_LAUDOS = V_IMPRESSORA_LAUDOS
                                    WHERE POSTO=V_POSTO AND ID_ACOMODACAO=V_ID_ACOMODACAO;	

  ELSIF V_FUNCAO = 3 THEN
            DELETE ACOMODACOES_POSTOS WHERE POSTO=V_POSTO AND ID_ACOMODACAO=V_ID_ACOMODACAO;	

  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_ACOMODACOES_POSTOS;
/
