CREATE OR REPLACE FUNCTION PRC_MAP_B2B_CONVENIOS(V_ID_SERVICO_B2B  IN   MAP_B2B_CONVENIOS.ID_SERVICO_B2B%TYPE,
                                                  V_CONVENIO        IN   MAP_B2B_CONVENIOS.CONVENIO%TYPE,
                                                  V_MAP_CONVENIO    IN   MAP_B2B_CONVENIOS.MAP_CONVENIO%TYPE,
                                                  V_FUNCAO          IN   INT) RETURNS VOID AS $$                         
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO MAP_B2B_CONVENIOS VALUES (V_ID_SERVICO_B2B, V_CONVENIO, V_MAP_CONVENIO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE MAP_B2B_CONVENIOS SET MAP_CONVENIO = V_MAP_CONVENIO WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND CONVENIO = V_CONVENIO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE MAP_B2B_CONVENIOS WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND CONVENIO = V_CONVENIO;
     
  END IF;             

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_MAP_B2B_CONVENIOS;
/
