CREATE OR REPLACE FUNCTION PRC_MAP_B2B_PROCEDIMENTOS(V_ID_SERVICO_B2B  IN   MAP_B2B_PROCEDIMENTOS.ID_SERVICO_B2B%TYPE,
                                                      V_MNEMONICO       IN   MAP_B2B_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                      V_MAP_B2B         IN   MAP_B2B_PROCEDIMENTOS.MAP_B2B%TYPE,
                                                      V_FUNCAO          IN   INT) RETURNS VOID AS $$                         
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO MAP_B2B_PROCEDIMENTOS VALUES (V_ID_SERVICO_B2B, V_MNEMONICO, V_MAP_B2B);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE MAP_B2B_PROCEDIMENTOS SET MAP_B2B = V_MAP_B2B WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND MNEMONICO = V_MNEMONICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE MAP_B2B_PROCEDIMENTOS WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND MNEMONICO = V_MNEMONICO;
     
  END IF;             

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_MAP_B2B_PROCEDIMENTOS;
/
