CREATE OR REPLACE FUNCTION PRC_INS_PRODUTOS(V_PRODUTO IN PRODUTOS.PRODUTO%TYPE) RETURNS VOID AS $$
BEGIN
  INSERT INTO ESTOQUE SELECT V_PRODUTO, DEPARTAMENTO, 0, 0,0 FROM DEPARTAMENTOS;
  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_INS_PRODUTOS;
/
