CREATE OR REPLACE FUNCTION PRC_METODOS(V_METODO  IN OUT METODOS.METODO%TYPE,
                                        V_NOME    IN     METODOS.NOME%TYPE,
                                        V_FUNCAO  IN     INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_METODOS.NEXTVAL INTO V_METODO FROM DUAL;
     INSERT INTO METODOS VALUES (V_METODO, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE METODOS SET NOME = V_NOME WHERE METODO = V_METODO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE METODOS WHERE METODO = V_METODO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_METODOS;
/
