CREATE OR REPLACE FUNCTION PRC_CORRECAO_GUIAS_ATEND 
        (V_ID_ATENDIMENTO    IN CORRECAO_GUIAS_ATENDIMENTOS.ID_ATENDIMENTO%TYPE,
         V_CORREL_CORRECAO   IN CORRECAO_GUIAS_ATENDIMENTOS.CORREL_CORRECAO%TYPE,
         V_USUARIO           IN CORRECAO_GUIAS_ATENDIMENTOS.USUARIO%TYPE,
         V_DATA_CAD          IN CORRECAO_GUIAS_ATENDIMENTOS.DATA_CAD%TYPE,
         V_ESTACAO           IN CORRECAO_GUIAS_ATENDIMENTOS.ESTACAO%TYPE,
         V_CORRECAO          IN CORRECAO_GUIAS_ATENDIMENTOS.CORRECAO%TYPE,
         V_TIPO_MOVIMENTACAO IN CORRECAO_GUIAS_ATENDIMENTOS.TIPO_MOVIMENTACAO%TYPE,
         V_FUNCAO            IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CORRECAO_GUIAS_ATENDIMENTOS
            VALUES (V_ID_ATENDIMENTO, V_CORREL_CORRECAO, V_USUARIO, V_DATA_CAD,
                    V_ESTACAO, V_CORRECAO, V_TIPO_MOVIMENTACAO);
  ELSIF V_FUNCAO = 3 THEN
            DELETE CORRECAO_GUIAS_ATENDIMENTOS WHERE ID_ATENDIMENTO = V_ID_ATENDIMENTO AND CORREL_CORRECAO = V_CORREL_CORRECAO;

  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_CORRECAO_GUIAS_ATEND;