CREATE OR REPLACE FUNCTION PRC_RECALCULO(V_CONVENIO    IN ATENDIMENTOS.CONVENIO%TYPE,
                                          V_DATA_DESDE  IN ATENDIMENTOS.DATA_FAT%TYPE,
                                          V_DATA_ATE    IN ATENDIMENTOS.DATA_FAT%TYPE) RETURNS VOID AS $$
  DECLARE
  V_VALOR_CH DECIMAL(12,2);
  V_ATENDIMENTO ATENDIMENTOS.ATENDIMENTO%TYPE;
  V_POSTO ATENDIMENTOS.POSTO%TYPE;
  V_CATALOGO CONVENIOS.CATALOGO%TYPE;
  V_HONORARIOS CONVENIOS.HONORARIOS%TYPE;
  V_TABELA VARCHAR(9);
  V_DESCONTO DECIMAL(5,2);
  V_DESCONTO_ESPECIAL DECIMAL(5,2);

  CURSOR CUR_RECALCULO IS SELECT POSTO, ATENDIMENTO 
                            FROM ATENDIMENTOS 
                           WHERE CONVENIO  = V_CONVENIO 
                             AND DATA_FAT >= V_DATA_DESDE 
                             AND DATA_FAT <= V_DATA_ATE;

  CURSOR CUR_EXAMES IS SELECT CORREL, MNEMONICO, VALOR_HON 
                         FROM EXAMES 
                        WHERE POSTO = V_POSTO 
                          AND ATENDIMENTO = V_ATENDIMENTO
                   FOR UPDATE OF CORREL;

  BEGIN
BEGIN 
    SELECT CATALOGO, HONORARIOS, DESCONTO, DESCONTO_ESPECIAL INTO V_CATALOGO, V_HONORARIOS, V_DESCONTO, V_DESCONTO_ESPECIAL FROM CONVENIOS 
     WHERE CONVENIO = V_CONVENIO;

    V_TABELA   := 'TABELA' || V_CATALOGO;
 
    IF V_DESCONTO <> 0 THEN
       V_DESCONTO :=  V_DESCONTO / 100;
    ELSE
       V_DESCONTO :=  0;
    END IF;

    IF V_DESCONTO_ESPECIAL <> 0 THEN
       V_DESCONTO_ESPECIAL :=  V_DESCONTO_ESPECIAL / 100;
    ELSE
       V_DESCONTO_ESPECIAL :=  0;
    END IF;

    FOR RECALCULO_ATD IN CUR_RECALCULO LOOP
      V_POSTO       := RECALCULO_ATD.POSTO;
      V_ATENDIMENTO := RECALCULO_ATD.ATENDIMENTO;

      BEGIN
        FOR RECALCULO_EXA IN CUR_EXAMES LOOP
          PRC_RECALCULO2('SELECT VALOR_CH FROM ' || V_TABELA || ' WHERE MNEMONICO = ''' || RECALCULO_EXA.MNEMONICO || '''', V_VALOR_CH);
       
          UPDATE EXAMES SET VALOR_HON      = (V_HONORARIOS * V_VALOR_CH) - ((V_HONORARIOS * V_VALOR_CH) * V_DESCONTO),
                            VALOR_ESPECIAL = (V_HONORARIOS * V_VALOR_CH) - ((V_HONORARIOS * V_VALOR_CH) * V_DESCONTO_ESPECIAL) WHERE CURRENT OF CUR_EXAMES;

        END LOOP;
      END;
    END LOOP;
  END;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_RECALCULO;
/
