CREATE OR REPLACE FUNCTION PRC_CONDICOES_REFERENCIA(V_MNEMONICO     IN CONDICOES_REFERENCIA.MNEMONICO%TYPE,
                                            	     V_NUMERO        IN CONDICOES_REFERENCIA.NUMERO%TYPE,
                                                     V_CORREL        IN CONDICOES_REFERENCIA.CORREL%TYPE,
                                                     V_CONDICAO      IN CONDICOES_REFERENCIA.CONDICAO%TYPE,
                                                     V_FUNCAO        IN INT) RETURNS VOID AS
 DECLARE $$
CURSOR CUR_VARIAVEIS IS
  SELECT MNEMONICO, NUMERO, VARIAVEL FROM VARIAVEIS_TEXTOS WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO;

BEGIN

  IF V_FUNCAO = 1 THEN
     INSERT INTO CONDICOES_REFERENCIA VALUES (V_MNEMONICO, V_NUMERO, V_CORREL, V_CONDICAO); 

     FOR VARIAVEIS_CUR IN CUR_VARIAVEIS LOOP
         INSERT INTO VALORES_REFERENCIA VALUES (V_MNEMONICO, V_NUMERO, V_CORREL, VARIAVEIS_CUR.VARIAVEL, '');
     END LOOP;

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONDICOES_REFERENCIA SET CONDICAO = V_CONDICAO
                        WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND CORREL = V_CORREL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CONDICOES_REFERENCIA WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND CORREL = V_CORREL;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_CONDICOES_REFERENCIA;
/
