CREATE OR REPLACE FUNCTION PRC_RESULTADOS_TEXTOS(V_POSTO       IN RESULTADOS_TEXTOS.POSTO%TYPE, 
                                           	  V_ATENDIMENTO IN RESULTADOS_TEXTOS.ATENDIMENTO%TYPE, 
                                           	  V_CORREL      IN RESULTADOS_TEXTOS.CORREL%TYPE, 
                                           	  V_VALOR       IN RESULTADOS_TEXTOS.VALOR%TYPE, 
                                                  V_FUNCAO      IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO RESULTADOS_TEXTOS VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL, V_VALOR);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE RESULTADOS_TEXTOS SET VALOR = V_VALOR
                        WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL;
  ELSIF V_FUNCAO = 3 THEN
     DELETE RESULTADOS_TEXTOS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_RESULTADOS_TEXTOS;
/
