CREATE OR REPLACE FUNCTION PRC_CENTROS_RASTREO(V_CENTRO_RASTREIO  IN OUT CENTROS_RASTREO.CENTRO_RASTREIO%TYPE,
                                                V_NOME             IN     CENTROS_RASTREO.NOME%TYPE,
                                                V_TIPO_CENTRO      IN     CENTROS_RASTREO.NOME%TYPE,
                                                V_FUNCAO           IN     INT) RETURNS VOID AS $$                         
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_CENTRO_RASTREIO.NEXTVAL INTO V_CENTRO_RASTREIO FROM DUAL;
     INSERT INTO CENTROS_RASTREO VALUES (V_CENTRO_RASTREIO, V_NOME, V_TIPO_CENTRO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CENTROS_RASTREO SET NOME = V_NOME, TIPO_CENTRO = V_TIPO_CENTRO
      WHERE CENTRO_RASTREIO = V_CENTRO_RASTREIO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CENTROS_RASTREO WHERE CENTRO_RASTREIO = V_CENTRO_RASTREIO;
     
  END IF;             

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_CENTROS_RASTREO;
/
