CREATE OR REPLACE FUNCTION PRC_CONTAS_ATENDIMENTOS(V_CONTA_HOSP   IN OUT CONTAS_ATENDIMENTOS.CONTA_HOSP%TYPE,
                                                    V_POSTO        IN     CONTAS_ATENDIMENTOS.POSTO%TYPE,
                                                    V_ATENDIMENTO  IN     CONTAS_ATENDIMENTOS.ATENDIMENTO%TYPE,
                                                    V_FUNCAO       IN     INT) RETURNS VOID AS $$

BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CONTAS_ATENDIMENTOS VALUES (V_CONTA_HOSP, V_POSTO, V_ATENDIMENTO);

  ELSIF V_FUNCAO = 2 THEN
     SELECT SQ_CONTAS_ATENDIMENTOS.NEXTVAL INTO V_CONTA_HOSP FROM DUAL;
     INSERT INTO CONTAS_ATENDIMENTOS VALUES (V_CONTA_HOSP, V_POSTO, V_ATENDIMENTO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE CONTAS_ATENDIMENTOS WHERE CONTA_HOSP = V_CONTA_HOSP;

  ELSIF V_FUNCAO = 4 THEN
     DELETE CONTAS_ATENDIMENTOS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO;

  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_CONTAS_ATENDIMENTOS;
/
