CREATE OR REPLACE FUNCTION PRC_RESULTADOS_DIGITALIZADOS(V_POSTO         IN RESULTADOS_DIGITALIZADOS.POSTO%TYPE, 
                                                         V_ATENDIMENTO   IN RESULTADOS_DIGITALIZADOS.ATENDIMENTO%TYPE, 
                                                         V_CORREL        IN RESULTADOS_DIGITALIZADOS.CORREL%TYPE, 
                                                         V_LAUDO         IN RESULTADOS_DIGITALIZADOS.LAUDO%TYPE, 
                                                         V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO RESULTADOS_DIGITALIZADOS VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL, V_LAUDO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE RESULTADOS_DIGITALIZADOS SET LAUDO = V_LAUDO
                           WHERE POSTO  = V_POSTO  AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE RESULTADOS_DIGITALIZADOS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_RESULTADOS_DIGITALIZADOS;
/
