CREATE OR REPLACE FUNCTION PRC_EXAMES_CORRELACIONADOS(V_POSTO            IN EXAMES_CORRELACIONADOS.POSTO%TYPE,
                                                       V_ATENDIMENTO      IN EXAMES_CORRELACIONADOS.ATENDIMENTO%TYPE,
                                                       V_CORREL_DE        IN EXAMES_CORRELACIONADOS.CORREL_DE%TYPE,
                                                       V_CORREL_PARA      IN EXAMES_CORRELACIONADOS.CORREL_PARA%TYPE,
                                                       V_ORDEM_CORRELACAO IN OUT EXAMES_CORRELACIONADOS.ORDEM_CORRELACAO%TYPE,
                                                       V_FUNCAO           IN INT) RETURNS VOID AS $$
BEGIN                                                       
  IF V_FUNCAO = 1 THEN                 
     SELECT GET_MAX_ORDEM_CORRELACAO(V_POSTO,V_ATENDIMENTO)+1 INTO V_ORDEM_CORRELACAO FROM DUAL;
                     
     INSERT INTO EXAMES_CORRELACIONADOS
            VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL_DE, V_CORREL_PARA, V_ORDEM_CORRELACAO);

  ELSIF V_FUNCAO = 3 THEN
            DELETE EXAMES_CORRELACIONADOS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL_DE = V_CORREL_DE AND CORREL_PARA = V_CORREL_PARA;
  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_EXAMES_CORRELACIONADOS;
/
