CREATE OR REPLACE FUNCTION PRC_TIPOS_OPERACAO(V_TIPO_OPERACAO      IN OUT  TIPOS_OPERACAO.TIPO_OPERACAO%TYPE,
                                               V_NOME               IN      TIPOS_OPERACAO.NOME%TYPE,
                                               V_INPUT_OUTPUT       IN      TIPOS_OPERACAO.INPUT_OUTPUT%TYPE,
                                               V_FUNCAO             IN      INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_TIPOS_OPERACAO.NEXTVAL INTO V_TIPO_OPERACAO FROM DUAL;
     INSERT INTO TIPOS_OPERACAO VALUES (V_TIPO_OPERACAO, V_NOME, V_INPUT_OUTPUT);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE TIPOS_OPERACAO SET NOME = V_NOME, INPUT_OUTPUT = V_INPUT_OUTPUT
                        WHERE TIPO_OPERACAO = V_TIPO_OPERACAO;
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE TIPOS_OPERACAO WHERE TIPO_OPERACAO = V_TIPO_OPERACAO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_TIPOS_OPERACAO;
/
