CREATE OR REPLACE FUNCTION PRC_PROCEDIMENTOS_AUTORIZACAO(V_MNEMONICO        IN  PROCEDIMENTOS_AUTORIZACAO.MNEMONICO%TYPE,
                                                          V_CONVENIO         IN  PROCEDIMENTOS_AUTORIZACAO.CONVENIO%TYPE,
                                                          V_TIPO_AUTORIZACAO IN  PROCEDIMENTOS_AUTORIZACAO.TIPO_AUTORIZACAO%TYPE,
                                                          V_FUNCAO           IN  INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PROCEDIMENTOS_AUTORIZACAO VALUES (V_MNEMONICO, V_CONVENIO, V_TIPO_AUTORIZACAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE PROCEDIMENTOS_AUTORIZACAO SET TIPO_AUTORIZACAO = V_TIPO_AUTORIZACAO
                                            WHERE MNEMONICO = V_MNEMONICO AND CONVENIO   = V_CONVENIO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE PROCEDIMENTOS_AUTORIZACAO WHERE MNEMONICO = V_MNEMONICO AND CONVENIO = V_CONVENIO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_PROCEDIMENTOS_AUTORIZACAO;
/
