CREATE OR REPLACE FUNCTION PRC_METODOS_PROCEDIMENTOS(V_ID_PROCEDIMENTO IN  METODOS_PROCEDIMENTOS.ID_PROCEDIMENTO%TYPE,
                                                      V_ID_METODO       IN  METODOS_PROCEDIMENTOS.ID_METODO%TYPE,
                                                      V_STATUS          IN  METODOS_PROCEDIMENTOS.STATUS%TYPE,
                                                      V_FUNCAO          IN  INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO METODOS_PROCEDIMENTOS VALUES (V_ID_PROCEDIMENTO, V_ID_METODO, V_STATUS);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE METODOS_PROCEDIMENTOS SET STATUS = V_STATUS
                                WHERE ID_PROCEDIMENTO = V_ID_PROCEDIMENTO AND ID_METODO = V_ID_METODO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE METODOS_PROCEDIMENTOS WHERE ID_PROCEDIMENTO = V_ID_PROCEDIMENTO AND ID_METODO = V_ID_METODO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_METODOS_PROCEDIMENTOS;
/
