CREATE OR REPLACE FUNCTION PRC_PLANILHA_RESULTADOS(V_MNEMONICO IN  PLANILHA_RESULTADOS.MNEMONICO%TYPE,
                                                    V_PLANILHA  IN  PLANILHA_RESULTADOS.PLANILHA%TYPE,
                                                    V_FUNCAO    IN  INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PLANILHA_RESULTADOS VALUES (V_MNEMONICO, V_PLANILHA);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE PLANILHA_RESULTADOS SET PLANILHA = V_PLANILHA WHERE MNEMONICO = V_MNEMONICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE PLANILHA_RESULTADOS WHERE MNEMONICO = V_MNEMONICO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_PLANILHA_RESULTADOS;
/
