CREATE OR REPLACE FUNCTION PRC_POSTOS_PROCEDIMENTOS(V_MNEMONICO IN  POSTOS_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                     V_POSTO     IN  POSTOS_PROCEDIMENTOS.POSTO%TYPE,
                                                     V_PADRAO    IN  POSTOS_PROCEDIMENTOS.PADRAO%TYPE,
                                                     V_FUNCAO    IN  INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO POSTOS_PROCEDIMENTOS VALUES (V_MNEMONICO, V_POSTO, V_PADRAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE POSTOS_PROCEDIMENTOS SET PADRAO = V_PADRAO
                                       WHERE MNEMONICO = V_MNEMONICO AND POSTO = V_POSTO;
                    
  ELSIF V_FUNCAO = 3 THEN
     DELETE POSTOS_PROCEDIMENTOS WHERE MNEMONICO = V_MNEMONICO AND POSTO = V_POSTO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_POSTOS_PROCEDIMENTOS;
/
