CREATE OR REPLACE FUNCTION PRC_CATALOGO_PORTES_MEDICOS(V_ID_TABELA_PORTE_MEDICO IN OUT CATALOGO_PORTES_MEDICOS.ID_TABELA_PORTE_MEDICO%TYPE,
                                                        V_NOME                   IN     CATALOGO_PORTES_MEDICOS.NOME%TYPE,
                                                        V_FUNCAO                 IN     INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_CATALOGO_PORTES_MEDICOS.NEXTVAL INTO V_ID_TABELA_PORTE_MEDICO FROM DUAL;
     INSERT INTO CATALOGO_PORTES_MEDICOS VALUES (V_ID_TABELA_PORTE_MEDICO, V_NOME);


  ELSIF V_FUNCAO = 2 THEN
     UPDATE CATALOGO_PORTES_MEDICOS SET NOME = V_NOME
                           WHERE ID_TABELA_PORTE_MEDICO = V_ID_TABELA_PORTE_MEDICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CATALOGO_PORTES_MEDICOS WHERE ID_TABELA_PORTE_MEDICO = V_ID_TABELA_PORTE_MEDICO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_CATALOGO_PORTES_MEDICOS;

