CREATE OR REPLACE FUNCTION PRC_VARIAVEIS_TEXTOS(V_MNEMONICO     IN VARIAVEIS_TEXTOS.MNEMONICO%TYPE,
                                                 V_NUMERO        IN VARIAVEIS_TEXTOS.NUMERO%TYPE,
                                                 V_VARIAVEL      IN VARIAVEIS_TEXTOS.VARIAVEL%TYPE,
                                                 V_COMPARTILHADO IN VARIAVEIS_TEXTOS.COMPARTILHADO%TYPE,
                                                 V_OBRIGATORIO   IN VARIAVEIS_TEXTOS.OBRIGATORIO%TYPE,
                                                 V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO VARIAVEIS_TEXTOS VALUES (V_MNEMONICO, V_NUMERO, V_VARIAVEL, V_COMPARTILHADO, V_OBRIGATORIO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE VARIAVEIS_TEXTOS SET OBRIGATORIO = V_OBRIGATORIO
      WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE VARIAVEIS_TEXTOS WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_VARIAVEIS_TEXTOS;
/

