CREATE OR REPLACE FUNCTION PRC_CORRELACOES(V_TIPO_CORRELACAO   IN CORRELACOES.TIPO_CORRELACAO%TYPE,
                                            V_MNEMONICO_DE      IN CORRELACOES.MNEMONICO_DE%TYPE,
                                            V_MNEMONICO_PARA    IN CORRELACOES.MNEMONICO_PARA%TYPE,
                                            V_FUNCAO            IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CORRELACOES VALUES (V_TIPO_CORRELACAO, V_MNEMONICO_DE, V_MNEMONICO_PARA);

  ELSIF V_FUNCAO = 3 THEN
     DELETE CORRELACOES WHERE TIPO_CORRELACAO = V_TIPO_CORRELACAO AND MNEMONICO_DE = V_MNEMONICO_DE AND MNEMONICO_PARA = V_MNEMONICO_PARA;

  ELSIF V_FUNCAO = 4 THEN
     DELETE CORRELACOES WHERE TIPO_CORRELACAO = V_TIPO_CORRELACAO AND MNEMONICO_DE = V_MNEMONICO_DE;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_CORRELACOES;
/
