CREATE OR REPLACE FUNCTION PRC_LAYOUTS(V_ID_LAYOUT     IN OUT LAYOUTS.ID_LAYOUT%TYPE, 
                                        V_NOME          IN LAYOUTS.NOME%TYPE,  
                                        V_STATUS        IN LAYOUTS.STATUS%TYPE,  
                                        V_TIPO_LAYOUT   IN LAYOUTS.TIPO_LAYOUT%TYPE,  
                                        V_GERAL         IN LAYOUTS.GERAL%TYPE,  
                                        V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_LAYOUT.NEXTVAL INTO V_ID_LAYOUT FROM DUAL;
     INSERT INTO LAYOUTS VALUES (V_ID_LAYOUT, V_NOME, V_STATUS, V_TIPO_LAYOUT, V_GERAL, V_EMPTY_BLOB);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE LAYOUTS SET NOME = V_NOME, STATUS = V_STATUS, TIPO_LAYOUT = V_TIPO_LAYOUT, GERAL = V_GERAL 
                  WHERE ID_LAYOUT = V_ID_LAYOUT;

  ELSIF V_FUNCAO = 3 THEN
     DELETE LAYOUTS WHERE ID_LAYOUT = V_ID_LAYOUT;

  ELSIF V_FUNCAO = 4 THEN
     UPDATE LAYOUTS SET GERAL = 'N';
     UPDATE LAYOUTS SET GERAL = 'S'
                  WHERE ID_LAYOUT = V_ID_LAYOUT;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_LAYOUTS;
/
