CREATE OR REPLACE FUNCTION PRC_WORKLIST_NAO_ACHADOS(V_EQUIPAMENTO   IN WORKLIST_NAO_ACHADOS.EQUIPAMENTO%TYPE,
                                                     V_DATA          IN WORKLIST_NAO_ACHADOS.DATA%TYPE,
                                                     V_HORA          IN WORKLIST_NAO_ACHADOS.HORA%TYPE,
                                                     V_SPECIMEN_ID   IN WORKLIST_NAO_ACHADOS.SPECIMEN_ID%TYPE,
                                                     V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO WORKLIST_NAO_ACHADOS VALUES (V_EQUIPAMENTO, V_DATA, V_HORA, V_SPECIMEN_ID); 

  ELSIF V_FUNCAO = 3 THEN
     DELETE WORKLIST_NAO_ACHADOS WHERE EQUIPAMENTO = V_EQUIPAMENTO AND DATA = V_DATA AND
                                             HORA = V_HORA AND SPECIMEN_ID = V_SPECIMEN_ID;
  ELSIF V_FUNCAO = 4 THEN
     DELETE WORKLIST_NAO_ACHADOS WHERE EQUIPAMENTO = V_EQUIPAMENTO AND DATA <= V_DATA;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_WORKLIST_NAO_ACHADOS;
/
