CREATE OR REPLACE FUNCTION PRC_SINALIZACOES_EVOLUCAO(V_ID_SINALIZACAO  IN OUT SINALIZACOES_EVOLUCAO.ID_SINALIZACAO%TYPE,
                                                      V_NOME            IN     SINALIZACOES_EVOLUCAO.NOME%TYPE,
                                                      V_DESCRICAO       IN     SINALIZACOES_EVOLUCAO.DESCRICAO%TYPE,
                                                      V_TAG_MARCACAO    IN     SINALIZACOES_EVOLUCAO.TAG_MARCACAO%TYPE,
                                                      V_COR_MARCACAO    IN     SINALIZACOES_EVOLUCAO.COR_MARCACAO%TYPE,
                				                      V_TIPO_MARCACAO   IN     SINALIZACOES_EVOLUCAO.TIPO_MARCACAO%TYPE,
                                                      V_FUNCAO          IN     INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_SINALIZACAO_EVOLUCAO.NEXTVAL INTO V_ID_SINALIZACAO FROM DUAL;
     INSERT INTO SINALIZACOES_EVOLUCAO VALUES (V_ID_SINALIZACAO, V_NOME, V_DESCRICAO, V_TAG_MARCACAO, V_COR_MARCACAO, V_TIPO_MARCACAO);
     

  ELSIF V_FUNCAO = 2 THEN
     UPDATE SINALIZACOES_EVOLUCAO SET NOME = V_NOME, DESCRICAO = V_DESCRICAO, TAG_MARCACAO := V_TAG_MARCACAO, COR_MARCACAO = V_COR_MARCACAO, TIPO_MARCACAO = V_TIPO_MARCACAO
                           WHERE ID_SINALIZACAO = V_ID_SINALIZACAO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE SINALIZACOES_EVOLUCAO WHERE ID_SINALIZACAO = V_ID_SINALIZACAO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_SINALIZACOES_EVOLUCAO;
/

