CREATE OR REPLACE FUNCTION PRC_CATALOGO_TEMPOS_ENTREGA(V_ID_TEMPO_ENTREGA IN OUT CATALOGO_TEMPOS_ENTREGA.ID_TEMPO_ENTREGA%TYPE,
                                                        V_NOME             IN     CATALOGO_TEMPOS_ENTREGA.NOME%TYPE,
                                                        V_FUNCAO           IN INT) RETURNS VOID AS $$
BEGIN                                                           
  IF V_FUNCAO = 1 THEN                                          
     SELECT SQ_TEMPOS_ENTREGA.NEXTVAL INTO V_ID_TEMPO_ENTREGA FROM DUAL;
     INSERT INTO CATALOGO_TEMPOS_ENTREGA VALUES(V_ID_TEMPO_ENTREGA, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
            UPDATE CATALOGO_TEMPOS_ENTREGA SET NOME = V_NOME
             WHERE ID_TEMPO_ENTREGA = V_ID_TEMPO_ENTREGA;
  ELSIF V_FUNCAO = 3 THEN
            DELETE CATALOGO_TEMPOS_ENTREGA WHERE ID_TEMPO_ENTREGA = V_ID_TEMPO_ENTREGA;
  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_CATALOGO_TEMPOS_ENTREGA;
/
