CREATE OR REPLACE FUNCTION PRC_PREPAROS(V_MNEMONICO     IN OUT PREPAROS.MNEMONICO%TYPE,
                                         V_PREPARO       IN PREPAROS.PREPARO%TYPE,
                                         V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PREPAROS VALUES (V_MNEMONICO, V_PREPARO); 

  ELSIF V_FUNCAO = 2 THEN
     UPDATE PREPAROS SET PREPARO = V_PREPARO
                        WHERE MNEMONICO = V_MNEMONICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE PREPAROS WHERE MNEMONICO = V_MNEMONICO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_PREPAROS;
/
