CREATE OR REPLACE FUNCTION PRC_FAT_PERIODO(V_FATURAMENTO IN ATENDIMENTOS.FATURAMENTO%TYPE,
                                            V_DATA_FAT    IN ATENDIMENTOS.DATA_FAT%TYPE,
                                            V_DATA_FAT2   IN ATENDIMENTOS.DATA_FAT%TYPE) RETURNS VOID AS $$
BEGIN
  UPDATE ATENDIMENTOS SET FATURAMENTO = V_FATURAMENTO WHERE
         DATA_FAT >= V_DATA_FAT AND DATA_FAT <= V_DATA_FAT2;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_FAT_PERIODO;
/
