CREATE OR REPLACE FUNCTION PRC_MAP_B2B_MATERIAIS(V_ID_SERVICO_B2B  IN   MAP_B2B_MATERIAIS.ID_SERVICO_B2B%TYPE,
                                                  V_MATERIAL        IN   MAP_B2B_MATERIAIS.MATERIAL%TYPE,
                                                  V_MAP_MATERIAL    IN   MAP_B2B_MATERIAIS.MAP_MATERIAL%TYPE,
                                                  V_NOME            IN   MAP_B2B_MATERIAIS.NOME%TYPE,
                                                  V_FUNCAO          IN   INT) RETURNS VOID AS $$                         
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO MAP_B2B_MATERIAIS VALUES (V_ID_SERVICO_B2B, V_MATERIAL, V_MAP_MATERIAL, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE MAP_B2B_MATERIAIS SET MAP_MATERIAL = V_MAP_MATERIAL, NOME = V_NOME WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND MATERIAL = V_MATERIAL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE MAP_B2B_MATERIAIS WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND MATERIAL = V_MATERIAL;
     
  END IF;             

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_MAP_B2B_MATERIAIS;
/
