CREATE OR REPLACE FUNCTION PRC_VARIAVEIS_FRASES(V_VARIAVEL      IN VARIAVEIS_FRASES.VARIAVEL%TYPE,
                                                 V_CODIGO        IN VARIAVEIS_FRASES.CODIGO%TYPE,
                                                 V_MNEMONICO     IN VARIAVEIS_FRASES.MNEMONICO%TYPE,
                                                 V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO VARIAVEIS_FRASES VALUES (V_VARIAVEL, V_CODIGO, V_MNEMONICO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE VARIAVEIS_FRASES WHERE VARIAVEL = V_VARIAVEL AND CODIGO = V_CODIGO AND MNEMONICO = V_MNEMONICO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_VARIAVEIS_FRASES;
/

