CREATE OR REPLACE FUNCTION PRC_ORIENTACOES_PROCEDIMENTOS(V_MNEMONICO         IN ORIENTACOES_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                          V_ID_ORIENTACAO     IN ORIENTACOES_PROCEDIMENTOS.ID_ORIENTACAO%TYPE,
                                                          V_FUNCAO            IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO ORIENTACOES_PROCEDIMENTOS VALUES (V_MNEMONICO, V_ID_ORIENTACAO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE ORIENTACOES_PROCEDIMENTOS WHERE ID_ORIENTACAO = V_ID_ORIENTACAO AND MNEMONICO = V_MNEMONICO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_ORIENTACOES_PROCEDIMENTOS;
/
