CREATE OR REPLACE FUNCTION PRC_DEPARTAMENTOS_PRODUTOS(V_DEPARTAMENTO IN DEPARTAMENTOS_PRODUTOS.DEPARTAMENTO%TYPE,
                                                        V_PRODUTO     IN DEPARTAMENTOS_PRODUTOS.PRODUTO%TYPE,
                                                        V_QTD_ATUAL   IN DEPARTAMENTOS_PRODUTOS.QTD_ATUAL%TYPE,
                                                        V_FUNCAO      IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO DEPARTAMENTOS_PRODUTOS VALUES (V_DEPARTAMENTO, V_PRODUTO, V_QTD_ATUAL);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE DEPARTAMENTOS_PRODUTOS SET QTD_ATUAL = V_QTD_ATUAL WHERE DEPARTAMENTO = V_DEPARTAMENTO AND PRODUTO = V_PRODUTO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE DEPARTAMENTOS_PRODUTOS WHERE DEPARTAMENTO = V_DEPARTAMENTO AND PRODUTO = V_PRODUTO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_DEPARTAMENTOS_PRODUTOS;
/
