CREATE OR REPLACE FUNCTION PRC_ENTRADAS_PRODUTOS(V_NUMERO_COMPRA      IN ENTRADAS_PRODUTOS.NUMERO_COMPRA%TYPE,
                             		          V_CORREL_RECEBIMENTO IN ENTRADAS_PRODUTOS.CORREL_RECEBIMENTO%TYPE,
                             		          V_CORREL             IN ENTRADAS_PRODUTOS.CORREL%TYPE,
                             		          V_PRODUTO_ID         IN ENTRADAS_PRODUTOS.PRODUTO_ID%TYPE,
                             		          V_QTD                IN ENTRADAS_PRODUTOS.QTD%TYPE,
                                                  V_DATA_FABRICACAO    IN ENTRADAS_PRODUTOS.DATA_FABRICACAO%TYPE,
                                                  V_DIAS_VALIDADE      IN ENTRADAS_PRODUTOS.DIAS_VALIDADE%TYPE,
                                                  V_DATA_VALIDADE      IN ENTRADAS_PRODUTOS.DATA_VALIDADE%TYPE,
                                  	              V_FUNCAO             IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO ENTRADAS_PRODUTOS VALUES (V_NUMERO_COMPRA, V_CORREL_RECEBIMENTO, V_CORREL, 
								 V_PRODUTO_ID, V_QTD, V_DATA_FABRICACAO, V_DIAS_VALIDADE, 
								 V_DATA_VALIDADE);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE ENTRADAS_PRODUTOS SET QTD = V_QTD, DATA_FABRICACAO = V_DATA_FABRICACAO, 
                                        DIAS_VALIDADE = V_DIAS_VALIDADE, 
                                        DATA_VALIDADE = V_DATA_VALIDADE 
	WHERE NUMERO_COMPRA = V_NUMERO_COMPRA AND CORREL_RECEBIMENTO = V_CORREL_RECEBIMENTO AND CORREL = V_CORREL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE ENTRADAS_PRODUTOS WHERE NUMERO_COMPRA = V_NUMERO_COMPRA AND 
							CORREL_RECEBIMENTO = V_CORREL_RECEBIMENTO AND 
							CORREL = V_CORREL;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_ENTRADAS_PRODUTOS;
/