CREATE OR REPLACE FUNCTION PRC_CONVERSOES(V_ID_CONVERSAO        IN OUT CONVERSOES.ID_CONVERSAO%TYPE,
                                           V_NOME_CONVERSAO      IN     CONVERSOES.NOME_CONVERSAO%TYPE,
                                           V_TIPO_CONVERSAO      IN     CONVERSOES.TIPO_CONVERSAO%TYPE,
										   V_FORMULA_CONVERSAO   IN     CONVERSOES.FORMULA_CONVERSAO%TYPE,
                                           V_FUNCAO              IN     INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_CONVERSAO.NEXTVAL INTO V_ID_CONVERSAO FROM DUAL;
     INSERT INTO CONVERSOES VALUES (V_ID_CONVERSAO, V_NOME_CONVERSAO, V_TIPO_CONVERSAO, V_FORMULA_CONVERSAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONVERSOES SET NOME_CONVERSAO = V_NOME_CONVERSAO, TIPO_CONVERSAO = V_TIPO_CONVERSAO, FORMULA_CONVERSAO = V_FORMULA_CONVERSAO
      WHERE ID_CONVERSAO = V_ID_CONVERSAO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CONVERSOES WHERE ID_CONVERSAO = V_ID_CONVERSAO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_CONVERSOES;
