CREATE OR REPLACE FUNCTION PRC_POSTOS_MEDICOS_RESP(V_POSTO           IN POSTOS_MEDICOS_RESPONSAVEIS.POSTO%TYPE,
                                                    V_CRM_RESPONSAVEL IN POSTOS_MEDICOS_RESPONSAVEIS.CRM_RESPONSAVEL%TYPE,
                                                    V_SETOR           IN POSTOS_MEDICOS_RESPONSAVEIS.SETOR%TYPE,
                                                    V_FUNCAO          IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO POSTOS_MEDICOS_RESPONSAVEIS VALUES (V_POSTO, V_CRM_RESPONSAVEL, V_SETOR);
 
  ELSIF V_FUNCAO = 3 THEN
     DELETE POSTOS_MEDICOS_RESPONSAVEIS WHERE POSTO = V_POSTO AND CRM_RESPONSAVEL = V_CRM_RESPONSAVEL AND SETOR = V_SETOR;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_POSTOS_MEDICOS_RESP;
/
