CREATE OR REPLACE FUNCTION PRC_TEMPOS_COLETA_PROCED(V_ID_TEMPO_COLETA IN TEMPOS_COLETA_PROCEDIMENTOS.ID_TEMPO_COLETA%TYPE,
                                                     V_MNEMONICO       IN TEMPOS_COLETA_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                     V_FUNCAO          IN INT) RETURNS VOID AS $$
BEGIN                                                           
  IF V_FUNCAO = 1 THEN                                          
     INSERT INTO TEMPOS_COLETA_PROCEDIMENTOS VALUES(V_ID_TEMPO_COLETA, V_MNEMONICO);


  ELSIF V_FUNCAO = 3 THEN
            DELETE TEMPOS_COLETA_PROCEDIMENTOS WHERE ID_TEMPO_COLETA = V_ID_TEMPO_COLETA AND MNEMONICO = V_MNEMONICO;	

  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_TEMPOS_COLETA_PROCED;
/
