CREATE OR REPLACE FUNCTION PRC_ACOMODACOES(V_ID_ACOMODACAO IN OUT ACOMODACOES.ID_ACOMODACAO%TYPE, 
                                            V_NOME          IN ACOMODACOES.NOME%TYPE,  
                                            V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_ACOMODACAO.NEXTVAL INTO V_ID_ACOMODACAO FROM DUAL;
     INSERT INTO ACOMODACOES VALUES (V_ID_ACOMODACAO, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE ACOMODACOES SET NOME = V_NOME WHERE ID_ACOMODACAO = V_ID_ACOMODACAO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE ACOMODACOES WHERE ID_ACOMODACAO = V_ID_ACOMODACAO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_ACOMODACOES;
/
