CREATE OR REPLACE FUNCTION PRC_POSTOS_SERVICOS(V_ID_POSTO       IN POSTOS_SERVICOS.ID_POSTO%TYPE,
                                                V_ID_SERVICO_ADM IN POSTOS_SERVICOS.ID_SERVICO_ADM%TYPE,
                                                V_FUNCAO         IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO POSTOS_SERVICOS VALUES (V_ID_POSTO, V_ID_SERVICO_ADM);
 
  ELSIF V_FUNCAO = 3 THEN
     DELETE POSTOS_SERVICOS WHERE ID_POSTO = V_ID_POSTO AND ID_SERVICO_ADM = V_ID_SERVICO_ADM;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_POSTOS_SERVICOS;
/
