CREATE OR REPLACE FUNCTION PRC_EMPRESAS_CONVENIADAS(V_ID_EMPRESA_CONVENIADA IN OUT EMPRESAS_CONVENIADAS.ID_EMPRESA_CONVENIADA%TYPE,
                                                     V_NOME                  IN     EMPRESAS_CONVENIADAS.NOME%TYPE,
                                                     V_STATUS                IN     EMPRESAS_CONVENIADAS.STATUS%TYPE,
                                                     V_PASS_WEB              IN     EMPRESAS_CONVENIADAS.PASS_WEB%TYPE,
                                                     V_CNPJ                  IN     EMPRESAS_CONVENIADAS.CNPJ%TYPE,
                                                     V_FUNCAO                IN     INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_EMPRESA_CONVENIADA.NEXTVAL INTO V_ID_EMPRESA_CONVENIADA FROM DUAL;
     INSERT INTO EMPRESAS_CONVENIADAS VALUES (V_ID_EMPRESA_CONVENIADA, V_NOME, V_STATUS, V_PASS_WEB, V_CNPJ);

  ELSIF V_FUNCAO = 2 THEN
        UPDATE EMPRESAS_CONVENIADAS SET NOME = V_NOME, STATUS = V_STATUS, PASS_WEB = V_PASS_WEB, CNPJ = V_CNPJ
                          WHERE ID_EMPRESA_CONVENIADA = V_ID_EMPRESA_CONVENIADA;

  ELSIF V_FUNCAO = 3 THEN
     DELETE EMPRESAS_CONVENIADAS WHERE ID_EMPRESA_CONVENIADA = V_ID_EMPRESA_CONVENIADA;
  END IF;

  /* COMMIT WORK; */
END;
$$ LANGUAGE plpgsql; PRC_EMPRESAS_CONVENIADAS;
/

