CREATE OR REPLACE FUNCTION PRC_CENTROS_RASTREO(V_CENTRO_RASTREO  IN OUT CENTROS_RASTREO.CENTRO_RASTREO%TYPE,
                                                V_NOME            IN     CENTROS_RASTREO.NOME%TYPE,
                                                V_FUNCAO          IN     INT) RETURNS VOID AS $$                         
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_CENTRO_RASTREO.NEXTVAL INTO V_CENTRO_RASTREO FROM DUAL;
     INSERT INTO CENTROS_RASTREO VALUES (V_CENTRO_RASTREO, V_NOME);

  ELSIF V_FUNCAO = 3 THEN
     DELETE CENTROS_RASTREO WHERE CENTRO_RASTREO = V_CENTRO_RASTREO;
     
  END IF;             

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_CENTROS_RASTREO;
/
