CREATE OR REPLACE FUNCTION PRC_RESULTADOS_STREAMS(V_POSTO         IN RESULTADOS_STREAMS.POSTO%TYPE, 
                                                   V_ATENDIMENTO   IN RESULTADOS_STREAMS.ATENDIMENTO%TYPE, 
                                                   V_CORREL        IN RESULTADOS_STREAMS.CORREL%TYPE, 
                                                   V_NUMERO        IN RESULTADOS_STREAMS.NUMERO%TYPE, 
                                                   V_VARIAVEL      IN RESULTADOS_STREAMS.VARIAVEL%TYPE, 
                                                   V_STREAM        IN RESULTADOS_STREAMS.STREAM%TYPE, 
                                                   V_USUARIO_AUTO  IN RESULTADOS_STREAMS.USUARIO_AUTO%TYPE,
                                                   V_DATA_AUTO     IN RESULTADOS_STREAMS.DATA_AUTO%TYPE,
                                                   V_ESTACAO_AUTO  IN RESULTADOS_STREAMS.ESTACAO_AUTO%TYPE,
                                                   V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO RESULTADOS_STREAMS VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL, V_NUMERO, V_VARIAVEL, V_STREAM,
                                          V_USUARIO_AUTO, V_DATA_AUTO, V_ESTACAO_AUTO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE RESULTADOS_STREAMS SET STREAM = V_STREAM, USUARIO_AUTO = V_USUARIO_AUTO, DATA_AUTO = V_DATA_AUTO, ESTACAO_AUTO = V_ESTACAO_AUTO
                           WHERE POSTO  = V_POSTO  AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL AND 
                                 NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE RESULTADOS_STREAMS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL;

  ELSIF V_FUNCAO = 4 THEN
     DELETE RESULTADOS_STREAMS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL AND NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_RESULTADOS_STREAMS;
/
