CREATE OR REPLACE FUNCTION PRC_ACTIONS(V_ACTION       IN OUT ACTIONS.ACTION%TYPE,
                                        V_CATEGORIA    IN ACTIONS.CATEGORIA%TYPE,
                                        V_MODULO       IN ACTIONS.MODULO%TYPE,
                                        V_DESCRICAO    IN ACTIONS.DESCRICAO%TYPE,
                                        V_FUNCAO       IN INT) RETURNS VOID AS $$

BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO ACTIONS VALUES (V_ACTION,  V_CATEGORIA, V_MODULO, V_DESCRICAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE ACTIONS SET DESCRICAO = V_DESCRICAO WHERE ACTION = V_ACTION;

  ELSIF V_FUNCAO = 3 THEN
     DELETE ACTIONS WHERE ACTION = V_ACTION AND MODULO = V_MODULO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_ACTIONS;
/

