CREATE OR REPLACE FUNCTION PRC_TERMOS_PROCEDIMENTOS(V_MNEMONICO  IN  TERMOS_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                     V_TERMO      IN  TERMOS_PROCEDIMENTOS.TERMO%TYPE,
                                                     V_DATA_CAD   IN  TERMOS_PROCEDIMENTOS.DATA_CAD%TYPE,
                                                     V_USUARIO    IN  TERMOS_PROCEDIMENTOS.USUARIO%TYPE,
                                                     V_FUNCAO     IN  INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO TERMOS_PROCEDIMENTOS VALUES (V_MNEMONICO, V_TERMO, V_DATA_CAD, V_USUARIO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE TERMOS_PROCEDIMENTOS SET TERMO = V_TERMO, DATA_CAD = V_DATA_CAD, USUARIO = V_USUARIO
                                            WHERE MNEMONICO = V_MNEMONICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE TERMOS_PROCEDIMENTOS WHERE MNEMONICO = V_MNEMONICO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_TERMOS_PROCEDIMENTOS;
/
