CREATE OR REPLACE FUNCTION PRC_GRUPOS_OBJ_POSTOS(V_GRUPO_OBJ         IN     GRUPOS_OBJ_POSTOS.GRUPO_OBJ%TYPE,
                                                  V_POSTO             IN     GRUPOS_OBJ_POSTOS.POSTO%TYPE,
                                                  V_FUNCAO            IN     INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO GRUPOS_OBJ_POSTOS VALUES (V_GRUPO_OBJ, V_POSTO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE GRUPOS_OBJ_POSTOS WHERE GRUPO_OBJ = V_GRUPO_OBJ AND POSTO = V_POSTO;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_GRUPOS_OBJ_POSTOS;
