CREATE OR REPLACE FUNCTION PRC_TEXTOS_COMPARTILHADOS(V_MNEMONICO          IN OUT TEXTOS_COMPARTILHADOS.MNEMONICO%TYPE,
                                      		      V_NUMERO             IN     TEXTOS_COMPARTILHADOS.NUMERO%TYPE,
                                       		      V_MNEM_COMPARTILHADO IN     TEXTOS_COMPARTILHADOS.MNEM_COMPARTILHADO%TYPE,
                                       	              V_NUM_COMPARTILHADO  IN     TEXTOS_COMPARTILHADOS.NUM_COMPARTILHADO%TYPE,
                                       		      V_FUNCAO             IN     INT) RETURNS VOID AS
 DECLARE $$
CURSOR CUR_VARIAVEIS_TEXTOS IS
  SELECT MNEMONICO, NUMERO, VARIAVEL 
    FROM VARIAVEIS_TEXTOS
   WHERE MNEMONICO = V_MNEM_COMPARTILHADO AND NUMERO = V_NUM_COMPARTILHADO 
     AND (VARIAVEL) NOT IN (SELECT VT.VARIAVEL
                              FROM VARIAVEIS_TEXTOS VT
                             WHERE VT.MNEMONICO = V_MNEMONICO 
                               AND VT.NUMERO = V_NUMERO);

BEGIN

  IF V_FUNCAO = 1 THEN
     INSERT INTO TEXTOS_COMPARTILHADOS VALUES (V_MNEMONICO, V_NUMERO, V_MNEM_COMPARTILHADO, V_NUM_COMPARTILHADO); 

     IF (V_MNEMONICO <> V_MNEM_COMPARTILHADO) OR (V_NUMERO <> V_NUM_COMPARTILHADO) THEN

     	  FOR VARIAVEIS_TEXTOS_CUR IN CUR_VARIAVEIS_TEXTOS LOOP
            INSERT INTO VARIAVEIS_TEXTOS VALUES (V_MNEMONICO, V_NUMERO, VARIAVEIS_TEXTOS_CUR.VARIAVEL, 'S');
        END LOOP;
     END IF;


  ELSIF V_FUNCAO = 3 THEN
     DELETE TEXTOS_COMPARTILHADOS WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND
                                              MNEM_COMPARTILHADO = V_MNEM_COMPARTILHADO AND 
                                              NUM_COMPARTILHADO = V_NUM_COMPARTILHADO;

     FOR VARIAVEIS_TEXTOS_CUR IN CUR_VARIAVEIS_TEXTOS LOOP
         DELETE VARIAVEIS_TEXTOS WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND 
                                             VARIAVEL = VARIAVEIS_TEXTOS_CUR.VARIAVEL;
     END LOOP;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_TEXTOS_COMPARTILHADOS;
/
