CREATE OR REPLACE FUNCTION PRC_TRANSACOES_LIS(V_ID_TRANSACAO_LIS  IN OUT LIS.TRANSACOES_LIS.ID_TRANSACAO_LIS%TYPE,
                                               V_ID_ATENDIMENTO    IN LIS.TRANSACOES_LIS.ID_ATENDIMENTO%TYPE,
                                               V_SPECIMEN_ID       IN LIS.TRANSACOES_LIS.SPECIMEN_ID%TYPE,
                                               V_LOTE_TRANSACAO    IN LIS.TRANSACOES_LIS.LOTE_TRANSACAO%TYPE,
                                               V_ID_AUTOMACAO      IN LIS.TRANSACOES_LIS.ID_AUTOMACAO%TYPE,
                                               V_USUARIO_TRANSACAO IN LIS.TRANSACOES_LIS.USUARIO_TRANSACAO%TYPE,
                                               V_DATA_TRANSACAO    IN LIS.TRANSACOES_LIS.DATA_TRANSACAO%TYPE,
                                               V_ESTACAO_TRANSACAO IN LIS.TRANSACOES_LIS.ESTACAO_TRANSACAO%TYPE,
                                               V_TIPO_TRANSACAO    IN LIS.TRANSACOES_LIS.TIPO_TRANSACAO%TYPE,
                                               V_TRANSACAO         IN LIS.TRANSACOES_LIS.TRANSACAO%TYPE,
                                               V_STATUS_TRANSACAO  IN LIS.TRANSACOES_LIS.STATUS_TRANSACAO%TYPE,
                                               V_FUNCAO            IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_TRANSACAO_LIS.NEXTVAL INTO V_ID_TRANSACAO_LIS FROM DUAL;

     INSERT INTO LIS.TRANSACOES_LIS VALUES (V_ID_TRANSACAO_LIS, V_ID_ATENDIMENTO, V_SPECIMEN_ID,
                                            V_LOTE_TRANSACAO, V_ID_AUTOMACAO, V_USUARIO_TRANSACAO, V_DATA_TRANSACAO, 
                                            V_ESTACAO_TRANSACAO, V_TIPO_TRANSACAO, V_TRANSACAO, V_STATUS_TRANSACAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE LIS.TRANSACOES_LIS SET STATUS_TRANSACAO = V_STATUS_TRANSACAO
                               WHERE ID_TRANSACAO_LIS = V_ID_TRANSACAO_LIS;

  ELSIF V_FUNCAO = 3 THEN
     DELETE LIS.TRANSACOES_LIS WHERE ID_TRANSACAO_LIS = V_ID_TRANSACAO_LIS;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_TRANSACOES_LIS;
/
