CREATE OR REPLACE FUNCTION PRC_PROCEDIMENTOS_NOTAS(V_MNEMONICO     IN PROCEDIMENTOS_NOTAS.MNEMONICO%TYPE,
                                                    V_CODIGO        IN PROCEDIMENTOS_NOTAS.CODIGO%TYPE,
                                                    V_FUNCAO        IN INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PROCEDIMENTOS_NOTAS VALUES (V_MNEMONICO, V_CODIGO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE PROCEDIMENTOS_NOTAS WHERE MNEMONICO = V_MNEMONICO AND CODIGO = V_CODIGO;

  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_PROCEDIMENTOS_NOTAS;
/

