CREATE OR REPLACE FUNCTION PRC_ENTIDADES_SERVICOS_B2B(V_ENTIDADE       IN ENTIDADES_SERVICOS_B2B.ENTIDADE%TYPE,
                                                       V_ID_SERVICO_B2B IN ENTIDADES_SERVICOS_B2B.ID_SERVICO_B2B%TYPE,
                                                       V_FUNCAO         IN      INT) RETURNS VOID AS $$
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO ENTIDADES_SERVICOS_B2B VALUES (V_ENTIDADE, V_ID_SERVICO_B2B);

  ELSIF V_FUNCAO = 3 THEN
     DELETE ENTIDADES_SERVICOS_B2B WHERE ENTIDADE = V_ENTIDADE AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;
  END IF;

  /* COMMIT WORK; */

END;
$$ LANGUAGE plpgsql; PRC_ENTIDADES_SERVICOS_B2B;
/
