CREATE USER ETL 
  IDENTIFIED BY "etl"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE "DEFAULT"
  ACCOUNT UNLOCK;


/* Granted roles */
GRANT "CONNECT" TO ETL;

ALTER USER ETL DEFAULT ROLE ALL;

CREATE OR REPLACE FORCE VIEW ETL_AGIL AS
SELECT A.POSTO POSTO_CADASTRO,
       P.NOME NOME_POSTO_CADASTRO,
       A.ATENDIMENTO,
	   CL.REGISTRO CLIENTE,
	   CL.NOME NOME_CLIENTE,
  	   CL.SEXO,
	   CL.DATA_NAS DATA_NASCIMENTO,
       CL.CPF,	   
	   CL.TELEFONE,
	   A.CONVENIO,
	   CO.NOME NOME_CONVENIO,
	   A.MATRICULA,
  	   A.DATA_ATD DATA_ATENDIMENTO,
  	   A.DATA_FAT DATA_FATURAMENTO,
   	   A.DATA_ENT DATA_ENTREGA,
	   A.USUARIO USUARIO_ATENDIMENTO,
	   A.MED_SOL CRM_SOLICITANTE,
	   MS.NOME NOME_SOLICITANTE,
	   A.POSTO_ENTREGA,
	   PE.NOME NOME_POSTO_ENTREGA,
  	   A.SITUACAO SITUACAO_ATENDIMENTO,
	   PL.PLANO,
	   A.ID_FATURA,
	   A.GUIA_PRINCIPAL,
	   A.CARATER_ATENDIMENTO,
	   E.CORREL,
	   E.MNEMONICO,
	   E.DATA_REA1 DATA_REALIZACAO,
	   E.USUARIO_COLE USUARIO_COLETA,
  	   PR.NOME NOME_PROCEDIMENTO,
  	   PR.SETOR,
	   S.NOME NOME_SETOR,
	   E.MATERIAL,
	   M.NOME NOME_MATERIAL,
  	   E.POSTO_REA POSTO_REALIZANTE,
   	   PZ.NOME NOME_POSTO_REALIZANTE,
  	   E.MED_REA1 CRM_REALIZANTE,
  	   MR.NOME NOME_REALIZANTE,
  	   E.SITUACAO SITUACAO_EXAME
  FROM ATENDIMENTOS A,
       CLIENTES CL,
	     EXAMES E,
       CONVENIOS CO,
  	   POSTOS P,
  	   POSTOS PE,
  	   POSTOS PZ,
	     PLANOS_CONVENIOS PL,
	     PROCEDIMENTOS PR,
	     SETORES S,
	     MATERIAIS M,
	     MEDICOS MS,
	     MEDICOS MR
 WHERE CL.REGISTRO = A.REGISTRO
   AND E.POSTO = A.POSTO
   AND E.ATENDIMENTO = A.ATENDIMENTO
   AND P.POSTO = A.POSTO
   AND PE.POSTO = A.POSTO_ENTREGA
   AND PZ.POSTO = E.POSTO_REA
   AND CO.CONVENIO = A.CONVENIO
   AND PL.CODIGO_PLANO(+) = A.CODIGO_PLANO
   AND PR.MNEMONICO = E.MNEMONICO
   AND S.SETOR = PR.SETOR
   AND M.MATERIAL = E.MATERIAL
   AND MS.CRM = A.MED_SOL
   AND MR.CRM(+) = E.MED_REA1
ORDER BY POSTO_CADASTRO, ATENDIMENTO, CORREL

	   
GRANT SELECT
 ON ETL_AGIL
TO ETL;	   