CREATE OR REPLACE FUNCTION GET_ATENDIMENTOS_SOLICITANTE(V_REGISTRO         IN NUMBER,
                                                        V_ID_SOLICITANTE   IN NUMBER,
														V_MASK_POSTO       IN VARCHAR2,
														V_MASK_ATENDIMENTO IN VARCHAR2) RETURN VARCHAR2 IS ATENDIMENTOS VARCHAR2(4000);

    CURSOR CUR_ATENDIMENTOS_SOLICITANTE IS
      SELECT DATA_ATD, POSTO, ATENDIMENTO FROM VEX_ATENDIMENTOS WHERE REGISTRO = V_REGISTRO AND ID_SOLICITANTE = V_ID_SOLICITANTE;

BEGIN

ATENDIMENTOS := '';

FOR ATENDIMENTOS_REC in CUR_ATENDIMENTOS_SOLICITANTE
LOOP
    ATENDIMENTOS := ATENDIMENTOS || TO_CHAR(ATENDIMENTOS_REC.DATA_ATD,'DD/MM/YY') || ' |' || TO_CHAR(ATENDIMENTOS_REC.POSTO, V_MASK_POSTO) || TO_CHAR(ATENDIMENTOS_REC.ATENDIMENTO, V_MASK_ATENDIMENTO) || ',  ';

END LOOP;

RETURN ATENDIMENTOS;

END;
/

GRANT EXECUTE
 ON GET_ATENDIMENTOS_SOLICITANTE
TO EXPERIENCE;