CREATE USER EXPERIENCE 
  IDENTIFIED BY "experience"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE "DEFAULT"
  ACCOUNT UNLOCK;


/* Granted roles */
GRANT "CONNECT" TO EXPERIENCE;

ALTER USER EXPERIENCE DEFAULT ROLE ALL;