CREATE OR REPLACE VIEW VEX_RESULTADOS
(
  POSTO,
  ATENDIMENTO,
  CORREL,
  MNEMONICO,
  NUMERO,
  VARIAVEL,
  VARIAVEL_NOME,
  VARIAVEL_UNIDADE,
  VALOR,
  USUARIO_AUTO,
  DATA_AUTO,
  ESTACAO_AUTO
)
AS
SELECT 
	R.POSTO, 
	R.ATENDIMENTO, 
	R.CORREL, 
	E.MNEMONICO, 
	R.NUMERO, 
	R.VARIAVEL, 
	V.NOME VARIAVEL_NOME,
	V.UNIDADE VARIAVEL_UNIDADE
	R.VALOR, 
	R.USUARIO_AUTO, 
	R.DATA_AUTO, 
	R.ESTACAO_AUTO
FROM 
	RESULTADOS R, EXAMES E, VARIAVEL V, VARIAVEIS_TEXTOS VT
WHERE 
	E.POSTO = R.POSTO AND 
	E.ATENDIMENTO = R.ATENDIMENTO AND 
	E.CORREL = R.CORREL AND 
	VT.MNEMONICO = E.MNEMONICO AND 
	VT.NUMERO = R.NUMERO AND 
	VT.VARIAVEL = R.VARIAVEL AND
	V.VARIAVEL = R.VARIAVEL
ORDER BY POSTO, ATENDIMENTO, CORREL, NUMERO, VARIAVEL;

GRANT SELECT
 ON VEX_RESULTADOS
TO EXPERIENCE;
