CREATE OR REPLACE VIEW VEX_CONVENIOS
(
  CONVENIO,
  NOME,
  STATUS
)
AS
SELECT CONVENIO, NOME, STATUS
  FROM CONVENIOS
  WHERE STATUS = 'A'
    AND NOME_FICHA IS NOT NULL
ORDER BY CONVENIO;

GRANT SELECT
 ON VEX_CONVENIOS
TO EXPERIENCE;
