CREATE OR REPLACE FORCE VIEW VEX_ACOMODACOES
(
	ID_ACOMODACAO, 
	NOME_ACOMODACAO, 
	POSTO
) 
AS 
  SELECT 
	A.ID_ACOMODACAO, 
	A.NOME NOME_ACOMODACAO, 
	AP.POSTO
  FROM 
	ACOMODACOES A, 
	ACOMODACOES_POSTOS AP
  WHERE 
	A.ID_ACOMODACAO = AP.ID_ACOMODACAO
ORDER BY NOME