CREATE OR REPLACE VIEW VEX_CLIENTES
(
  REGISTRO,
  NOME,
  SEXO,
  DATA_NAS,
  IDENTIDADE,
  CPF,
  TELEFONE,
  TELEFONE2,
  EMAIL
)
AS
SELECT C.REGISTRO, C.NOME, C.SEXO, C.DATA_NAS, C.IDENTIDADE, C.CPF, C.TELEFONE, C.TELEFONE2, C.E_MAIL
  FROM CLIENTES C;

GRANT SELECT
 ON VEX_CLIENTES
TO EXPERIENCE;
