CREATE OR REPLACE VIEW VEX_MEDICOS
(
  CRM,
  NOME,
  CPF,
  TIPO,
  STATUS,
  UF_CONSELHO,
  TIPO_CR,
  TELEFONE,
  TELEFONE2,
  EMAIL,
  PASS,
  ID_MEDICO,
  DATA_NAS,
  PREFIXO_NOME
)
AS
SELECT "CRM","NOME","CPF","TIPO","STATUS","UF_CONSELHO","TIPO_CR","TELEFONE","TELEFONE2","EMAIL","PASS","ID_MEDICO","DATA_NAS","PREFIXO_NOME"
  FROM MEDICOS;

GRANT SELECT
 ON VEX_MEDICOS
TO EXPERIENCE;


