CREATE OR REPLACE VIEW VEX_POSTOS_MEDICOS
(
  ID_POSTO,
  ID_MEDICO
)
AS
SELECT PE.ID_POSTO, EM.ID_MEDICO
  FROM POSTOS_ENTIDADES PE, ENTIDADES_MEDICOS EM
  WHERE EM.ENTIDADE = PE.ID_ENTIDADE
ORDER BY ID_POSTO, ID_MEDICO;

GRANT SELECT
 ON VEX_POSTOS_MEDICOS
TO EXPERIENCE;


