CREATE OR REPLACE VIEW VEX_VARIAVEIS
(
  VARIAVEL,
  TIPO_VARIAVEL,
  NOME,
  UNIDADE,
  DECIMAIS,
  ORDEM_VISUALIZACAO
)
AS
SELECT VARIAVEL, TIPO_VARIAVEL, NOME, UNIDADE, DECIMAIS, ORDEM_VISUALIZACAO
  FROM VARIAVEIS
ORDER BY VARIAVEL;

GRANT SELECT
 ON VEX_VARIAVEIS
TO EXPERIENCE;
