CREATE OR REPLACE VIEW VEX_ATENDIMENTOS
(
  POSTO,
  ATENDIMENTO,
  REGISTRO,
  DATA_ATD,
  SOLICITANTE,
  DATA_ENTREGA,
  CONVENIO,
  ID_SOLICITANTE,
  NOME_CLIENTE,
  DATA_NAS,
  SEXO,
  NOME_SOLICITANTE,
  NOME_CONVENIO,
  NOME_POSTO,
  ACOMODACAO,
  LEITO,
  SALDO_DEVEDOR,
  SITUACAO_EXAMES_EXPERIENCE

)
AS
SELECT 
	A.POSTO, 
	A.ATENDIMENTO, 
	A.REGISTRO, 
	A.DATA_ATD, 
	A.MED_SOL, 
	A.DATA_ENT, 
	A.CONVENIO, 
	CL.NOME NOME_CLIENTE,
	CL.DATA_NAS,
	CL.SEXO,
    M.ID_MEDICO, 
	M.NOME NOME_SOLICITANTE,  
	C.NOME NOME_CONVENIO, 
	P.NOME NOME_POSTO, 
	AC.NOME ACOMODACAO, 
	CA.LEITO,
       (SELECT SUM(D.VALOR) FROM DEVEDORES D, CONTAS_ATENDIMENTOS CA 
	     WHERE CA.POSTO = A.POSTO AND CA.ATENDIMENTO = A.ATENDIMENTO AND D.CONTA_HOSP = CA.CONTA_HOSP),
	   GET_SITUACAO_EXAMES(A.POSTO, A.ATENDIMENTO)
FROM 
	ATENDIMENTOS A, 
	CLIENTES CL,
	MEDICOS M, 
	CONVENIOS C, 
	POSTOS P, 
	ACOMODACOES AC, 
	COMPLEMENTO_ATENDIMENTOS CA 
 WHERE A.SITUACAO = 'A'
-- cedro   AND TO_CHAR(A.DATA_ATD,'YYYY') >= '2010'
   AND M.CRM = A.MED_SOL
   AND CL.REGISTRO = A.REGISTRO
   AND C.CONVENIO = A.CONVENIO
   AND P.POSTO = A.POSTO
   AND CA.POSTO(+) = A.POSTO AND CA.ATENDIMENTO(+) = A.ATENDIMENTO
   AND AC.ID_ACOMODACAO(+) = CA.ID_ACOMODACAO 
ORDER BY POSTO, ATENDIMENTO;

GRANT SELECT
 ON VEX_ATENDIMENTOS
TO EXPERIENCE;
