-- FKs das tabelas do modulo de Atendimentos..
@%LIS_HOME%\fks\_amostras.sql
@%LIS_HOME%\fks\_atendimentos.sql
@%LIS_HOME%\fks\_caixa.sql
@%LIS_HOME%\fks\_calculos.sql
@%LIS_HOME%\fks\_calculos_aux.sql
@%LIS_HOME%\fks\_complemento_clientes.sql
@%LIS_HOME%\fks\_complemento_atendimentos.sql
@%LIS_HOME%\fks\_contas_atendimentos.sql
@%LIS_HOME%\fks\_cobranca_atendimentos.sql
@%LIS_HOME%\fks\_devedores.sql
@%LIS_HOME%\fks\_exames.sql
@%LIS_HOME%\fks\_exames_b2b.sql
@%LIS_HOME%\fks\_exames_autorizacoes.sql
@%LIS_HOME%\fks\_faturas.sql
@%LIS_HOME%\fks\_pendencias.sql
@%LIS_HOME%\fks\_resultados_atual.sql
@%LIS_HOME%\fks\_resultados_historico.sql
@%LIS_HOME%\fks\_resultados_digitalizados.sql
@%LIS_HOME%\fks\_resultados_streams.sql
@%LIS_HOME%\fks\_textos.sql
@%LIS_HOME%\fks\_transacoes_tes.sql
@%LIS_HOME%\fks\_validacoes.sql
@%LIS_HOME%\fks\_variaveis.sql
@%LIS_HOME%\fks\_variaveis_textos.sql
@%LIS_HOME%\fks\_variaveis_frases.sql
@%LIS_HOME%\fks\_valores_variaveis.sql
@%LIS_HOME%\fks\_vreferencia.sql
@%LIS_HOME%\fks\_rastros_amostras.sql
@%LIS_HOME%\fks\_procedimentos_notas.sql
@%LIS_HOME%\fks\_procedimentos_frases.sql
@%LIS_HOME%\fks\_layouts_postos.sql

