ALTER TABLE BIOQUIMICOS_SETORES ADD CONSTRAINT BIOQUIMICOS_SETORES_USUARIO_FK 
      FOREIGN KEY (USER_CODIGO) REFERENCES USUARIOS(USER_CODIGO)
      ON DELETE CASCADE;                                     
