ALTER TABLE CALCULOS ADD CONSTRAINT CALCULOS_VALIDACOES_FK 
      FOREIGN KEY (MNEMONICO, NUMERO, VALIDACAO, VARIAVEL)
      REFERENCES VALIDACOES(MNEMONICO, NUMERO, CORREL, VARIAVEL) 
      ON DELETE CASCADE;

