CREATE OR REPLACE FUNCTION SEQ_ATENDIMENTO(V_POSTO       IN INT,
                                           V_UPDATE      IN CHAR) RETURN INT IS
 DECLARE
       RESULT INT;
       V_UNIDADE INT;
BEGIN

     SELECT UNIDADE INTO V_UNIDADE FROM UNIDADES_POSTOS WHERE POSTO = V_POSTO;

     IF V_UPDATE='S' THEN
        SELECT SEQ_ATEND_ATUAL INTO RESULT FROM UNIDADES WHERE UNIDADE = V_UNIDADE FOR UPDATE;
        UPDATE UNIDADES SET SEQ_ATEND_ATUAL = SEQ_ATEND_ATUAL + 1  WHERE UNIDADE = V_UNIDADE;
        COMMIT;
     ELSE
         SELECT SEQ_ATEND_ATUAL INTO RESULT FROM UNIDADES WHERE UNIDADE = V_UNIDADE;
     END IF;
    RETURN(RESULT);
END SEQ_ATENDIMENTO;
$$ LANGUAGE plpgsql;
/
