CREATE OR REPLACE FUNCTION SEQ_INTERNO_FIM(V_POSTO       IN INT) RETURN INT IS
 DECLARE
       RESULT INT;
       V_UNIDADE INT;
BEGIN

     SELECT UNIDADE INTO V_UNIDADE FROM UNIDADES_POSTOS WHERE POSTO = V_POSTO;

     SELECT SEQ_INTERNO_FIM INTO RESULT FROM UNIDADES WHERE UNIDADE = V_UNIDADE;
    RETURN(RESULT);
END SEQ_INTERNO_FIM;
$$ LANGUAGE plpgsql;
/
