-- View: LIS.RESULTADOS_WEB

-- DROP VIEW LIS.RESULTADOS_WEB;

CREATE VIEW LIS.RESULTADOS_WEB
(
  REGISTRO,
  NOME,
  SEXO,
  DATA_NAS,
  IDENTIDADE,
  TELEFONE,
  ATENDIMENTO,
  DATA_ATD,
  POSTO,
  MED_SOL,
  LIB_FAT,
  DATA_ENT,
  OBSERVACOES,
  USUARIO,
  CORREL,
  MNEMONICO,
  SITUACAO,
  SITUACAO_INTERFACE,
  PENDENCIA,
  DATA_COLE,
  MED_REA1,
  MED_REA2,
  NOME_PROCED,
  TIPO_ENTREGA,
  NOME_MED,
  NOME_CONV,
  NOME_POSTO
)
AS
SELECT C.REGISTRO, C.NOME, C.SEXO, C.DATA_NAS, C.IDENTIDADE, C.TELEFONE, A.ATENDIMENTO,
       A.DATA_ATD, A.POSTO, A.MED_SOL, A.LIB_FAT, A.DATA_ENT, E.OBSERVACOES, E.USUARIO,
       E.CORREL, E.MNEMONICO, E.SITUACAO, E.SITUACAO_INTERFACE, E.PENDENCIA,
       E.DATA_COLE, E.MED_REA1, E.MED_REA2, P.NOME NOME_PROCED, P.TIPO_ENTREGA,
       M.NOME NOME_MED, CO.NOME NOME_CONV, PO.NOME NOME_POSTO
  FROM CLIENTES C, ATENDIMENTOS A, EXAMES E, PROCEDIMENTOS P, MEDICOS M,
       CONVENIOS CO, POSTOS PO, SETORES S, COMPLEMENTO_ATENDIMENTOS CA
 WHERE C.REGISTRO = A.REGISTRO
   AND A.SITUACAO = 'A'
   AND C.REGISTRO = A.REGISTRO
   AND E.POSTO = A.POSTO AND E.ATENDIMENTO = A.ATENDIMENTO
   AND E.SITUACAO <> 'F'
   AND E.SITUACAO <> 'C'
   AND CA.POSTO(+) = A.POSTO AND CA.ATENDIMENTO(+) = A.ATENDIMENTO
   AND P.MNEMONICO(+) = E.MNEMONICO
   AND S.SETOR(+) = P.SETOR
   AND M.CRM(+) = A.MED_SOL
   AND CO.CONVENIO(+) = A.CONVENIO
   AND PO.POSTO(+) = A.POSTO
ORDER BY ATENDIMENTO, CORREL;

GRANT SELECT
 ON LIS.RESULTADOS_WEB
TO WLIS;
