CREATE OR REPLACE VIEW VW_CORRECAO_GUIAS_ATENDIMENTOS AS
SELECT 1 ID_SERVICO_ADM, A.* FROM CORRECAO_GUIAS_ATENDIMENTOS A
UNION ALL
SELECT 2 ID_SERVICO_ADM, A.* FROM CORRECAO_GUIAS_ATENDIMENTOS@CLB_LNK A

