
-- DROP VIEW VW_EXAMES_COLETADOS;

CREATE VIEW VW_EXAMES_COLETADOS
(
 POSTO,
 ATENDIMENTO,
 CORREL,
 AMOSTRA,
 ID_TEMPO_COLETA,
 CONTROLE,
 PENDENCIA,
 IMPR_MAPA,
 DATA_CAD,
 DATA_COLE,
 USUARIO,
 USUARIO_COLE,
 ETIQUETA,
 SITUACAO_INTERFACE
)
AS
SELECT ETC.POSTO,
       ETC.ATENDIMENTO,
       ETC.CORREL,
       ETC.AMOSTRA,
       ETC.ID_TEMPO_COLETA,
       ETC.CONTROLE,
       ETC.PENDENCIA,
       ETC.IMPR_MAPA,
       ETC.DATA_CAD,
       ETC.DATA_COLE,
       ETC.USUARIO,
       ETC.USUARIO_COLE,
       ETC.ETIQUETA,
       ETC.SITUACAO_INTERFACE
  FROM EXAMES_TEMPOS_COLETA ETC
UNION ALL
SELECT E.POSTO,
       E.ATENDIMENTO,
       E.CORREL,
       GET_AMOSTRA(E.POSTO, E.ATENDIMENTO, E.CORREL) AMOSTRA,
       -1 ID_TEMPO_COLETA,
       E.CONTROLE,
       E.PENDENCIA,
       E.IMPR_MAPA,
       E.DATA_CAD,
       E.DATA_COLE,
       E.USUARIO,
       E.USUARIO_COLE,
       E.ETIQUETA,
       E.SITUACAO_INTERFACE
  FROM EXAMES E
ORDER BY POSTO, ATENDIMENTO, CORREL, AMOSTRA, ID_TEMPO_COLETA;
