ALTER TABLE BANDEIRAS_OPERADORAS ADD CONSTRAINT BANDEIRAS_OPERADORAS_PK
    PRIMARY KEY (ID_BANDEIRA_OPERADORA)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);
