ALTER TABLE CONTROLES_CORRIDAS ADD CONSTRAINT CONTROLES_CORRIDAS_PK
    PRIMARY KEY (ID_CONTROLE_CORRIDA)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);
