ALTER TABLE CONTROLES_PROCEDIMENTOS ADD CONSTRAINT CONTROLES_PROCEDIMENTOS_PK
    PRIMARY KEY (ID_CONTROLE_PROCEDIMENTO)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);