ALTER TABLE FORMAS_PAGAMENTOS_OPERADORAS ADD CONSTRAINT FORMAS_PAG_OPERADORAS_PK
    PRIMARY KEY (ID_FORMA_PAGAMENTO, ID_OPERADORA)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);