ALTER TABLE FORMAS_PAGAMENTOS ADD CONSTRAINT FORMAS_PAGAMENTOS_PK
    PRIMARY KEY (ID_FORMA_PAGAMENTO)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);
