ALTER TABLE MAP_EQUIPAMENTOS_FORMAS_PAG ADD CONSTRAINT MAP_EQUIPAMENTOS_FORMAS_PAG_PK
    PRIMARY KEY (EQUIPAMENTO, ID_FORMA_PAGAMENTO)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);