ALTER TABLE CONTR_PROCEDIMENTOS_INTERFACES ADD CONSTRAINT CONTR_PROCEDI_INTERFACES_PK
    PRIMARY KEY (ID_CONT_PROCEDIMENTO_INTERFACE)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);