ALTER TABLE MAP_CONTROLES_VARIAVEIS_INTERFACES ADD CONSTRAINT MAP_CONTROLES_VARIAVEIS_INTERFACES_PK
    PRIMARY KEY (ID_CONTROLE_VARIAVEL_INTERFACE)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);