ALTER TABLE MAP_EQUIPAMENTOS_BANDEIRAS ADD CONSTRAINT MAP_EQUIPAMENTOS_BANDEIRAS_PK
    PRIMARY KEY (EQUIPAMENTO, ID_BANDEIRA)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);
