ALTER TABLE MAP_EQUIPAMENTOS_OPERADORAS ADD CONSTRAINT MAP_EQUIPAMENTOS_OPERADORAS_PK
    PRIMARY KEY (EQUIPAMENTO, ID_OPERADORA)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);