ALTER TABLE RESPONSAVEIS_FINANCEIROS ADD CONSTRAINT RESPONSAVEIS_FINANCEIROS_PK
    PRIMARY KEY (ID_RESPONSAVEL_FINANCEIRO)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);
