ALTER TABLE TRANSACOES_INTEGRACOES ADD CONSTRAINT TRANSACOES_INTEGRACOES_PK
    PRIMARY KEY (ID_TRANSACAO_INTEGRACAO)
    USING INDEX
    TABLESPACE LIS_INDX PCTFREE 20
    STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0);
