CREATE TABLE CONTR_PROCEDIMENTOS_INTERFACES (
    ID_CONT_PROCEDIMENTO_INTERFACE NUMBER(9) NOT NULL,
    ID_CONTROLE_PROCEDIMENTO NUMBER(9) NOT NULL,
    ID_PROCEDIMENTO_AUTOMACAO NUMBER(9) NOT NULL,
    ID_PROCEDIMENTO_INTEGRACAO NUMBER(9) NOT NULL
)
TABLESPACE LIS_DATA;