CREATE TABLE CONTROLES_CORRIDAS(
    ID_CONTROLE_CORRIDA NUMBER(9) NOT NULL,
    ID_CONTROLE NUMBER(9) NOT NULL,
    ID_EQUIPAMENTO NUMBER(9) NOT NULL,
    RESULTADO VARCHAR2(2000) NOT NULL,
    DATA_HORA DATE NOT NULL,
    VERSAO VARCHAR2(10)
)
TABLESPACE LIS_DATA;