ALTER TABLE EQUIPAMENTOS_VARIAVEIS
    ADD ID_EQUIPAMENTO_VARIAVEL NUMBER(9);

ALTER TABLE EQUIPAMENTOS_VARIAVEIS
    ADD CONSTRAINT EQUIPAMENTOS_VARIAVEIS_UK UNIQUE (ID_EQUIPAMENTO_VARIAVEL);

UPDATE EQUIPAMENTOS_VARIAVEIS SET ID_EQUIPAMENTO_VARIAVEL = SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL;