CREATE TABLE EQUIPAMENTOS_CONTROLES_LOTES(
    ID_CONTROLE_LOTE NUMBER(9) NOT NULL,
    ID_EQUIPAMENTO NUMBER(3) NOT NULL,
    POSTO_REA NUMBER(2) NOT NULL,
    DATA_ATIVACAO DATE,
    DATA_CANCELAMENTO  DATE,
    USUARIO_ATIVACAO VARCHAR2(50),
    USUARIO_CANCELAMENTO  VARCHAR2(50),
    STATUS VARCHAR2(1) NOT NULL,
    ID_MOTIVO_CANCELAMENTO NUMBER(6)
)
TABLESPACE LIS_DATA;