ALTER TABLE EQUIPAMENTOS_TEXTOS
	ADD ID_EQUIPAMENTO_TEXTO NUMBER(9);

ALTER TABLE EQUIPAMENTOS_TEXTOS
     ADD CONSTRAINT EQUIPAMENTOS_TEXTOS_UK UNIQUE (ID_EQUIPAMENTO_TEXTO);

UPDATE EQUIPAMENTOS_TEXTOS SET ID_EQUIPAMENTO_TEXTO = SQ_EQUIPAMENTOS_TEXTOS.NEXTVAL;