CREATE TABLE MAP_CONTROLES_VARIAVEIS_INTERFACES(
    ID_CONTROLE_VARIAVEL_INTERFACE NUMBER(9) NOT NULL,
    ID_CONTROLE_PROCEDIMENTO NUMBER(9) NOT NULL,
    ID_MAP_VARIAVEL_INTEGRACAO NUMBER(9) NOT NULL,
    ID_MAP_VARIAVEL_AUTOMACAO NUMBER(9) NOT NULL
)
TABLESPACE LIS_DATA;