CREATE TABLE RESPONSAVEIS_FINANCEIROS (
    ID_RESPONSAVEL_FINANCEIRO NUMBER(4) NOT NULL,
    RESPONSAVEL_FINANCEIRO VARCHAR2(50) NOT NULL,
    CPF/CNPJ VARCHAR2(15),
    EMAIL VARCHAR2(25),
    TELEFONE VARCHAR2(23),
    TIPO VARCHAR2(2)
)
TABLESPACE LIS_DATA;