CREATE TABLE RESPONSAVEIS_FINANCEIROS (
    ID_RESPONSAVEL_FINANCEIRO NUMBER(4) NOT NULL,
    RESPONSAVEL_FINANCEIRO VARCHAR2(50) NOT NULL,
    CPF_CNPJ VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(25),
    TELEFONE VARCHAR2(23),
    TIPO VARCHAR2(2) NOT NULL,
    USUARIO VARCHAR2(10) NOT NULL,
    DATA_CAD DATE NOT NULL
)
TABLESPACE LIS_DATA;