CREATE TABLE TRANSACOES_INTEGRACOES(
    ID_TRANSACAO_INTEGRACAO NUMBER(9) NOT NULL,
    ID_INTEGRACAO NUMBER(2) NOT NULL,
    DATA_TRANSACAO DATE,
    STATUS_TRANSACAO VARCHAR2(1) NOT NULL,
    TRANSACAO CLOB NOT NULL,
    ESTACAO_TRANSACAO VARCHAR2(20) ,
    TIPO_INTEGRACAO VARCHAR2(25)
);