CREATE OR REPLACE PROCEDURE PRC_CATEGORIAS(V_CATEGORIA IN OUT CATEGORIAS.CATEGORIA%TYPE,
                                           V_NOME      IN     CATEGORIAS.NOME%TYPE,
                                           V_FUNCAO    IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_CATEGORIA.NEXTVAL INTO V_CATEGORIA FROM DUAL;
     INSERT INTO CATEGORIAS VALUES (V_CATEGORIA, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CATEGORIAS SET NOME = V_NOME WHERE CATEGORIA = V_CATEGORIA;
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE CATEGORIAS WHERE CATEGORIA = V_CATEGORIA;
  END IF;

  COMMIT WORK;

END PRC_CATEGORIAS;
/
