CREATE OR REPLACE PROCEDURE PRC_TABELA_PRECOS(V_FORNECEDOR IN TABELAS_FORNECEDORES.FORNECEDOR%TYPE,
                                              V_PRODUTO    IN TABELAS_FORNECEDORES.PRODUTO%TYPE,
                                              V_CODIGO     IN TABELAS_FORNECEDORES.CODIGO%TYPE,
                                              V_VALOR      IN TABELAS_FORNECEDORES.VALOR%TYPE,
                                              V_FUNCAO     IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 2 THEN
     UPDATE TABELAS_FORNECEDORES SET CODIGO = V_CODIGO, VALOR = V_VALOR WHERE FORNECEDOR = V_FORNECEDOR AND
     PRODUTO = V_PRODUTO;
  END IF;

  COMMIT WORK;

END PRC_TABELA_PRECOS;
/
