CREATE OR REPLACE PROCEDURE PRC_CALCULOS(V_MNEMONICO    IN CALCULOS.MNEMONICO%TYPE,
                                         V_NUMERO       IN CALCULOS.NUMERO%TYPE,
                                         V_VALIDACAO    IN CALCULOS.VALIDACAO%TYPE,
                                         V_VARIAVEL     IN CALCULOS.VARIAVEL%TYPE,
                                         V_CORREL       IN CALCULOS.CORREL%TYPE,
                                         V_CALCULO      IN CALCULOS.CALCULO%TYPE,
                                         V_FUNCAO       IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CALCULOS VALUES (V_MNEMONICO, V_NUMERO, V_VALIDACAO, V_VARIAVEL, V_CORREL,
                                        V_CALCULO); 

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CALCULOS SET CALCULO = V_CALCULO
                        WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND VALIDACAO = V_VALIDACAO AND VARIAVEL = V_VARIAVEL AND CORREL = V_CORREL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CALCULOS WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND VALIDACAO = V_VALIDACAO AND VARIAVEL = V_VARIAVEL AND CORREL = V_CORREL;

  END IF;

  COMMIT WORK;

END PRC_CALCULOS;
/
