CREATE OR REPLACE PROCEDURE PRC_VARIAVEIS_METODOS(V_ID_METODO     IN VARIAVEIS_METODOS.ID_METODO%TYPE,
                                                  V_VARIAVEL      IN VARIAVEIS_METODOS.VARIAVEL%TYPE,
                                                  V_FUNCAO        IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO VARIAVEIS_METODOS VALUES (V_ID_METODO, V_VARIAVEL);

  ELSIF V_FUNCAO = 3 THEN
     DELETE VARIAVEIS_METODOS WHERE ID_METODO = V_ID_METODO AND VARIAVEL = V_VARIAVEL;

  END IF;

  COMMIT WORK;

END PRC_VARIAVEIS_METODOS;
/

