CREATE OR REPLACE PROCEDURE PRC_POSTOS_EQUIPAMENTOS(V_POSTO             IN POSTOS_EQUIPAMENTOS.POSTO%TYPE,
                                                    V_EQUIPAMENTO      IN POSTOS_EQUIPAMENTOS.EQUIPAMENTO%TYPE,
                                                    V_LOGIN            IN POSTOS_EQUIPAMENTOS.LOGIN%TYPE,
                                                    V_PASS             IN POSTOS_EQUIPAMENTOS.PASS%TYPE,
                                                    V_LOTE             IN OUT POSTOS_EQUIPAMENTOS.LOTE%TYPE,
												    V_IMPRIME_ETIQUETA IN POSTOS_EQUIPAMENTOS.IMPRIME_ETIQUETA%TYPE,
                                                    V_FUNCAO           IN NUMBER) IS
 BEGIN
   IF V_FUNCAO = 1 THEN
      INSERT INTO POSTOS_EQUIPAMENTOS VALUES (V_POSTO, V_EQUIPAMENTO, V_LOGIN, V_PASS, V_LOTE, V_IMPRIME_ETIQUETA);
   ELSIF V_FUNCAO = 2 THEN
 	 UPDATE POSTOS_EQUIPAMENTOS SET LOGIN = V_LOGIN, PASS = V_PASS, LOTE = V_LOTE, IMPRIME_ETIQUETA = V_IMPRIME_ETIQUETA
           WHERE POSTO = V_POSTO AND EQUIPAMENTO = V_EQUIPAMENTO;
   ELSIF V_FUNCAO = 3 THEN
      DELETE POSTOS_EQUIPAMENTOS WHERE POSTO = V_POSTO AND EQUIPAMENTO = V_EQUIPAMENTO;
   ELSIF V_FUNCAO = 4 THEN
      UPDATE POSTOS_EQUIPAMENTOS SET LOTE = LOTE + 1 
       WHERE POSTO = V_POSTO AND EQUIPAMENTO = V_EQUIPAMENTO;
   END IF;
   COMMIT WORK;
 END PRC_POSTOS_EQUIPAMENTOS;
-- fim bloco
 