CREATE OR REPLACE PROCEDURE PRC_LAYOUT_EQUIPAMENTOS(V_MODELO_EQUIPAMENTO    IN  LAYOUT_EQUIPAMENTOS.MODELO_EQUIPAMENTO%TYPE,
                                                    V_CARACTER_DELIMITADOR  IN  LAYOUT_EQUIPAMENTOS.CARACTER_DELIMITADOR%TYPE,
                                                    V_TIPO_REGISTRO         IN  LAYOUT_EQUIPAMENTOS.TIPO_REGISTRO%TYPE,
                                                    V_SEQUENCIA_REGISTRO    IN  LAYOUT_EQUIPAMENTOS.SEQUENCIA_REGISTRO%TYPE,
                                                    V_CONDICAO_CORTE        IN  LAYOUT_EQUIPAMENTOS.CONDICAO_CORTE%TYPE,
                                                    V_LINHA_REGISTRO        IN  LAYOUT_EQUIPAMENTOS.LINHA_REGISTRO%TYPE,
                                                    V_FUNCAO                IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO LAYOUT_EQUIPAMENTOS VALUES (V_MODELO_EQUIPAMENTO, V_CARACTER_DELIMITADOR, V_TIPO_REGISTRO,
                                                   V_SEQUENCIA_REGISTRO, V_CONDICAO_CORTE, V_LINHA_REGISTRO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE LAYOUT_EQUIPAMENTOS SET CARACTER_DELIMITADOR = V_CARACTER_DELIMITADOR, TIPO_REGISTRO = V_TIPO_REGISTRO,
                                          SEQUENCIA_REGISTRO = V_SEQUENCIA_REGISTRO, CONDICAO_CORTE = V_CONDICAO_CORTE,
                                          LINHA_REGISTRO = V_LINHA_REGISTRO
     WHERE MODELO_EQUIPAMENTO = V_MODELO_EQUIPAMENTO;
  ELSIF V_FUNCAO = 3 THEN
     DELETE LAYOUT_EQUIPAMENTOS WHERE MODELO_EQUIPAMENTO = V_MODELO_EQUIPAMENTO;

  END IF;

  COMMIT WORK;

END PRC_LAYOUT_EQUIPAMENTOS;
/
