CREATE OR REPLACE PROCEDURE PRC_EXCECOES_GRUPOS_ETIQUETAS(V_POSTO          IN  EXCECOES_GRUPOS_ETIQUETAS.POSTO%TYPE,
                                                          V_MNEMONICO      IN  EXCECOES_GRUPOS_ETIQUETAS.MNEMONICO%TYPE,                                                     
                                                          V_GRUPO_ETIQUETA IN  EXCECOES_GRUPOS_ETIQUETAS.GRUPO_ETIQUETA%TYPE,
                                                          V_FUNCAO         IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO EXCECOES_GRUPOS_ETIQUETAS VALUES (V_POSTO, V_MNEMONICO, V_GRUPO_ETIQUETA);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE EXCECOES_GRUPOS_ETIQUETAS SET GRUPO_ETIQUETA = V_GRUPO_ETIQUETA
                                       WHERE POSTO = V_POSTO AND MNEMONICO = V_MNEMONICO;
                    
  ELSIF V_FUNCAO = 3 THEN
     DELETE EXCECOES_GRUPOS_ETIQUETAS WHERE POSTO = V_POSTO AND MNEMONICO = V_MNEMONICO;

  END IF;

  COMMIT WORK;

END PRC_EXCECOES_GRUPOS_ETIQUETAS;
/
