CREATE OR REPLACE PROCEDURE PRC_GERENTE_ESTOQUE(V_USER_CODIGO    IN  GERENTE_ESTOQUE.USER_CODIGO%TYPE,
                                                V_DEPARTAMENTO   IN  GERENTE_ESTOQUE.DEPARTAMENTO%TYPE,
                                                V_FUNCAO         IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO GERENTE_ESTOQUE VALUES (V_USER_CODIGO, V_DEPARTAMENTO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE GERENTE_ESTOQUE WHERE USER_CODIGO = V_USER_CODIGO AND DEPARTAMENTO = V_DEPARTAMENTO;
  END IF;

  COMMIT WORK;

END PRC_GERENTE_ESTOQUE;
/
