CREATE OR REPLACE PROCEDURE PRC_MAP_B2B_VARIAVEIS(V_ID_SERVICO_B2B  IN   MAP_B2B_VARIAVEIS.ID_SERVICO_B2B%TYPE,
                                                  V_VARIAVEL        IN   MAP_B2B_VARIAVEIS.VARIAVEL%TYPE,
                                                  V_MAP_VARIAVEL    IN   MAP_B2B_VARIAVEIS.MAP_VARIAVEL%TYPE,
                                                  V_FUNCAO          IN   NUMBER) IS                         
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO MAP_B2B_VARIAVEIS VALUES (V_ID_SERVICO_B2B, V_VARIAVEL, V_MAP_VARIAVEL);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE MAP_B2B_VARIAVEIS SET MAP_VARIAVEL = V_MAP_VARIAVEL WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND VARIAVEL = V_VARIAVEL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE MAP_B2B_VARIAVEIS WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND VARIAVEL = V_VARIAVEL;
     
  END IF;             

  COMMIT WORK;

END PRC_MAP_B2B_VARIAVEIS;
/
