CREATE OR REPLACE PROCEDURE PRC_BIOQUIMICOS_SETORES(V_USER_CODIGO    IN OUT BIOQUIMICOS_SETORES.USER_CODIGO%TYPE,
                                                    V_SETOR          IN     BIOQUIMICOS_SETORES.SETOR%TYPE,
                                                    V_RESPONSAVEL    IN     BIOQUIMICOS_SETORES.RESPONSAVEL%TYPE,
                                                    V_FUNCAO         IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO BIOQUIMICOS_SETORES VALUES (V_USER_CODIGO, V_SETOR, V_RESPONSAVEL);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE BIOQUIMICOS_SETORES SET RESPONSAVEL = V_RESPONSAVEL WHERE USER_CODIGO = V_USER_CODIGO AND SETOR = V_SETOR;

  ELSIF V_FUNCAO = 3 THEN
     DELETE BIOQUIMICOS_SETORES WHERE USER_CODIGO = V_USER_CODIGO AND SETOR = V_SETOR ;

  ELSIF V_FUNCAO = 4 THEN
     DELETE BIOQUIMICOS_SETORES WHERE USER_CODIGO = V_USER_CODIGO;
     
  END IF;           

  COMMIT WORK;

END PRC_BIOQUIMICOS_SETORES;
/
