CREATE OR REPLACE PROCEDURE PRC_PRODUTOS_COMPRA(V_NUMERO 	      IN PRODUTOS_COMPRA.NUMERO%TYPE,
                                        		V_PRODUTO_ID      IN PRODUTOS_COMPRA.PRODUTO_ID%TYPE,
                                        		V_QTD             IN PRODUTOS_COMPRA.QTD%TYPE,
                                        		V_VALOR           IN PRODUTOS_COMPRA.VALOR%TYPE,
                                        		V_TIPO_DESCONTO   IN PRODUTOS_COMPRA.TIPO_DESCONTO%TYPE,
                                        		V_DESCONTO        IN PRODUTOS_COMPRA.DESCONTO%TYPE,
                                        		V_PRAZO_ENTREGA   IN PRODUTOS_COMPRA.PRAZO_ENTREGA%TYPE,
                                        		V_QTD_ENTREGUE    IN PRODUTOS_COMPRA.QTD_ENTREGUE%TYPE,
                                        		V_IPI             IN PRODUTOS_COMPRA.IPI%TYPE,
                                        		V_FUNCAO          IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PRODUTOS_COMPRA VALUES (V_NUMERO       , V_PRODUTO_ID   , V_QTD, 
                                               V_VALOR        , V_TIPO_DESCONTO, V_DESCONTO, 
                                               V_PRAZO_ENTREGA, V_QTD_ENTREGUE , V_IPI);

  ELSIF V_FUNCAO = 3 THEN
     DELETE PRODUTOS_COMPRA WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 4 THEN
     UPDATE PRODUTOS_COMPRA SET QTD = V_QTD WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 5 THEN
     UPDATE PRODUTOS_COMPRA SET VALOR = V_VALOR WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 6 THEN
     UPDATE PRODUTOS_COMPRA SET TIPO_DESCONTO = V_TIPO_DESCONTO WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 7 THEN
     UPDATE PRODUTOS_COMPRA SET DESCONTO = V_DESCONTO WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 8 THEN
     UPDATE PRODUTOS_COMPRA SET PRAZO_ENTREGA = V_PRAZO_ENTREGA WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 9 THEN
     UPDATE PRODUTOS_COMPRA SET QTD_ENTREGUE  = V_QTD_ENTREGUE WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  ELSIF V_FUNCAO = 10 THEN
     UPDATE PRODUTOS_COMPRA SET IPI = V_IPI WHERE NUMERO = V_NUMERO AND PRODUTO_ID = V_PRODUTO_ID;

  END IF;

  COMMIT WORK;

END PRC_PRODUTOS_COMPRA;
/