CREATE OR REPLACE PROCEDURE PRC_PROCEDIMENTOS_FRASES(V_MNEMONICO      IN PROCEDIMENTOS_FRASES.MNEMONICO%TYPE,
                                                    V_CODIGO          IN PROCEDIMENTOS_FRASES.CODIGO%TYPE,
                                                    V_MNEMONICO_FRASE IN PROCEDIMENTOS_FRASES.MNEMONICO_FRASE%TYPE,
                                                    V_FUNCAO          IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PROCEDIMENTOS_FRASES VALUES (V_MNEMONICO, V_CODIGO, V_MNEMONICO_FRASE);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE PROCEDIMENTOS_FRASES SET MNEMONICO_FRASE = V_MNEMONICO_FRASE;

  ELSIF V_FUNCAO = 3 THEN
     DELETE PROCEDIMENTOS_FRASES WHERE MNEMONICO = V_MNEMONICO AND CODIGO = V_CODIGO;

  END IF;

  COMMIT WORK;

END PRC_PROCEDIMENTOS_FRASES;
/

