CREATE OR REPLACE PROCEDURE PRC_ENTIDADES_MEDICOS(V_ENTIDADE    IN     ENTIDADES_MEDICOS.ENTIDADE%TYPE,
                                                  V_CRM         IN     ENTIDADES_MEDICOS.CRM%TYPE,
                                                  V_ID_MEDICO   IN     ENTIDADES_MEDICOS.ID_MEDICO%TYPE,
                                                  V_FUNCAO      IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO ENTIDADES_MEDICOS VALUES (V_ENTIDADE, V_CRM, V_ID_MEDICO);
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE ENTIDADES_MEDICOS WHERE ENTIDADE = V_ENTIDADE AND ID_MEDICO = V_ID_MEDICO;
  END IF;

  COMMIT WORK;

END PRC_ENTIDADES_MEDICOS;
/
