CREATE OR REPLACE PROCEDURE PRC_PORTES_MEDICOS(V_ID_TABELA_PORTE_MEDICO IN     PORTES_MEDICOS.ID_TABELA_PORTE_MEDICO%TYPE,
                                               V_ID_PORTE_MEDICO        IN     PORTES_MEDICOS.ID_PORTE_MEDICO%TYPE,
                                               V_VALOR_PORTE            IN     PORTES_MEDICOS.VALOR_PORTE%TYPE,
                                               V_FUNCAO                 IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PORTES_MEDICOS VALUES (V_ID_TABELA_PORTE_MEDICO, V_ID_PORTE_MEDICO, V_VALOR_PORTE);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE PORTES_MEDICOS SET VALOR_PORTE = V_VALOR_PORTE
                               WHERE ID_TABELA_PORTE_MEDICO = V_ID_TABELA_PORTE_MEDICO
                                 AND ID_PORTE_MEDICO = V_ID_PORTE_MEDICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE PORTES_MEDICOS WHERE ID_TABELA_PORTE_MEDICO = V_ID_TABELA_PORTE_MEDICO
                                 AND ID_PORTE_MEDICO = V_ID_PORTE_MEDICO;

  ELSIF V_FUNCAO = 4 THEN
     DELETE PORTES_MEDICOS WHERE ID_TABELA_PORTE_MEDICO = V_ID_TABELA_PORTE_MEDICO;
  END IF;

  COMMIT WORK;

END PRC_PORTES_MEDICOS;  
