CREATE OR REPLACE PROCEDURE PRC_EQUIPAMENTOS_TEXTOS(V_EQUIPAMENTO           IN EQUIPAMENTOS_TEXTOS.EQUIPAMENTO%TYPE,
													V_MNEMONICO             IN EQUIPAMENTOS_TEXTOS.MNEMONICO%TYPE,
													V_NUMERO                IN EQUIPAMENTOS_TEXTOS.NUMERO%TYPE,
													V_POSTO_REA             IN EQUIPAMENTOS_TEXTOS.POSTO_REA%TYPE,
													V_MAP_EQUIPAMENTO       IN EQUIPAMENTOS_TEXTOS.MAP_EQUIPAMENTO%TYPE,
													V_STATUS                IN EQUIPAMENTOS_TEXTOS.STATUS%TYPE,
													V_AUTO_LIBERA           IN EQUIPAMENTOS_TEXTOS.AUTO_LIBERA%TYPE,
													V_FUNCAO                IN NUMBER) IS
BEGIN
	 IF V_FUNCAO = 1 THEN
	    INSERT INTO EQUIPAMENTOS_TEXTOS VALUES (V_EQUIPAMENTO, V_MNEMONICO, V_NUMERO, V_POSTO_REA, V_MAP_EQUIPAMENTO, V_STATUS, V_AUTO_LIBERA);

	 ELSIF V_FUNCAO = 2 THEN
		UPDATE EQUIPAMENTOS_TEXTOS SET MAP_EQUIPAMENTO = V_MAP_EQUIPAMENTO, STATUS = V_STATUS, AUTO_LIBERA = V_AUTO_LIBERA
		 WHERE EQUIPAMENTO = V_EQUIPAMENTO AND MNEMONICO = V_MNEMONICO 
		   AND POSTO_REA = V_POSTO_REA AND NUMERO = V_NUMERO;
		 
	 ELSIF V_FUNCAO = 3 THEN
		DELETE EQUIPAMENTOS_TEXTOS WHERE EQUIPAMENTO = V_EQUIPAMENTO AND MNEMONICO = V_MNEMONICO 
									  AND POSTO_REA = V_POSTO_REA AND NUMERO = V_NUMERO;
																								   
	 END IF;

	 COMMIT WORK;

END PRC_EQUIPAMENTOS_TEXTOS;
/
