CREATE OR REPLACE PROCEDURE PRC_MOTIVOS(V_ID_MOTIVO        IN OUT MOTIVOS.ID_MOTIVO%TYPE,
                                        V_MOTIVO           IN     MOTIVOS.MOTIVO%TYPE,
                                        V_TIPO_MOTIVO      IN     MOTIVOS.TIPO_MOTIVO%TYPE,
                                        V_MNEMONICO_MOTIVO IN     MOTIVOS.MNEMONICO_MOTIVO%TYPE,
                                        V_MOTIVO_FORMAT    IN     MOTIVOS.MOTIVO_FORMAT%TYPE,
                                        V_FUNCAO          IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT TO_CHAR(SQ_MOTIVO.NEXTVAL) INTO V_ID_MOTIVO FROM DUAL;

     INSERT INTO MOTIVOS VALUES (V_ID_MOTIVO, V_MOTIVO, V_TIPO_MOTIVO, V_MNEMONICO_MOTIVO, V_MOTIVO_FORMAT);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE MOTIVOS SET MOTIVO = V_MOTIVO, TIPO_MOTIVO = V_TIPO_MOTIVO, MNEMONICO_MOTIVO = V_MNEMONICO_MOTIVO, MOTIVO_FORMAT = V_MOTIVO_FORMAT
                       WHERE ID_MOTIVO = V_ID_MOTIVO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE MOTIVOS WHERE ID_MOTIVO = V_ID_MOTIVO;
  END IF;

  COMMIT WORK;

END PRC_MOTIVOS;
/
