CREATE OR REPLACE PROCEDURE PRC_EVOLUCAO_RESULTADOS(V_POSTO              IN EVOLUCAO_RESULTADOS.POSTO%TYPE, 
                                             	    V_ATENDIMENTO        IN EVOLUCAO_RESULTADOS.ATENDIMENTO%TYPE, 
                                           	        V_CORREL             IN EVOLUCAO_RESULTADOS.CORREL%TYPE, 
                                           	        V_DATA_EVOLUCAO      IN EVOLUCAO_RESULTADOS.DATA_EVOLUCAO%TYPE, 
                                           	        V_USUARIO_EVOLUCAO   IN EVOLUCAO_RESULTADOS.USUARIO_EVOLUCAO%TYPE, 
                                           	        V_EVOLUCAO_RESULTADO IN EVOLUCAO_RESULTADOS.EVOLUCAO_RESULTADO%TYPE, 
                                                    V_FUNCAO             IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO EVOLUCAO_RESULTADOS VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL, V_DATA_EVOLUCAO, V_USUARIO_EVOLUCAO, V_EVOLUCAO_RESULTADO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE EVOLUCAO_RESULTADOS SET EVOLUCAO_RESULTADO = V_EVOLUCAO_RESULTADO
                        WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL AND DATA_EVOLUCAO = V_DATA_EVOLUCAO;
  ELSIF V_FUNCAO = 3 THEN
     DELETE EVOLUCAO_RESULTADOS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL AND DATA_EVOLUCAO = V_DATA_EVOLUCAO;

  END IF;

  COMMIT WORK;

END PRC_EVOLUCAO_RESULTADOS;
/
