CREATE OR REPLACE PROCEDURE PRC_COMPRAS_APAGAR(V_NUMERO_COMPRA    IN     COMPRAS_APAGAR.NUMERO_COMPRA%TYPE,
                                               V_PARCELA          IN     COMPRAS_APAGAR.PARCELA%TYPE,
                                               V_NFISCAL          IN     COMPRAS_APAGAR.NFISCAL%TYPE,
                                               V_DATA_VENC        IN     COMPRAS_APAGAR.DATA_VENC%TYPE,
                                               V_VALOR            IN     COMPRAS_APAGAR.VALOR%TYPE,
                                               V_QTD_PARCELAS     IN     COMPRAS_APAGAR.PARCELA%TYPE,
                                               V_VALOR_FATURAR    IN     COMPRAS_APAGAR.VALOR%TYPE,
                                               V_INTERVALO        IN  NUMBER,
                                               V_FUNCAO           IN  NUMBER) IS

V_PARC COMPRAS_APAGAR.PARCELA%TYPE;
V_FAT  COMPRAS_APAGAR.VALOR%TYPE;
V_CONT NUMBER;

BEGIN
  IF V_FUNCAO = 1 THEN
     V_CONT := 0;
     LOOP
        SELECT NVL(MAX(PARCELA), 0) INTO V_PARC FROM COMPRAS_APAGAR WHERE NUMERO_COMPRA = V_NUMERO_COMPRA;

        EXIT WHEN V_CONT = V_QTD_PARCELAS;
        IF V_CONT = 0 THEN
           INSERT INTO COMPRAS_APAGAR VALUES (V_NUMERO_COMPRA, V_PARC + 1, V_NFISCAL, V_DATA_VENC, V_VALOR);
	     V_FAT := V_VALOR_FATURAR - V_VALOR;
        ELSE
           INSERT INTO COMPRAS_APAGAR VALUES (V_NUMERO_COMPRA, V_PARC + 1, V_NFISCAL, V_DATA_VENC + (V_INTERVALO * V_CONT), V_FAT / (V_QTD_PARCELAS - 1));
        END IF;
        V_CONT := V_CONT + 1;
     END LOOP;

  ELSIF V_FUNCAO = 3 THEN
     DELETE COMPRAS_APAGAR WHERE NUMERO_COMPRA = V_NUMERO_COMPRA AND PARCELA = V_PARCELA;

  ELSIF V_FUNCAO = 4 THEN
     UPDATE COMPRAS_APAGAR SET DATA_VENC = V_DATA_VENC WHERE NUMERO_COMPRA = V_NUMERO_COMPRA AND PARCELA = V_PARCELA;

  ELSIF V_FUNCAO = 5 THEN
     UPDATE COMPRAS_APAGAR SET VALOR = V_VALOR WHERE NUMERO_COMPRA = V_NUMERO_COMPRA AND PARCELA = V_PARCELA;

  END IF;

  COMMIT WORK;

END PRC_COMPRAS_APAGAR;
/
