CREATE OR REPLACE PROCEDURE PRC_FATORES(V_POSTO             IN FATORES.POSTO%TYPE,
                                        V_CONVENIO          IN FATORES.CONVENIO%TYPE,
                                        V_MNEMONICO         IN FATORES.MNEMONICO%TYPE,
                                        V_FATOR             IN FATORES.FATOR%TYPE,
                                        V_FUNCAO            IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO FATORES (SELECT V_POSTO, V_CONVENIO, MNEMONICO, V_FATOR FROM PROCEDIMENTOS);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE FATORES SET FATOR = V_FATOR
                        WHERE POSTO = V_POSTO AND CONVENIO = V_CONVENIO AND MNEMONICO = V_MNEMONICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE FATORES WHERE POSTO = V_POSTO AND CONVENIO = V_CONVENIO;

  END IF;

  COMMIT WORK;

END PRC_FATORES;
/
