CREATE OR REPLACE PROCEDURE PRC_EQUIP_VARIAVEIS_FRASES(V_EQUIPAMENTO           IN EQUIPAMENTOS_VARIAVEIS_FRASES.EQUIPAMENTO%TYPE,
                                                       V_VARIAVEL              IN EQUIPAMENTOS_VARIAVEIS_FRASES.VARIAVEL%TYPE,
                                                       V_CODIGO                IN EQUIPAMENTOS_VARIAVEIS_FRASES.CODIGO%TYPE,
                                                       V_MNEMONICO             IN EQUIPAMENTOS_VARIAVEIS_FRASES.MNEMONICO%TYPE,
                                                       V_FRASE_EQUIPAMENTO     IN EQUIPAMENTOS_VARIAVEIS_FRASES.FRASE_EQUIPAMENTO%TYPE,
													   V_TIPO_COMPARACAO       IN EQUIPAMENTOS_VARIAVEIS_FRASES.TIPO_COMPARACAO%TYPE,
                                                       V_FUNCAO                IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO EQUIPAMENTOS_VARIAVEIS_FRASES VALUES (V_EQUIPAMENTO, V_VARIAVEL, V_CODIGO, V_MNEMONICO, V_FRASE_EQUIPAMENTO, V_TIPO_COMPARACAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE EQUIPAMENTOS_VARIAVEIS_FRASES SET FRASE_EQUIPAMENTO = V_FRASE_EQUIPAMENTO, TIPO_COMPARACAO = V_TIPO_COMPARACAO
            WHERE EQUIPAMENTO = V_EQUIPAMENTO AND VARIAVEL = V_VARIAVEL AND CODIGO = V_CODIGO AND MNEMONICO = V_MNEMONICO;
     
  ELSIF V_FUNCAO = 3 THEN
     DELETE EQUIPAMENTOS_VARIAVEIS_FRASES 
            WHERE EQUIPAMENTO = V_EQUIPAMENTO AND VARIAVEL = V_VARIAVEL AND CODIGO = V_CODIGO AND MNEMONICO = V_MNEMONICO;
                                                                                               
  END IF;

  COMMIT WORK;

END PRC_EQUIP_VARIAVEIS_FRASES;
/
