CREATE OR REPLACE PROCEDURE PRC_TEXTOS(V_MNEMONICO     IN OUT TEXTOS.MNEMONICO%TYPE,
                                       V_NUMERO        IN     TEXTOS.NUMERO%TYPE,
                                       V_DESCRICAO     IN     TEXTOS.DESCRICAO%TYPE,
                                       V_TEXTO         IN     LONG,
                                       V_TIPO          IN     TEXTOS.TIPO%TYPE,
                                       V_STATUS        IN     TEXTOS.STATUS%TYPE,
                                       V_DIRECIONADO   IN     TEXTOS.DIRECIONADO%TYPE,
                                       V_NUMERO_NEW    IN     TEXTOS.NUMERO%TYPE,
                                       V_FUNCAO        IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO TEXTOS     VALUES (V_MNEMONICO, V_NUMERO, V_DESCRICAO, V_TEXTO, V_TIPO, V_STATUS, V_DIRECIONADO); 

  ELSIF V_FUNCAO = 2 THEN
     UPDATE TEXTOS SET DESCRICAO = V_DESCRICAO, TEXTO = V_TEXTO, TIPO = V_TIPO, STATUS = V_STATUS, DIRECIONADO = V_DIRECIONADO 
                       WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE TEXTOS     WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO;

  ELSIF V_FUNCAO = 4 THEN
     UPDATE TEXTOS     SET NUMERO = V_NUMERO_NEW WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO;

  ELSIF V_FUNCAO = 5 THEN
     UPDATE TEXTOS     SET DESCRICAO = V_DESCRICAO WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO;
  END IF;

  COMMIT WORK;

END PRC_TEXTOS;
/
