CREATE OR REPLACE PROCEDURE PRC_TIPO_COLETORES(V_ID_TIPO_COLETOR  IN OUT TIPO_COLETORES.ID_TIPO_COLETOR%TYPE,
                                               V_NOME             IN     TIPO_COLETORES.NOME%TYPE,
                                               V_STATUS           IN     TIPO_COLETORES.STATUS%TYPE,
                                               V_FUNCAO           IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_TIPO_COLETOR.NEXTVAL INTO V_ID_TIPO_COLETOR FROM DUAL;
     INSERT INTO TIPO_COLETORES VALUES (V_ID_TIPO_COLETOR, V_NOME, V_STATUS);
     
  ELSIF V_FUNCAO = 2 THEN
     UPDATE TIPO_COLETORES SET NOME = V_NOME, STATUS = V_STATUS
                           WHERE ID_TIPO_COLETOR = V_ID_TIPO_COLETOR;

  ELSIF V_FUNCAO = 3 THEN
     DELETE TIPO_COLETORES WHERE ID_TIPO_COLETOR = V_ID_TIPO_COLETOR;
	 
  END IF;

  COMMIT WORK;

END PRC_TIPO_COLETORES;
/
