CREATE OR REPLACE PROCEDURE PRC_EQUIP_CENTROS_RASTREIO(V_EQUIPAMENTO     IN     EQUIPAMENTOS_CENTROS_RASTREIO.EQUIPAMENTO%TYPE,
                                                       V_CENTRO_RASTREIO IN     EQUIPAMENTOS_CENTROS_RASTREIO.CENTRO_RASTREIO%TYPE,
                                                       V_FUNCAO          IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO EQUIPAMENTOS_CENTROS_RASTREIO VALUES (V_EQUIPAMENTO, V_CENTRO_RASTREIO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE EQUIPAMENTOS_CENTROS_RASTREIO WHERE EQUIPAMENTO = V_EQUIPAMENTO AND CENTRO_RASTREIO = V_CENTRO_RASTREIO;

  END IF;           

  COMMIT WORK;

END PRC_EQUIP_CENTROS_RASTREIO;
-- fim bloco
