CREATE OR REPLACE PROCEDURE PRC_ORG_EMPRESAS_CONVENIADAS(V_ID_EMPRESA_CONVENIADA     IN     ORG_EMPRESAS_CONVENIADAS.ID_EMPRESA_CONVENIADA%TYPE,
                                                         V_CORREL_EMPRESA_CONVENIADA IN OUT ORG_EMPRESAS_CONVENIADAS.CORREL_EMPRESA_CONVENIADA%TYPE,
                                                         V_SETOR                     IN     ORG_EMPRESAS_CONVENIADAS.SETOR%TYPE,
                                                         V_CARGO                     IN     ORG_EMPRESAS_CONVENIADAS.CARGO%TYPE,
                                                         V_STATUS                    IN     ORG_EMPRESAS_CONVENIADAS.STATUS%TYPE,
                                                         V_FUNCAO                    IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT NVL(MAX(OEC.CORREL_EMPRESA_CONVENIADA)+1,1) INTO V_CORREL_EMPRESA_CONVENIADA FROM ORG_EMPRESAS_CONVENIADAS OEC 
      WHERE OEC.ID_EMPRESA_CONVENIADA = V_ID_EMPRESA_CONVENIADA;

     INSERT INTO ORG_EMPRESAS_CONVENIADAS VALUES (V_ID_EMPRESA_CONVENIADA, V_CORREL_EMPRESA_CONVENIADA, V_SETOR, V_CARGO, V_STATUS);

  ELSIF V_FUNCAO = 2 THEN
        UPDATE ORG_EMPRESAS_CONVENIADAS SET SETOR = V_SETOR, CARGO = V_CARGO, STATUS = V_STATUS
                                      WHERE ID_EMPRESA_CONVENIADA = V_ID_EMPRESA_CONVENIADA
                                        AND CORREL_EMPRESA_CONVENIADA = V_CORREL_EMPRESA_CONVENIADA;

  ELSIF V_FUNCAO = 3 THEN
     DELETE ORG_EMPRESAS_CONVENIADAS WHERE ID_EMPRESA_CONVENIADA = V_ID_EMPRESA_CONVENIADA
                                       AND CORREL_EMPRESA_CONVENIADA = V_CORREL_EMPRESA_CONVENIADA;
  END IF;

  COMMIT WORK;
END PRC_ORG_EMPRESAS_CONVENIADAS;
/

