CREATE OR REPLACE PROCEDURE PRC_ORIENTACOES(V_ID_ORIENTACAO         IN OUT ORIENTACOES.ID_ORIENTACAO%TYPE,
                                            V_ORIENTACAO            IN     ORIENTACOES.ORIENTACAO%TYPE,
                                            V_STATUS_ORIENTACAO     IN     ORIENTACOES.STATUS_ORIENTACAO%TYPE,
                                            V_PRIORIDADE_ORIENTACAO IN     ORIENTACOES.PRIORIDADE_ORIENTACAO%TYPE,
                                            V_GRUPO_ORIENTACAO      IN     ORIENTACOES.GRUPO_ORIENTACAO%TYPE,
                                            V_FUNCAO                IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_ORIENTACAO.NEXTVAL INTO V_ID_ORIENTACAO FROM DUAL;
     INSERT INTO ORIENTACOES VALUES (V_ID_ORIENTACAO, V_ORIENTACAO, V_STATUS_ORIENTACAO, V_PRIORIDADE_ORIENTACAO, V_GRUPO_ORIENTACAO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE ORIENTACOES SET ORIENTACAO = V_ORIENTACAO, STATUS_ORIENTACAO = V_STATUS_ORIENTACAO, 
                                  PRIORIDADE_ORIENTACAO = V_PRIORIDADE_ORIENTACAO, GRUPO_ORIENTACAO = V_GRUPO_ORIENTACAO
                       WHERE ID_ORIENTACAO = V_ID_ORIENTACAO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE ORIENTACOES WHERE ID_ORIENTACAO = V_ID_ORIENTACAO;
  END IF;

  COMMIT WORK;

END PRC_ORIENTACOES;
/
