CREATE OR REPLACE PROCEDURE PRC_POSTOS_SERVICOS_B2B(V_POSTO             IN POSTOS_SERVICOS_B2B.POSTO%TYPE,
                                                    V_ID_SERVICO_B2B    IN POSTOS_SERVICOS_B2B.ID_SERVICO_B2B%TYPE,
                                                    V_LOGIN             IN POSTOS_SERVICOS_B2B.LOGIN%TYPE,
                                                    V_PASS              IN POSTOS_SERVICOS_B2B.PASS%TYPE,
                                                    V_LOTE              IN POSTOS_SERVICOS_B2B.LOTE%TYPE,
                                                    V_FUNCAO            IN      NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO POSTOS_SERVICOS_B2B VALUES (V_POSTO, V_ID_SERVICO_B2B, V_LOGIN, V_PASS, V_LOTE);
  
  ELSIF V_FUNCAO = 2 THEN
	 UPDATE POSTOS_SERVICOS_B2B SET LOGIN = V_LOGIN, PASS = V_PASS, LOTE = V_LOTE
          WHERE POSTO = V_POSTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;
	 
  ELSIF V_FUNCAO = 3 THEN
     DELETE POSTOS_SERVICOS_B2B WHERE POSTO = V_POSTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;
  
  ELSIF V_FUNCAO = 4 THEN
     UPDATE POSTOS_SERVICOS_B2B SET LOTE = LOTE + 1 
      WHERE POSTO = V_POSTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;

  END IF;

  COMMIT WORK;

END PRC_POSTOS_SERVICOS_B2B;
/