CREATE OR REPLACE PROCEDURE PRC_EMPRESAS(V_EMPRESA         IN OUT EMPRESAS.EMPRESA%TYPE,
                                         V_NOME            IN     EMPRESAS.NOME%TYPE,
                                         V_FUNCAO          IN     NUMBER) IS
BEGIN
  IF V_NOME = NULL THEN
     RAISE_APPLICATION_ERROR(-20000, 'NÃO PODE INSERIR DADOS EM BRANCO');
  END IF;

  IF V_FUNCAO = 1 THEN
     SELECT SQ_EMPRESA.NEXTVAL INTO V_EMPRESA FROM DUAL;
     INSERT INTO EMPRESAS VALUES (V_EMPRESA, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE EMPRESAS SET NOME = V_NOME WHERE EMPRESA = V_EMPRESA;
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE EMPRESAS WHERE EMPRESA = V_EMPRESA;
  END IF;

  COMMIT WORK;
END PRC_EMPRESAS;
/
