CREATE OR REPLACE PROCEDURE PRC_MODELOS_EQUIPAMENTOS(V_MODELO_EQUIPAMENTO IN OUT  MODELOS_EQUIPAMENTOS.MODELO_EQUIPAMENTO%TYPE,
                                                     V_NOME_MODELO        IN      MODELOS_EQUIPAMENTOS.NOME_MODELO%TYPE,
                                                     V_ENVIA              IN      MODELOS_EQUIPAMENTOS.ENVIA%TYPE,
                                                     V_RECEBE             IN      MODELOS_EQUIPAMENTOS.RECEBE%TYPE,
                                                     V_FUNCAO             IN      NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_MODELO_EQUIPAMENTO.NEXTVAL INTO V_MODELO_EQUIPAMENTO FROM DUAL;
     INSERT INTO MODELOS_EQUIPAMENTOS VALUES (V_MODELO_EQUIPAMENTO, V_NOME_MODELO,
                                                    V_ENVIA, V_RECEBE);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE MODELOS_EQUIPAMENTOS SET NOME_MODELO = V_NOME_MODELO,
                                           ENVIA = V_ENVIA, RECEBE = V_RECEBE
                        WHERE MODELO_EQUIPAMENTO = V_MODELO_EQUIPAMENTO;
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE MODELOS_EQUIPAMENTOS WHERE MODELO_EQUIPAMENTO = V_MODELO_EQUIPAMENTO;
  END IF;

  COMMIT WORK;

END PRC_MODELOS_EQUIPAMENTOS;
/
