CREATE OR REPLACE PROCEDURE PRC_VALORES_REFERENCIA(V_MNEMONICO     IN VALORES_REFERENCIA.MNEMONICO%TYPE,
                                                   V_NUMERO        IN VALORES_REFERENCIA.NUMERO%TYPE,
                                                   V_CORREL        IN VALORES_REFERENCIA.CORREL%TYPE,
                                                   V_VARIAVEL      IN VALORES_REFERENCIA.VARIAVEL%TYPE,
                                                   V_VREFERENCIA   IN VALORES_REFERENCIA.VREFERENCIA%TYPE,
                                                   V_FUNCAO        IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO VALORES_REFERENCIA VALUES (V_MNEMONICO, V_NUMERO, V_CORREL,
                                                  V_VARIAVEL, V_VREFERENCIA); 

  ELSIF V_FUNCAO = 2 THEN
     UPDATE VALORES_REFERENCIA SET VREFERENCIA = V_VREFERENCIA
                        WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND CORREL = V_CORREL AND VARIAVEL = V_VARIAVEL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE VALORES_REFERENCIA WHERE MNEMONICO = V_MNEMONICO AND NUMERO = V_NUMERO AND CORREL = V_CORREL AND VARIAVEL = V_VARIAVEL;

  END IF;

  COMMIT WORK;

END PRC_VALORES_REFERENCIA;
/
