CREATE OR REPLACE PROCEDURE PRC_RESULTADOS_PASS(V_ID       IN RESULTADOS_PASS.ID%TYPE,
                                                V_PASS     IN RESULTADOS_PASS.PASS%TYPE,
                                                V_PURE     IN RESULTADOS_PASS.PURE%TYPE,
												V_DATA_CAD IN RESULTADOS_PASS.DATA_CAD%TYPE,
                                                V_FUNCAO   IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO RESULTADOS_PASS VALUES (V_ID, V_PASS, V_PURE, V_DATA_CAD);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE RESULTADOS_PASS SET PASS = V_PASS, PURE = V_PURE, DATA_CAD = V_DATA_CAD WHERE ID = V_ID;

  ELSIF V_FUNCAO = 3 THEN
     DELETE RESULTADOS_PASS WHERE ID = V_ID;
	 
  ELSIF V_FUNCAO = 4 THEN
     UPDATE RESULTADOS_PASS SET DATA_CAD = V_DATA_CAD WHERE ID = V_ID;

  END IF;

  COMMIT WORK;

END PRC_RESULTADOS_PASS;
 