CREATE OR REPLACE PROCEDURE PRC_RECALCULO2(V_TAB IN VARCHAR2, V_VALOR_CH OUT NUMBER) AS
CURSOR_AUX INTEGER;
RETURN_VALUE INTEGER;
BEGIN
     CURSOR_AUX := SYS.DBMS_SQL.OPEN_CURSOR;
     SYS.DBMS_SQL.PARSE(CURSOR_AUX, V_TAB, SYS.DBMS_SQL.V7);
     RETURN_VALUE := SYS.DBMS_SQL.EXECUTE(CURSOR_AUX);

     SYS.DBMS_SQL.DEFINE_COLUMN(CURSOR_AUX, 1, V_VALOR_CH);
     IF SYS.DBMS_SQL.FETCH_ROWS(CURSOR_AUX) > 0 THEN
        SYS.DBMS_SQL.COLUMN_VALUE(CURSOR_AUX, 1, V_VALOR_CH);
     END IF;
     SYS.DBMS_SQL.CLOSE_CURSOR(CURSOR_AUX);
END PRC_RECALCULO2;
/
