CREATE OR REPLACE PROCEDURE PRC_FRASES(V_CODIGO          IN OUT FRASES.CODIGO%TYPE,
                                       V_FRASE           IN     FRASES.FRASE%TYPE,
                                       V_TIPO_FRASE      IN     FRASES.TIPO_FRASE%TYPE,
                                       V_MNEMONICO_FRASE IN     FRASES.MNEMONICO_FRASE%TYPE,
                                       V_FRASE_FORMAT    IN     FRASES.FRASE_FORMAT%TYPE,
                                       V_FUNCAO          IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     IF V_CODIGO IS NULL THEN
        SELECT TO_CHAR(SQ_FRASE.NEXTVAL) INTO V_CODIGO FROM DUAL;
     END IF;

     INSERT INTO FRASES VALUES (V_CODIGO, V_FRASE, V_TIPO_FRASE, V_MNEMONICO_FRASE, V_FRASE_FORMAT);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE FRASES SET FRASE = V_FRASE, TIPO_FRASE = V_TIPO_FRASE, MNEMONICO_FRASE = V_MNEMONICO_FRASE, FRASE_FORMAT = V_FRASE_FORMAT
                       WHERE CODIGO = V_CODIGO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE FRASES WHERE CODIGO = V_CODIGO;
  END IF;

  COMMIT WORK;

END PRC_FRASES;
/
