CREATE OR REPLACE PROCEDURE PRC_GRUPOS_OBJ(V_GRUPO_OBJ         IN OUT GRUPOS_OBJ.GRUPO_OBJ%TYPE,
                                           V_NOME_GRUPO        IN     GRUPOS_OBJ.NOME_GRUPO%TYPE,
                                           V_TIPO_OBJ          IN     GRUPOS_OBJ.TIPO_OBJ%TYPE,
                                           V_FUNCAO            IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_GRUPO_OBJ.NEXTVAL INTO V_GRUPO_OBJ FROM DUAL;
     INSERT INTO GRUPOS_OBJ VALUES (V_GRUPO_OBJ, V_NOME_GRUPO, V_TIPO_OBJ);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE GRUPOS_OBJ SET NOME_GRUPO = V_NOME_GRUPO, TIPO_OBJ = V_TIPO_OBJ
      WHERE GRUPO_OBJ = V_GRUPO_OBJ;

  ELSIF V_FUNCAO = 3 THEN
     DELETE GRUPOS_OBJ WHERE GRUPO_OBJ = V_GRUPO_OBJ;
  END IF;

  COMMIT WORK;

END PRC_GRUPOS_OBJ;
