CREATE OR REPLACE PROCEDURE PRC_GRUPOS_ETIQUETAS(V_GRUPO_ETIQUETA         IN OUT GRUPOS_ETIQUETAS.GRUPO_ETIQUETA%TYPE,
                                                 V_NOME                   IN     GRUPOS_ETIQUETAS.NOME%TYPE,
                                                 V_MATERIAL               IN     GRUPOS_ETIQUETAS.MATERIAL%TYPE,
                                                 V_QT_ETIQUETAS           IN     GRUPOS_ETIQUETAS.QT_ETIQUETAS%TYPE,
                                                 V_SEPARA_ETIQUETAS       IN     GRUPOS_ETIQUETAS.SEPARA_ETIQUETAS%TYPE,
                                                 V_TIPO_CODIGO            IN     GRUPOS_ETIQUETAS.TIPO_CODIGO%TYPE,
                                                 V_MARGEM_ESQUERDA_CODIGO IN     GRUPOS_ETIQUETAS.MARGEM_ESQUERDA_CODIGO%TYPE,
                                                 V_RATIO_CODIGO           IN     GRUPOS_ETIQUETAS.RATIO_CODIGO%TYPE,
                                                 V_REALCA_NOME            IN     GRUPOS_ETIQUETAS.REALCA_NOME%TYPE,
                                                 V_IMPRESSORA             IN     GRUPOS_ETIQUETAS.IMPRESSORA%TYPE,
                                                 V_DIGITO_CODIGO          IN     GRUPOS_ETIQUETAS.DIGITO_CODIGO%TYPE,
												 V_QT_MAX_MNEMONICOS      IN     GRUPOS_ETIQUETAS.QT_MAX_MNEMONICOS%TYPE,
                                                 V_FUNCAO                 IN     NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_GRUPO_ETIQUETA.NEXTVAL INTO V_GRUPO_ETIQUETA FROM DUAL;
     INSERT INTO GRUPOS_ETIQUETAS VALUES (V_GRUPO_ETIQUETA, V_NOME, V_MATERIAL, V_QT_ETIQUETAS, V_SEPARA_ETIQUETAS, V_TIPO_CODIGO, V_MARGEM_ESQUERDA_CODIGO, 
                                          V_RATIO_CODIGO, V_REALCA_NOME, V_IMPRESSORA, V_DIGITO_CODIGO, V_QT_MAX_MNEMONICOS);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE GRUPOS_ETIQUETAS SET NOME = V_NOME, MATERIAL = V_MATERIAL, QT_ETIQUETAS = V_QT_ETIQUETAS, SEPARA_ETIQUETAS = V_SEPARA_ETIQUETAS,
            TIPO_CODIGO = V_TIPO_CODIGO, MARGEM_ESQUERDA_CODIGO = V_MARGEM_ESQUERDA_CODIGO, RATIO_CODIGO = V_RATIO_CODIGO, REALCA_NOME = V_REALCA_NOME,
            IMPRESSORA = V_IMPRESSORA, DIGITO_CODIGO = V_DIGITO_CODIGO, QT_MAX_MNEMONICOS = V_QT_MAX_MNEMONICOS
      WHERE GRUPO_ETIQUETA = V_GRUPO_ETIQUETA;

  ELSIF V_FUNCAO = 3 THEN
     DELETE GRUPOS_ETIQUETAS WHERE GRUPO_ETIQUETA = V_GRUPO_ETIQUETA;
  END IF;

  COMMIT WORK;

END PRC_GRUPOS_ETIQUETAS;
/


