CREATE OR REPLACE PROCEDURE PRC_LOTES_RASTROS(V_ID_LOTE_RASTRO IN OUT LOTES_RASTROS.ID_LOTE_RASTRO%TYPE,
                                              V_DATA_RASTRO    IN     LOTES_RASTROS.DATA_RASTRO%TYPE,
                                              V_TIPO_RASTRO    IN     LOTES_RASTROS.TIPO_RASTRO%TYPE,
                                              V_FUNCAO         IN     NUMBER) IS                         
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_LOTE_RASTRO.NEXTVAL INTO V_ID_LOTE_RASTRO FROM DUAL;
     INSERT INTO LOTES_RASTROS VALUES (V_ID_LOTE_RASTRO, V_DATA_RASTRO, V_TIPO_RASTRO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE LOTES_RASTROS WHERE ID_LOTE_RASTRO = V_ID_LOTE_RASTRO;
     
  END IF;             

  COMMIT WORK;

END PRC_LOTES_RASTROS;
/
