CREATE OR REPLACE PROCEDURE PRC_DEPARTAMENTOS(V_DEPARTAMENTO     IN OUT DEPARTAMENTOS.DEPARTAMENTO%TYPE,
                                              V_NOME             IN     DEPARTAMENTOS.NOME%TYPE,
                                              V_CCUSTO           IN     DEPARTAMENTOS.CCUSTO%TYPE,
                                              V_CONTROLE_ESTOQUE IN     DEPARTAMENTOS.CONTROLE_ESTOQUE%TYPE,
                                              V_FUNCAO           IN NUMBER) IS

BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_DEPARTAMENTO.NEXTVAL INTO V_DEPARTAMENTO FROM DUAL;
     INSERT INTO DEPARTAMENTOS VALUES (V_DEPARTAMENTO, V_NOME, V_CCUSTO, V_CONTROLE_ESTOQUE);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE DEPARTAMENTOS SET NOME = V_NOME, CCUSTO = V_CCUSTO, CONTROLE_ESTOQUE = V_CONTROLE_ESTOQUE
                                 WHERE DEPARTAMENTO = V_DEPARTAMENTO; 
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE DEPARTAMENTOS WHERE DEPARTAMENTO = V_DEPARTAMENTO;
  END IF;

  COMMIT WORK;

END PRC_DEPARTAMENTOS;
/
