CREATE OR REPLACE PROCEDURE PRC_INS_PRODUTOS(V_PRODUTO IN PRODUTOS.PRODUTO%TYPE) IS
BEGIN
  INSERT INTO ESTOQUE SELECT V_PRODUTO, DEPARTAMENTO, 0, 0,0 FROM DEPARTAMENTOS;
  COMMIT WORK;

END PRC_INS_PRODUTOS;
/
