CREATE OR REPLACE PROCEDURE PRC_PACOTES_PROCEDIMENTOS_TISS(V_CONVENIO      IN  PACOTES_PROCEDIMENTOS_TISS.CONVENIO%TYPE,
                                                           V_MNEMONICO     IN  PACOTES_PROCEDIMENTOS_TISS.MNEMONICO%TYPE,
                                                           V_CATALOGO_TISS IN  PACOTES_PROCEDIMENTOS_TISS.CATALOGO_TISS%TYPE,
                                                           V_FUNCAO        IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO PACOTES_PROCEDIMENTOS_TISS VALUES (V_CONVENIO, V_MNEMONICO, V_CATALOGO_TISS);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE PACOTES_PROCEDIMENTOS_TISS SET CATALOGO_TISS = V_CATALOGO_TISS
                          WHERE CONVENIO = V_CONVENIO AND MNEMONICO = V_MNEMONICO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE PACOTES_PROCEDIMENTOS_TISS WHERE CONVENIO = V_CONVENIO AND MNEMONICO = V_MNEMONICO;
  END IF;

  COMMIT WORK;

END PRC_PACOTES_PROCEDIMENTOS_TISS;
/


