CREATE OR REPLACE PROCEDURE PRC_ATENDIMENTOS_B2B(V_POSTO                   IN ATENDIMENTOS_B2B.POSTO%TYPE,
                                                 V_ATENDIMENTO             IN ATENDIMENTOS_B2B.ATENDIMENTO%TYPE,
                                                 V_ID_SERVICO_B2B          IN ATENDIMENTOS_B2B.ID_SERVICO_B2B%TYPE,
                                                 V_CODIGO_EXTERNO          IN ATENDIMENTOS_B2B.CODIGO_EXTERNO%TYPE,
                                                 V_DATA_B2B                IN ATENDIMENTOS_B2B.DATA_B2B%TYPE,
                                                 V_SITUACAO_B2B            IN ATENDIMENTOS_B2B.SITUACAO_B2B%TYPE,
                                                 V_FUNCAO                  IN NUMBER) IS
BEGIN
     DECLARE
            V_ACHEI  NUMBER(8);
            
            CURSOR CUR_PROCURA IS
                   SELECT ATENDIMENTO FROM ATENDIMENTOS_B2B
                    WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;
      BEGIN
           IF V_FUNCAO = 1 THEN
              INSERT INTO ATENDIMENTOS_B2B VALUES (V_POSTO, V_ATENDIMENTO, V_ID_SERVICO_B2B, V_CODIGO_EXTERNO, V_DATA_B2B, V_SITUACAO_B2B);

           ELSIF V_FUNCAO = 2 THEN
              UPDATE ATENDIMENTOS_B2B SET CODIGO_EXTERNO = V_CODIGO_EXTERNO, SITUACAO_B2B = V_SITUACAO_B2B, DATA_B2B = V_DATA_B2B
	                                WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;

           ELSIF V_FUNCAO = 3 THEN
              DELETE ATENDIMENTOS_B2B WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;
	 
           ELSIF V_FUNCAO = 4 THEN
                OPEN CUR_PROCURA;
                FETCH CUR_PROCURA INTO V_ACHEI;
  
                IF CUR_PROCURA%NOTFOUND THEN
                   INSERT INTO ATENDIMENTOS_B2B VALUES (V_POSTO, V_ATENDIMENTO, V_ID_SERVICO_B2B, V_CODIGO_EXTERNO, V_DATA_B2B, V_SITUACAO_B2B);
				ELSE   
                    UPDATE ATENDIMENTOS_B2B SET CODIGO_EXTERNO = V_CODIGO_EXTERNO, SITUACAO_B2B = V_SITUACAO_B2B, DATA_B2B = V_DATA_B2B
	                                      WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND ID_SERVICO_B2B = V_ID_SERVICO_B2B;
                END IF;
           END IF;
      END;
	  
      COMMIT WORK;
END PRC_ATENDIMENTOS_B2B;
/
