CREATE OR REPLACE PROCEDURE PRC_POSTOS_ENTIDADES(V_ID_POSTO       IN POSTOS_ENTIDADES.ID_POSTO%TYPE,
                                                 V_ID_ENTIDADE    IN POSTOS_ENTIDADES.ID_ENTIDADE%TYPE,
                                                 V_FUNCAO      IN      NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO POSTOS_ENTIDADES VALUES (V_ID_POSTO, V_ID_ENTIDADE);
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE POSTOS_ENTIDADES WHERE ID_POSTO = V_ID_POSTO AND ID_ENTIDADE = V_ID_ENTIDADE;
  
  END IF;

  COMMIT WORK;

END PRC_POSTOS_ENTIDADES;
/