CREATE OR REPLACE PROCEDURE PRC_CONSERVANTES_PROCED(V_ID_CONSERVANTE IN CONSERVANTES_PROCEDIMENTOS.ID_CONSERVANTE%TYPE,
                                                     V_MNEMONICO       IN CONSERVANTES_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                     V_FUNCAO          IN NUMBER) IS
BEGIN                                                           
  IF V_FUNCAO = 1 THEN                                          
     INSERT INTO CONSERVANTES_PROCEDIMENTOS VALUES(V_ID_CONSERVANTE, V_MNEMONICO);


  ELSIF V_FUNCAO = 3 THEN
            DELETE CONSERVANTES_PROCEDIMENTOS WHERE ID_CONSERVANTE = V_ID_CONSERVANTE AND MNEMONICO = V_MNEMONICO;	

  END IF;

  COMMIT WORK;
END PRC_CONSERVANTES_PROCED;
/
