CREATE OR REPLACE PROCEDURE PRC_COBRANCA_ATENDIMENTOS(V_POSTO          IN     COBRANCA_ATENDIMENTOS.POSTO%TYPE,
                                                      V_ATENDIMENTO    IN     COBRANCA_ATENDIMENTOS.ATENDIMENTO%TYPE,
                                                      V_USUARIO        IN     COBRANCA_ATENDIMENTOS.USUARIO%TYPE,
                                                      V_DATA_CAD       IN     COBRANCA_ATENDIMENTOS.DATA_CAD%TYPE,
                                                      V_POSTO_COBRANCA IN     COBRANCA_ATENDIMENTOS.POSTO_COBRANCA%TYPE,
                                                      V_FUNCAO         IN     NUMBER) IS

BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO COBRANCA_ATENDIMENTOS VALUES (V_POSTO, V_ATENDIMENTO, V_USUARIO, V_DATA_CAD, V_POSTO_COBRANCA);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE COBRANCA_ATENDIMENTOS SET DATA_CAD = V_DATA_CAD, USUARIO = V_USUARIO,
                                            POSTO_COBRANCA = V_POSTO_COBRANCA
                                        WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE COBRANCA_ATENDIMENTOS WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO;

  END IF;

  COMMIT WORK;
END PRC_COBRANCA_ATENDIMENTOS;
/
