CREATE OR REPLACE PROCEDURE PRC_SETORES_CENTROS_RASTREO(V_SETOR           IN SETORES_CENTROS_RASTREO.SETOR%TYPE,
                                                        V_CENTRO_RASTREIO IN SETORES_CENTROS_RASTREO.CENTRO_RASTREIO%TYPE,
                                                        V_FUNCAO          IN NUMBER) IS                         
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO SETORES_CENTROS_RASTREO VALUES (V_SETOR, V_CENTRO_RASTREIO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE SETORES_CENTROS_RASTREO WHERE SETOR = V_SETOR AND CENTRO_RASTREIO = V_CENTRO_RASTREIO;
     
  END IF;             

  COMMIT WORK;

END PRC_SETORES_CENTROS_RASTREO;
/
