CREATE OR REPLACE PROCEDURE PRC_CCUSTOS(V_CCUSTO  IN OUT CCUSTOS.CCUSTO%TYPE,
                                        V_NOME    IN     CCUSTOS.NOME%TYPE,
                                        V_EMPRESA IN     CCUSTOS.EMPRESA%TYPE,
                                        V_FUNCAO  IN NUMBER) IS

BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT SQ_CCUSTO.NEXTVAL INTO V_CCUSTO FROM DUAL;
     INSERT INTO CCUSTOS VALUES (V_CCUSTO, V_NOME, V_EMPRESA);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CCUSTOS SET NOME = V_NOME, EMPRESA = V_EMPRESA WHERE CCUSTO = V_CCUSTO;
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE CCUSTOS WHERE CCUSTO = V_CCUSTO;
  END IF;

  COMMIT WORK;

END PRC_CCUSTOS;
/
