CREATE OR REPLACE PROCEDURE PRC_ACOMODACOES_TEMPOS_ENTREGA(V_ID_ACOMODACAO          IN ACOMODACOES_TEMPOS_ENTREGA.ID_ACOMODACAO%TYPE,
                                                           V_ID_TEMPO_ENTREGA       IN ACOMODACOES_TEMPOS_ENTREGA.ID_TEMPO_ENTREGA%TYPE,
                                                           V_FUNCAO                 IN NUMBER) IS
BEGIN                                                           
  IF V_FUNCAO = 1 THEN                                          
     INSERT INTO ACOMODACOES_TEMPOS_ENTREGA VALUES(V_ID_ACOMODACAO, V_ID_TEMPO_ENTREGA);

  ELSIF V_FUNCAO = 3 THEN
            DELETE ACOMODACOES_TEMPOS_ENTREGA WHERE ID_ACOMODACAO = V_ID_ACOMODACAO AND ID_TEMPO_ENTREGA = V_ID_TEMPO_ENTREGA;	

  END IF;

  COMMIT WORK;
END PRC_ACOMODACOES_TEMPOS_ENTREGA;
/
