CREATE OR REPLACE PROCEDURE PRC_CATALOGO_TISS(V_CATALOGO_TISS  IN OUT CATALOGO_TISS.CATALOGO_TISS%TYPE,
                                         V_NOME                IN CATALOGO_TISS.NOME%TYPE,
                                         V_FUNCAO              IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CATALOGO_TISS VALUES (V_CATALOGO_TISS, V_NOME);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CATALOGO_TISS SET NOME = V_NOME
                           WHERE CATALOGO_TISS = V_CATALOGO_TISS;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CATALOGO_TISS WHERE CATALOGO_TISS = V_CATALOGO_TISS;
  END IF;

  COMMIT WORK;

END PRC_CATALOGO_TISS;
/
