CREATE OR REPLACE PROCEDURE PRC_FORNECEDORES_CATEGORIAS(V_FORNECEDOR  IN FORNECEDORES_CATEGORIAS.FORNECEDOR%TYPE,
                                                        V_CATEGORIA   IN FORNECEDORES_CATEGORIAS.CATEGORIA%TYPE,
                                                        V_TABELA      IN FORNECEDORES.TABELA%TYPE,
                                                        V_FUNCAO      IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO FORNECEDORES_CATEGORIAS VALUES (V_FORNECEDOR, V_CATEGORIA);

     IF V_TABELA = 'S' THEN
        INSERT INTO TABELAS_FORNECEDORES SELECT V_FORNECEDOR, PRODUTO, '', 0 FROM PRODUTOS WHERE CATEGORIA = V_CATEGORIA;
     END IF;

  ELSIF V_FUNCAO = 3 THEN
     DELETE FORNECEDORES_CATEGORIAS WHERE FORNECEDOR = V_FORNECEDOR AND CATEGORIA = V_CATEGORIA;

     IF V_TABELA = 'S' THEN
        DELETE TABELAS_FORNECEDORES WHERE FORNECEDOR = V_FORNECEDOR AND 
        PRODUTO IN (SELECT PRODUTO FROM PRODUTOS WHERE CATEGORIA = V_CATEGORIA);
     END IF;

  END IF;

  COMMIT WORK;

END PRC_FORNECEDORES_CATEGORIAS;
/
