CREATE OR REPLACE PROCEDURE PRC_CLIENTES_PASS(V_ID      IN CLIENTES_PASS.ID%TYPE,
                                              V_PASS    IN CLIENTES_PASS.PASS%TYPE,
                                              V_PURE    IN CLIENTES_PASS.PASS%TYPE,
                                              V_FUNCAO  IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CLIENTES_PASS VALUES (V_ID, V_PASS, V_PURE);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE CLIENTES_PASS SET PASS = V_PASS, PURE = V_PURE WHERE ID = V_ID;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CLIENTES_PASS WHERE ID = V_ID;
  END IF;

  COMMIT WORK;

END PRC_CLIENTES_PASS;
/
