CREATE OR REPLACE PROCEDURE PRC_TRANSACOES_TES(V_POSTO             IN TRANSACOES_TES.POSTO%TYPE,
                                               V_ATENDIMENTO       IN TRANSACOES_TES.ATENDIMENTO%TYPE,
                                               V_CORREL_TRANSACAO  IN OUT TRANSACOES_TES.CORREL_TRANSACAO%TYPE,
                                               V_USUARIO_TRANSACAO IN TRANSACOES_TES.USUARIO_TRANSACAO%TYPE,
                                               V_DATA_TRANSACAO    IN TRANSACOES_TES.DATA_TRANSACAO%TYPE,
                                               V_ESTACAO_TRANSACAO IN TRANSACOES_TES.ESTACAO_TRANSACAO%TYPE,
                                               V_TIPO_TRANSACAO    IN TRANSACOES_TES.TIPO_TRANSACAO%TYPE,
                                               V_TRANSACAO         IN TRANSACOES_TES.TRANSACAO%TYPE,
                                               V_FUNCAO            IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     SELECT NVL(MAX(TT.CORREL_TRANSACAO),0)+1 INTO V_CORREL_TRANSACAO
       FROM TRANSACOES_TES TT WHERE TT.POSTO = V_POSTO AND TT.ATENDIMENTO = V_ATENDIMENTO;


     INSERT INTO TRANSACOES_TES VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL_TRANSACAO,
                                              V_USUARIO_TRANSACAO, V_DATA_TRANSACAO, V_ESTACAO_TRANSACAO,
                                              V_TIPO_TRANSACAO, V_TRANSACAO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE TRANSACOES_TES WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO 
                             AND CORREL_TRANSACAO = V_CORREL_TRANSACAO;
  END IF;

  COMMIT WORK;

END PRC_TRANSACOES_TES;
/