CREATE OR REPLACE PROCEDURE PRC_GRUPOS_ETIQUETAS_TIPO_COLETORES(V_GRUPO_ETIQUETA   IN  GRUPOS_ETIQUETAS_TIPO_COLETORES.GRUPO_ETIQUETA%TYPE,
																V_ID_TIPO_COLETOR  IN  GRUPOS_ETIQUETAS_TIPO_COLETORES.ID_TIPO_COLETOR%TYPE,
                                                                V_FUNCAO           IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO GRUPOS_ETIQUETAS_TIPO_COLETORES VALUES (V_GRUPO_ETIQUETA, V_ID_TIPO_COLETOR);
     
  ELSIF V_FUNCAO = 3 THEN
     DELETE GRUPOS_ETIQUETAS_TIPO_COLETORES WHERE GRUPO_ETIQUETA = V_GRUPO_ETIQUETA AND ID_TIPO_COLETOR = V_ID_TIPO_COLETOR;
	 
  END IF;

  COMMIT WORK;

END PRC_TIPO_COLETORES;
/
