CREATE OR REPLACE PROCEDURE PRC_CLIENTES_B2B(V_REGISTRO           IN CLIENTES_B2B.REGISTRO%TYPE,
                                             V_ID_SERVICO_B2B     IN CLIENTES_B2B.ID_SERVICO_B2B%TYPE,
                                             V_CODIGO_EXTERNO     IN CLIENTES_B2B.CODIGO_EXTERNO%TYPE,
                                             V_NOME_EXTERNO       IN CLIENTES_B2B.NOME_EXTERNO%TYPE,
                                             V_DATA_NAS_EXTERNO   IN CLIENTES_B2B.DATA_NAS_EXTERNO%TYPE,
                                             V_SEXO_EXTERNO       IN CLIENTES_B2B.SEXO_EXTERNO%TYPE,
                                             V_IDENTIDADE_EXTERNO IN CLIENTES_B2B.IDENTIDADE_EXTERNO%TYPE,
                                             V_CPF_EXTERNO        IN CLIENTES_B2B.CPF_EXTERNO%TYPE,
                                             V_FUNCAO             IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CLIENTES_B2B VALUES (V_REGISTRO, V_ID_SERVICO_B2B, V_CODIGO_EXTERNO, V_NOME_EXTERNO, V_DATA_NAS_EXTERNO, V_SEXO_EXTERNO, V_IDENTIDADE_EXTERNO, V_CPF_EXTERNO);

  ELSIF V_FUNCAO = 2 THEN
        UPDATE CLIENTES_B2B SET NOME_EXTERNO = V_NOME_EXTERNO, DATA_NAS_EXTERNO = V_DATA_NAS_EXTERNO, SEXO_EXTERNO = V_SEXO_EXTERNO, IDENTIDADE_EXTERNO = V_IDENTIDADE_EXTERNO, CPF_EXTERNO = V_CPF_EXTERNO
                          WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND CODIGO_EXTERNO = V_CODIGO_EXTERNO;

  ELSIF V_FUNCAO = 3 THEN
     DELETE CLIENTES_B2B WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND CODIGO_EXTERNO = V_CODIGO_EXTERNO;
                            
  ELSIF V_FUNCAO = 4 THEN
     UPDATE CLIENTES_B2B SET REGISTRO = V_REGISTRO
                         WHERE ID_SERVICO_B2B = V_ID_SERVICO_B2B AND CODIGO_EXTERNO = V_CODIGO_EXTERNO;
  END IF;

  COMMIT WORK;
END PRC_CLIENTES_B2B;
/



