CREATE OR REPLACE PROCEDURE PRC_MATERIAIS_PROCEDIMENTOS(V_MNEMONICO IN  MATERIAIS_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                        V_MATERIAL  IN  MATERIAIS_PROCEDIMENTOS.MATERIAL%TYPE,
                                                        V_FUNCAO    IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO MATERIAIS_PROCEDIMENTOS VALUES (V_MNEMONICO, V_MATERIAL);

  ELSIF V_FUNCAO = 3 THEN
     DELETE MATERIAIS_PROCEDIMENTOS WHERE MNEMONICO = V_MNEMONICO AND MATERIAL = V_MATERIAL;

  END IF;

  COMMIT WORK;

END PRC_MATERIAIS_PROCEDIMENTOS;
/
