CREATE OR REPLACE PROCEDURE PRC_CONVENIOS_POSTOS(V_POSTO     IN   CONVENIOS_POSTOS.POSTO%TYPE,
                                                 V_CONVENIO  IN   CONVENIOS_POSTOS.CONVENIO%TYPE,
                                                 V_FUNCAO    IN   NUMBER) IS                         
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO CONVENIOS_POSTOS VALUES (V_POSTO, V_CONVENIO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE CONVENIOS_POSTOS WHERE POSTO = V_POSTO AND CONVENIO = V_CONVENIO;
     
  END IF;             

  COMMIT WORK;

END PRC_CONVENIOS_POSTOS;
/
