CREATE OR REPLACE PROCEDURE PRC_UNIDADES_POSTOS(V_UNIDADE         IN UNIDADES_POSTOS.UNIDADE%TYPE,
                                                V_POSTO           IN UNIDADES_POSTOS.POSTO%TYPE,
                                                V_FUNCAO IN     NUMBER) IS

BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO UNIDADES_POSTOS VALUES (V_UNIDADE, V_POSTO);

  ELSIF V_FUNCAO = 3 THEN
     DELETE UNIDADES_POSTOS WHERE UNIDADE = V_UNIDADE AND POSTO = V_POSTO;
  END IF;

  COMMIT WORK;

END PRC_UNIDADES_POSTOS;
/
