CREATE OR REPLACE PROCEDURE PRC_RESULTADOS(V_POSTO         IN RESULTADOS_ATUAL.POSTO%TYPE, 
                                           V_ATENDIMENTO   IN RESULTADOS_ATUAL.ATENDIMENTO%TYPE, 
                                           V_CORREL        IN RESULTADOS_ATUAL.CORREL%TYPE, 
                                           V_NUMERO        IN RESULTADOS_ATUAL.NUMERO%TYPE, 
                                           V_VARIAVEL      IN RESULTADOS_ATUAL.VARIAVEL%TYPE, 
                                           V_VALOR         IN RESULTADOS_ATUAL.VALOR%TYPE, 
                                           V_USUARIO_AUTO  IN RESULTADOS_ATUAL.USUARIO_AUTO%TYPE,
                                           V_DATA_AUTO     IN RESULTADOS_ATUAL.DATA_AUTO%TYPE,
                                           V_ESTACAO_AUTO  IN RESULTADOS_ATUAL.ESTACAO_AUTO%TYPE,
                                           V_FUNCAO        IN NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO RESULTADOS_ATUAL VALUES (V_POSTO, V_ATENDIMENTO, V_CORREL, V_NUMERO, V_VARIAVEL, V_VALOR,
                                          V_USUARIO_AUTO, V_DATA_AUTO, V_ESTACAO_AUTO);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE RESULTADOS_ATUAL SET VALOR = V_VALOR, USUARIO_AUTO = V_USUARIO_AUTO, DATA_AUTO = V_DATA_AUTO, ESTACAO_AUTO = V_ESTACAO_AUTO
                           WHERE POSTO  = V_POSTO  AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL AND 
                                 NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE RESULTADOS_ATUAL WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND CORREL = V_CORREL;

  END IF;

  COMMIT WORK;

END PRC_RESULTADOS;
/
