CREATE OR REPLACE PROCEDURE VER_EXAMES IS
BEGIN
  DECLARE

  V_POSTO EXAMES.POSTO%TYPE;
  V_ATENDIMENTO EXAMES.ATENDIMENTO%TYPE;
  V_CORREL EXAMES.CORREL%TYPE;

  V_POSTO_OLD EXAMES.POSTO%TYPE;
  V_ATENDIMENTO_OLD EXAMES.ATENDIMENTO%TYPE;
  V_CORREL_OLD EXAMES.CORREL%TYPE;

  CURSOR CUR_EXAMES_OLD IS
  SELECT POSTO, ATENDIMENTO, CORREL FROM JOSE.EXAMES WHERE DATA_CAD >= '01/04/02';

  CURSOR CUR_EXAMES_NEW IS
  SELECT POSTO, ATENDIMENTO, CORREL FROM EXAMES 
    WHERE POSTO = V_POSTO_OLD AND ATENDIMENTO = V_ATENDIMENTO_OLD AND CORREL = V_CORREL_OLD;

  CURSOR CUR_ATENDIMENTOS IS
  SELECT POSTO, ATENDIMENTO FROM ATENDIMENTOS
    WHERE POSTO = V_POSTO_OLD AND ATENDIMENTO = V_ATENDIMENTO_OLD;

  BEGIN 
    FOR EXAMES_CUR_OLD IN CUR_EXAMES_OLD LOOP
      V_POSTO_OLD       := EXAMES_CUR_OLD.POSTO;
      V_ATENDIMENTO_OLD := EXAMES_CUR_OLD.ATENDIMENTO;
      V_CORREL_OLD      := EXAMES_CUR_OLD.CORREL;

      OPEN CUR_EXAMES_NEW;
      FETCH CUR_EXAMES_NEW INTO V_POSTO, V_ATENDIMENTO, V_CORREL;
      IF CUR_EXAMES_NEW%NOTFOUND THEN

         OPEN CUR_ATENDIMENTOS;
         FETCH CUR_ATENDIMENTOS INTO V_POSTO, V_ATENDIMENTO;

         IF CUR_ATENDIMENTOS%FOUND THEN
            INSERT INTO TST SELECT * FROM JOSE.EXAMES WHERE POSTO = V_POSTO_OLD AND 
               ATENDIMENTO = V_ATENDIMENTO_OLD AND CORREL = V_CORREL_OLD;
         END IF;
         CLOSE CUR_ATENDIMENTOS;
      END IF;

      CLOSE CUR_EXAMES_NEW;
    END LOOP;
  END;

  COMMIT WORK;
END VER_EXAMES;
/
