CREATE OR REPLACE VIEW EQUIP_TEXTOS_PROCEDIMENTOS AS
SELECT NVL(ET.EQUIPAMENTO,0) EQUIPAMENTO, 
       NVL(ET.MNEMONICO,0) MNEMONICO, 
       NVL(ET.POSTO_REA,0) POSTO_REA, 
       NVL(ET.NUMERO,0) NUMERO, 
       NVL(EP.MNEMONICO_EQUIPAMENTO,'') MNEMONICO_EQUIPAMENTO,
       NVL(EP.STATUS,'') STATUS
  FROM EQUIPAMENTOS_TEXTOS ET, EQUIPAMENTOS_PROCEDIMENTOS EP
 WHERE ET.EQUIPAMENTO =  EP.EQUIPAMENTO
   AND ET.MNEMONICO =  EP.MNEMONICO
   AND ET.POSTO_REA =  EP.POSTO_REA;

