-- View: LIS.MEDICOS_WEB

-- DROP VIEW LIS.MEDICOS_WEB;

CREATE VIEW LIS.MEDICOS_WEB
(
  CRM,
  NOME,
  CPF,
  TIPO,
  STATUS,
  CODIGO_CONSELHO,
  TIPO_CR,
  TELEFONE,
  TELEFONE2,
  EMAIL,
  PASS,
  ID_MEDICO,
  DATA_NAS,
  PREFIXO_NOME
)
AS
SELECT "CRM","NOME","CPF","TIPO","STATUS","CODIGO_CONSELHO","TIPO_CR","TELEFONE","TELEFONE2","EMAIL","PASS","ID_MEDICO","DATA_NAS","PREFIXO_NOME"
  FROM MEDICOS;

GRANT SELECT
 ON LIS.MEDICOS_WEB
TO WLIS;
