-- View: LIS.PROCEDIMENTOS_WEB

-- DROP VIEW LIS.PROCEDIMENTOS_WEB;

CREATE VIEW LIS.PROCEDIMENTOS_WEB
(
  MNEMONICO,
  NOME,
  ENTREGA,
  HORA_COLE,
  STATUS,
  SETOR,
  MATERIAL
)
AS
SELECT P.MNEMONICO, P.NOME, P.ENTREGA, P.HORA_COLE, P.STATUS, S.NOME SETOR, M.NOME MATERIAL
  FROM PROCEDIMENTOS P, SETORES S, MATERIAIS M
 WHERE S.SETOR = P.SETOR
   AND M.MATERIAL = P.MATERIAL
ORDER BY MNEMONICO;

GRANT SELECT
 ON LIS.PROCEDIMENTOS_WEB
TO WLIS;
