-- View: LIS.SERVICOS_ADM_WEB

-- DROP VIEW LIS.SERVICOS_ADM_WEB;

CREATE VIEW LIS.SERVICOS_ADM_WEB
(
  MNEMO_SERVICO_ADM,
  NOME,
  LOGO,
  RESULTADOS_WEB,
  CONEXAO_DB,
  PASTA_WEB_PDF,
  PASTA_WEB_XML,
  WEB_PORTA,
  WEB_LAUDO,
  WEB_PREPARO 
)
AS
SELECT MNEMO_SERVICO_ADM, NOME, LOGO, RESULTADOS_WEB, CONEXAO_DB, PASTA_WEB_PDF, PASTA_WEB_XML, WEB_PORTA, WEB_LAUDO, WEB_PREPARO 
  FROM SERVICOS_ADM
  WHERE STATUS = 'A';

GRANT SELECT
 ON LIS.SERVICOS_ADM_WEB
TO WLIS;
