ALTER TABLE CALCULOS_AUX ADD CONSTRAINT CALCULOS_AUX_CALCULOS_FK 
      FOREIGN KEY (MNEMONICO, NUMERO, VARIAVEL_ORIGEM, VALIDACAO, CORREL)
      REFERENCES CALCULOS(MNEMONICO, NUMERO, VARIAVEL, VALIDACAO, CORREL) 
      ON DELETE CASCADE;
