ALTER TABLE EQUIPAMENTOS_VARIAVEIS ADD CONSTRAINT EQUIP_VAR_EQUIP_TEXTOS_FK 
      FOREIGN KEY (EQUIPAMENTO, MNEMONICO, NUMERO) REFERENCES EQUIPAMENTOS_TEXTOS(EQUIPAMENTO, MNEMONICO, NUMERO)
      ON DELETE CASCADE;
