ALTER TABLE EQUIPAMENTOS_VARIAVEIS ADD CONSTRAINT EQUIP_VARIAVEIS_VAR_TEXTOS_FK 
      FOREIGN KEY (MNEMONICO, NUMERO, VARIAVEL) REFERENCES VARIAVEIS_TEXTOS(MNEMONICO, NUMERO, VARIAVEL)
      ON DELETE CASCADE;
