ALTER TABLE ORG_EMPRESAS_CONVENIADAS ADD CONSTRAINT ORG_EMPRESAS_CONVENIADAS_FK 
      FOREIGN KEY (ID_EMPRESA_CONVENIADA) REFERENCES EMPRESAS_CONVENIADAS(ID_EMPRESA_CONVENIADA)
      ON DELETE CASCADE;
