ALTER TABLE VALORES_REFERENCIA ADD CONSTRAINT VREFERENCIA_COND_REFERENCIA_FK 
      FOREIGN KEY (MNEMONICO,NUMERO,CORREL) 
      REFERENCES CONDICOES_REFERENCIA(MNEMONICO,NUMERO,CORREL) 
      ON DELETE CASCADE;
