CREATE TABLE SINALIZACOES_EVOLUCAO
(ID_SINALIZACAO  NUMBER(3)      NOT NULL,
 NOME            VARCHAR2(20)   NOT NULL,
 DESCRICAO       VARCHAR2(50)   NOT NULL,
 TAG_MARCACAO    VARCHAR2(30)   NOT NULL,
 COR_MARCACAO    NUMBER(10)     NOT NULL,
 TIPO_MARCACAO   VARCHAR2(1)    NOT NULL)
TABLESPACE LIS_DATA;