CREATE OR REPLACE FUNCTION GET_SITUACAO_EXAME(V_PENDENCIA           IN VARCHAR2,
                                              V_SITUACAO            IN VARCHAR2,
                                              V_SITUACAO_INTERFACE  IN VARCHAR2) RETURN VARCHAR2 IS RESULT VARCHAR2(15);
BEGIN
   IF V_PENDENCIA = 'S' THEN
 	  RESULT := 'PENDENCIA';
   ELSIF V_SITUACAO IN ('I','L') THEN
 	  RESULT := 'FINALIZADO';
   ELSIF V_SITUACAO = 'R' AND V_SITUACAO_INTERFACE IN ('L','U','D','T') THEN 
 	  RESULT := 'FINALIZADO';
   ELSIF V_SITUACAO = 'R' AND V_SITUACAO_INTERFACE = 'N' THEN 
 	  RESULT := 'AGUARDANDO';
   ELSIF V_SITUACAO_INTERFACE = 'R' AND V_SITUACAO IN ('R','N','U') THEN 
 	  RESULT := 'AGUARDANDO';
   ELSIF V_SITUACAO_INTERFACE IN ('S','E','I','P') THEN 
 	  RESULT := 'ANDAMENTO';
   ELSE 
	  RESULT := 'NAO';
   END IF;
   
   RETURN(RESULT);
END GET_SITUACAO_EXAME;
/

GRANT EXECUTE
 ON GET_SITUACAO_EXAME
TO EXP_CLB;

