CREATE OR REPLACE FUNCTION GET_COUNT_EXAMES_SITUACAO(V_POSTO       IN NUMBER,
                                                     V_ATENDIMENTO IN NUMBER,
                                                     V_SITUACAO    IN VARCHAR2) RETURN NUMBER IS RESULT NUMBER;
BEGIN
  IF V_SITUACAO = 'FINALIZADO' THEN
     SELECT COUNT(1) INTO RESULT FROM EXAMES E
      WHERE E.POSTO = V_POSTO
        AND E.ATENDIMENTO = V_ATENDIMENTO
        AND E.PENDENCIA <> 'S'
        AND E.SITUACAO <> 'C'
        AND E.SITUACAO <> 'F'
        AND E.SITUACAO IN ('R','I','L')
        AND E.SITUACAO_INTERFACE IN ('N','L','U','D','T');

  ELSIF V_SITUACAO = 'ANDAMENTO' THEN
     SELECT COUNT(1) INTO RESULT FROM EXAMES E
      WHERE E.POSTO = V_POSTO
        AND E.ATENDIMENTO = V_ATENDIMENTO
        AND E.PENDENCIA <> 'S'
        AND E.SITUACAO <> 'C'
        AND E.SITUACAO <> 'F'
        AND E.SITUACAO_INTERFACE IN ('S','E','I','P');

  ELSIF V_SITUACAO = 'AGUARDANDO' THEN
     SELECT COUNT(1) INTO RESULT FROM EXAMES E
      WHERE E.POSTO = V_POSTO
        AND E.PENDENCIA <> 'S'
        AND E.ATENDIMENTO = V_ATENDIMENTO
        AND E.SITUACAO <> 'C'
        AND E.SITUACAO <> 'F'
        AND E.SITUACAO IN ('R','N','U')
        AND E.SITUACAO_INTERFACE = 'R';

  ELSIF V_SITUACAO = 'PENDENCIA' THEN
     SELECT COUNT(1) INTO RESULT FROM EXAMES E
      WHERE E.POSTO = V_POSTO
        AND E.ATENDIMENTO = V_ATENDIMENTO
        AND E.SITUACAO <> 'C'
        AND E.SITUACAO <> 'F'
        AND E.PENDENCIA = 'S';

  ELSIF V_SITUACAO = 'NAO' THEN
     SELECT COUNT(1) INTO RESULT FROM EXAMES E
      WHERE E.POSTO = V_POSTO
        AND E.ATENDIMENTO = V_ATENDIMENTO
        AND E.PENDENCIA <> 'S'
        AND E.SITUACAO <> 'C'
        AND E.SITUACAO <> 'F'
        AND E.SITUACAO IN ('N','U')
        AND E.SITUACAO_INTERFACE = 'N';

  ELSIF V_SITUACAO = 'TODOS' THEN
     SELECT COUNT(1) INTO RESULT FROM EXAMES E
      WHERE E.POSTO = V_POSTO
        AND E.ATENDIMENTO = V_ATENDIMENTO
        AND E.SITUACAO <> 'C'
        AND E.SITUACAO <> 'F';

   END IF;
   RETURN(RESULT);
END GET_COUNT_EXAMES_SITUACAO;
/

GRANT EXECUTE
 ON GET_COUNT_EXAMES_SITUACAO
TO EXP_CLB;

