CREATE OR REPLACE FUNCTION GET_MNEMONICOS(V_POSTO       IN NUMBER,
                                          V_ATENDIMENTO IN NUMBER,
										  V_POSTO_REA   IN NUMBER DEFAULT NULL) RETURN VARCHAR2 IS MNEMONICOS VARCHAR2(2000);

    CURSOR CUR_MNEMONICOS IS
      SELECT MNEMONICO FROM EXAMES WHERE POSTO = V_POSTO AND ATENDIMENTO = V_ATENDIMENTO AND (V_POSTO_REA IS NULL OR POSTO_REA = V_POSTO_REA) AND SITUACAO NOT IN ('C','F');

BEGIN

MNEMONICOS := '';

FOR MNEMONICOS_REC in CUR_MNEMONICOS
LOOP
    MNEMONICOS := MNEMONICOS || MNEMONICOS_REC.MNEMONICO || ' ';
END LOOP;

RETURN MNEMONICOS;

END;
/

GRANT EXECUTE
 ON GET_MNEMONICOS
TO EXP_CLB;
