CREATE OR REPLACE FUNCTION GET_SITUACAO_EXAMES(V_POSTO       IN NUMBER,
                                               V_ATENDIMENTO IN NUMBER) RETURN VARCHAR2 IS RESULT VARCHAR2(2);
  QT_FINALIZADOS NUMBER(4);
  QT_PENDENCIA   NUMBER(4);
  QT_TODOS       NUMBER(4);
  QT_NAO         NUMBER(4);

											   
BEGIN
     QT_FINALIZADOS := GET_COUNT_EXAMES_SITUACAO(V_POSTO, V_ATENDIMENTO, 'FINALIZADO');
     QT_PENDENCIA   := GET_COUNT_EXAMES_SITUACAO(V_POSTO, V_ATENDIMENTO, 'PENDENCIA');
     QT_TODOS       := GET_COUNT_EXAMES_SITUACAO(V_POSTO, V_ATENDIMENTO, 'TODOS');
     QT_NAO         := GET_COUNT_EXAMES_SITUACAO(V_POSTO, V_ATENDIMENTO, 'NAO');
	 
	 IF QT_TODOS = 0 then
		RESULT := 'SE';
     ELSIF QT_FINALIZADOS = QT_TODOS then
        RESULT := 'TF';
     ELSIF QT_PENDENCIA > 0 then
          RESULT  := 'EP';
     ELSIF QT_FINALIZADOS > 0 then
        RESULT := 'PF';
     ELSIF QT_NAO= QT_TODOS then
        RESULT := 'NR';
     ELSE  
        RESULT := 'EA';
     END IF;
	 
     RETURN(RESULT);
END GET_SITUACAO_EXAMES;
/

GRANT EXECUTE
 ON GET_SITUACAO_EXAMES
TO EXP_CLB;

