CREATE USER EXP_CDR 
  IDENTIFIED BY "1029384756"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE "DEFAULT"
  ACCOUNT UNLOCK;


/* Granted roles */
GRANT "CONNECT" TO EXP_CDR;

ALTER USER EXP_CDR DEFAULT ROLE ALL;