CREATE OR REPLACE VIEW VEX_AMOSTRAS
(
  POSTO,
  ATENDIMENTO,
  CORREL,
  MNEMONICO,
  AMOSTRA,
  USUARIO,
  USUARIO_COLE,
  DATA_CAD,
  DATA_COLE,
  OBSERVACOES
)
AS
SELECT POSTO, ATENDIMENTO, CORREL, MNEMONICO, AMOSTRA, USUARIO, USUARIO_COLE, DATA_CAD, DATA_COLE, OBSERVACOES
  FROM AMOSTRAS
 ORDER BY POSTO, ATENDIMENTO, CORREL;


GRANT SELECT
 ON VEX_AMOSTRAS
TO EXP_CLB;
