CREATE OR REPLACE VIEW VEX_RESULTADOS
(
  POSTO,
  ATENDIMENTO,
  CORREL,
  NUMERO,
  VARIAVEL,
  VALOR,
  USUARIO_AUTO,
  DATA_AUTO,
  ESTACAO_AUTO
)
AS
SELECT R.POSTO, R.ATENDIMENTO, R.CORREL, R.NUMERO, R.VARIAVEL, R.VALOR, R.USUARIO_AUTO, R.DATA_AUTO, R.ESTACAO_AUTO
  FROM RESULTADOS R
ORDER BY POSTO, ATENDIMENTO, CORREL, NUMERO, VARIAVEL;

GRANT SELECT
 ON VEX_RESULTADOS
TO EXP_CLB;
