CREATE OR REPLACE VIEW VEX_EXAMES
(
  POSTO,
  ATENDIMENTO,
  CORREL,
  MNEMONICO,
  SITUACAO,
  SITUACAO_INTERFACE,
  PENDENCIA,
  DATA_COLE,
  REALIZANTE1,
  REALIZANTE2,
  POSTO_REALIZANTE,
  DATA_ENTREGA,
  DATA_REA1,
  DATA_REA2,
  TIPO_COLETA,
  USUARIO,
  OBSERVACOES,
  NOME_PROCEDIMENTO,
  TIPO_ENTREGA,
  NOME_REALIZANTE1,
  NOME_REALIZANTE2,
  NOME_POSTO_REALIZANTE,
  TIPO_POSTO_REALIZANTE,
  SITUACAO_EXPERIENCE,
  AMOSTRA
)
AS
SELECT E.POSTO, E.ATENDIMENTO, E.CORREL, E.MNEMONICO, E.SITUACAO, E.SITUACAO_INTERFACE, E.PENDENCIA,
       E.DATA_COLE, E.MED_REA1, E.MED_REA2, E.POSTO_REA, E.DATA_ENT, E.DATA_REA1, E.DATA_REA2, E.TIPO_COLETA, E.USUARIO, E.OBSERVACOES, 
       P.NOME, P.TIPO_ENTREGA, M1.NOME, M2.NOME, PO.NOME, PO.TIPO_POSTO, GET_SITUACAO_EXAME(PENDENCIA, SITUACAO, SITUACAO_INTERFACE), GET_AMOSTRA(E.POSTO, E.ATENDIMENTO, E.CORREL) 
  FROM EXAMES E, PROCEDIMENTOS P, MEDICOS M1, MEDICOS M2, POSTOS PO
 WHERE E.SITUACAO <> 'F'
   AND E.SITUACAO <> 'C'
   AND P.MNEMONICO(+) = E.MNEMONICO
   AND M1.CRM(+) = E.MED_REA1
   AND M2.CRM(+) = E.MED_REA2
   AND PO.POSTO = E.POSTO_REA
ORDER BY POSTO, ATENDIMENTO, CORREL;

GRANT SELECT
 ON VEX_EXAMES
TO EXP_CLB;
