CREATE OR REPLACE VIEW VEX_PROCEDIMENTOS
(
  MNEMONICO,
  NOME,
  PRAZO_ENTREGA,
  HORA_COLE,
  STATUS,
  TIPO_ENTREGA,
  TIPO_COLETA,
  SETOR,
  NOME_SETOR,
  MATERIAL,
  NOME_MATERIAL
)
AS
SELECT P.MNEMONICO, P.NOME, P.ENTREGA, P.HORA_COLE, P.STATUS, P.TIPO_ENTREGA, P.TIPO_COLETA, P.SETOR, S.NOME NOME_SETOR, P.MATERIAL, M.NOME NOME_MATERIAL
  FROM PROCEDIMENTOS P, SETORES S, MATERIAIS M
 WHERE S.SETOR = P.SETOR
   AND M.MATERIAL = P.MATERIAL
ORDER BY MNEMONICO;

GRANT SELECT
 ON VEX_PROCEDIMENTOS
TO EXP_CLB;