ALTER TABLE CONTR_PROCEDIMENTOS_INTERFACES ADD CONSTRAINT CONT_PROCE_INTER_AUTOMACAO_FK 
    FOREIGN KEY (ID_PROCEDIMENTO_AUTOMACAO) REFERENCES EQUIPAMENTOS_TEXTOS(ID_EQUIPAMENTO_TEXTO)
    ON DELETE CASCADE;