ALTER TABLE CONTR_PROCEDIMENTOS_INTERFACES ADD CONSTRAINT CONTROLES_PROCEDIMENTOS_FK
    FOREIGN KEY (ID_CONTROLE_PROCEDIMENTO) REFERENCES CONTROLES_PROCEDIMENTOS(ID_CONTROLE_PROCEDIMENTO)
    ON DELETE CASCADE;