-- select retorno
SELECT 'ALTER TABLE ' || TABLE_NAME || ' ALLOCATE EXTENT;'
  FROM USER_TABLES
 ORDER BY TABLE_NAME
-- fim bloco

-- select retorno
SELECT 'ALTER TABLE ' || 'LIS.' || TABLE_NAME || ' ENABLE CONSTRAINT ' || CONSTRAINT_NAME
FROM user_constraints WHERE CONSTRAINT_TYPE = 'R'
-- fim bloco

-- select retorno
SELECT constraint_name
FROM user_constraints WHERE CONSTRAINT_TYPE = 'R' AND VALIDATED = 'NOT VALIDATED'
-- fim bloco

