-- PKs das tabelas do modulo Atendimento..
@%LIS_HOME%\pks\amostras_pk.sql
@%LIS_HOME%\pks\atendimentos_pk.sql
@%LIS_HOME%\pks\complemento_atendimentos_pk.sql
@%LIS_HOME%\pks\caixa_pk.sql
@%LIS_HOME%\pks\calculos_aux_pk.sql
@%LIS_HOME%\pks\calculos_pk.sql
@%LIS_HOME%\pks\clientes_pk.sql
@%LIS_HOME%\pks\clientes_pass_pk.sql
@%LIS_HOME%\pks\clientes_b2b_pk.sql
@%LIS_HOME%\pks\complemento_clientes_pk.sql
@%LIS_HOME%\pks\conferencia_guias_pk.sql
@%LIS_HOME%\pks\condicoes_referencia_pk.sql
@%LIS_HOME%\pks\contas_atendimentos_pk.sql
@%LIS_HOME%\pks\cobranca_atendimentos_pk.sql
@%LIS_HOME%\pks\correcao_guias_atendimentos_pk.sql
@%LIS_HOME%\pks\devedores_pk.sql
@%LIS_HOME%\pks\exames_pk.sql
@%LIS_HOME%\pks\exames_autorizacoes_pk.sql
@%LIS_HOME%\pks\exames_b2b_pk.sql
@%LIS_HOME%\pks\exames_tempos_coleta_pk.sql
@%LIS_HOME%\pks\frases_pk.sql
@%LIS_HOME%\pks\procedimentos_frases_pk.sql
@%LIS_HOME%\pks\procedimentos_notas_pk.sql
@%LIS_HOME%\pks\pendencias_pk.sql
@%LIS_HOME%\pks\resultados_atual_pk.sql
@%LIS_HOME%\pks\resultados_historico_pk.sql
@%LIS_HOME%\pks\resultados_textos_pk.sql
@%LIS_HOME%\pks\resultados_digitalizados_pk.sql
@%LIS_HOME%\pks\resultados_streams_pk.sql
@%LIS_HOME%\pks\textos_pk.sql
@%LIS_HOME%\pks\validacoes_pk.sql
@%LIS_HOME%\pks\valores_referencia_pk.sql
@%LIS_HOME%\pks\variaveies_pk.sql
@%LIS_HOME%\pks\rastros_amostras_pk.sql
@%LIS_HOME%\pks\centros_rastreo_pk.sql
@%LIS_HOME%\pks\transacoes_tes_pk.sql
@%LIS_HOME%\pks\layouts_pk.sql

