ALTER TABLE EXAMES_TEMPOS_COLETA ADD CONSTRAINT EXAMES_TEMPOS_COLETA_PK 
      PRIMARY KEY (POSTO, ATENDIMENTO, CORREL, AMOSTRA, ID_TEMPO_COLETA)
   USING INDEX
          TABLESPACE CDR_PEN_AMO_INDX
            STORAGE (INITIAL 256K);