CREATE OR REPLACE PROCEDURE PRC_CONTROLES(V_ID_CONTROLE IN OUT CONTROLES.ID_CONTROLE%TYPE,
                                          V_DESCRICAO   IN CONTROLES.DESCRICAO%TYPE,  
                                          V_NIVEL       IN CONTROLES.NIVEL%TYPE,
                                          V_STATUS      IN CONTROLES.STATUS%TYPE,
                                          V_FUNCAO      IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_CONTROLES.NEXTVAL INTO V_ID_CONTROLE FROM DUAL;
	 
     INSERT INTO CONTROLES VALUES (V_ID_CONTROLE, V_DESCRICAO, V_NIVEL, V_STATUS);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONTROLES SET DESCRICAO = V_DESCRICAO, NIVEL = V_NIVEL, STATUS = V_STATUS
                      WHERE ID_CONTROLE = V_ID_CONTROLE;	
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE CONTROLES WHERE ID_CONTROLE = V_ID_CONTROLE;

  END IF;

  COMMIT WORK;

END PRC_CONTROLES;
