CREATE OR REPLACE PROCEDURE PRC_EQUIP_CONTROL_LOTES(V_ID_CONTROLE_LOTE       IN EQUIPAMENTOS_CONTROLES_LOTES.ID_CONTROLE_LOTE%TYPE,
                                                    V_ID_EQUIPAMENTO         IN EQUIPAMENTOS_CONTROLES_LOTES.ID_EQUIPAMENTO%TYPE,  
                                                    V_POSTO_REA              IN EQUIPAMENTOS_CONTROLES_LOTES.POSTO_REA%TYPE,
                                                    V_DATA_ATIVACAO          IN EQUIPAMENTOS_CONTROLES_LOTES.DATA_ATIVACAO%TYPE,
                                                    V_DATA_CANCELAMENTO      IN EQUIPAMENTOS_CONTROLES_LOTES.DATA_CANCELAMENTO%TYPE,
                                                    V_USUARIO_ATIVACAO       IN EQUIPAMENTOS_CONTROLES_LOTES.USUARIO_ATIVACAO%TYPE,
                                                    V_USUARIO_CANCELAMENTO   IN EQUIPAMENTOS_CONTROLES_LOTES.USUARIO_CANCELAMENTO%TYPE,
                                                    V_STATUS                 IN EQUIPAMENTOS_CONTROLES_LOTES.STATUS%TYPE,
                                                    V_ID_MOTIVO_CANCELAMENTO IN EQUIPAMENTOS_CONTROLES_LOTES.ID_MOTIVO_CANCELAMENTO%TYPE,
                                                    V_FUNCAO                 IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
     INSERT INTO EQUIPAMENTOS_CONTROLES_LOTES VALUES (V_ID_CONTROLE_LOTE, V_ID_EQUIPAMENTO, V_POSTO_REA, V_DATA_ATIVACAO,
                                                      V_DATA_CANCELAMENTO, V_USUARIO_ATIVACAO, V_USUARIO_CANCELAMENTO, V_STATUS,
                                                      V_ID_MOTIVO_CANCELAMENTO);           
 
  ELSIF V_FUNCAO = 3 THEN
     DELETE EQUIPAMENTOS_CONTROLES_LOTES WHERE ID_CONTROLE_LOTE = V_ID_CONTROLE_LOTE AND ID_EQUIPAMENTO = V_ID_EQUIPAMENTO
                                               AND POSTO_REA = V_POSTO_REA; 

  ELSIF V_FUNCAO = 4 THEN
     UPDATE EQUIPAMENTOS_CONTROLES_LOTES SET DATA_ATIVACAO = V_DATA_ATIVACAO, DATA_CANCELAMENTO = V_DATA_CANCELAMENTO, 
                                             USUARIO_ATIVACAO = V_USUARIO_ATIVACAO, USUARIO_CANCELAMENTO = V_USUARIO_CANCELAMENTO,
                                             ID_MOTIVO_CANCELAMENTO = V_ID_MOTIVO_CANCELAMENTO, STATUS = V_STATUS 
                                         WHERE ID_CONTROLE_LOTE = V_ID_CONTROLE_LOTE AND ID_EQUIPAMENTO = V_ID_EQUIPAMENTO
                                               AND POSTO_REA = V_POSTO_REA;

  ELSIF V_FUNCAO = 5 THEN
     UPDATE EQUIPAMENTOS_CONTROLES_LOTES SET DATA_CANCELAMENTO = V_DATA_CANCELAMENTO, USUARIO_CANCELAMENTO = V_USUARIO_CANCELAMENTO,
                                             ID_MOTIVO_CANCELAMENTO = V_ID_MOTIVO_CANCELAMENTO, STATUS = V_STATUS 
                                         WHERE ID_CONTROLE_LOTE = V_ID_CONTROLE_LOTE AND ID_EQUIPAMENTO = V_ID_EQUIPAMENTO
                                               AND POSTO_REA = V_POSTO_REA;

  END IF;

  COMMIT WORK;

END PRC_EQUIP_CONTROL_LOTES;