CREATE OR REPLACE PROCEDURE PRC_CONTR_PROCEDIM_INTERFACES(V_ID_CONT_PROCEDIM_INTERFACE  IN OUT CONTR_PROCEDIMENTOS_INTERFACES.ID_CONT_PROCEDIMENTO_INTERFACE%TYPE,
                                                          V_ID_CONTROLE_PROCEDIMENTO    IN     CONTR_PROCEDIMENTOS_INTERFACES.ID_CONTROLE_PROCEDIMENTO%TYPE,  
                                                          V_ID_PROCEDIMENTO_AUTOMACAO   IN     CONTR_PROCEDIMENTOS_INTERFACES.ID_PROCEDIMENTO_AUTOMACAO%TYPE,
                                                          V_ID_PROCEDIMENTO_INTEGRACAO  IN     CONTR_PROCEDIMENTOS_INTERFACES.ID_PROCEDIMENTO_INTEGRACAO%TYPE,
                                                          V_FUNCAO                      IN NUMBER) IS      
BEGIN 
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_CONTR_PROCEDIMEN_INTERFACES.NEXTVAL INTO V_ID_CONT_PROCEDIM_INTERFACE FROM DUAL;
	 
     INSERT INTO CONTR_PROCEDIMENTOS_INTERFACES VALUES (V_ID_CONT_PROCEDIM_INTERFACE, 
                                                        V_ID_CONTROLE_PROCEDIMENTO,
                                                        V_ID_PROCEDIMENTO_AUTOMACAO,
                                                        V_ID_PROCEDIMENTO_INTEGRACAO);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONTR_PROCEDIMENTOS_INTERFACES SET ID_CONTROLE_PROCEDIMENTO = V_ID_CONTROLE_PROCEDIMENTO, 
                                               ID_PROCEDIMENTO_AUTOMACAO = V_ID_PROCEDIMENTO_AUTOMACAO,
                                               ID_PROCEDIMENTO_INTEGRACAO = V_ID_PROCEDIMENTO_INTEGRACAO
                                           WHERE ID_CONT_PROCEDIMENTO_INTERFACE = V_ID_CONT_PROCEDIM_INTERFACE;	
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE CONTR_PROCEDIMENTOS_INTERFACES WHERE ID_CONT_PROCEDIMENTO_INTERFACE = V_ID_CONT_PROCEDIM_INTERFACE;

  END IF;

  COMMIT WORK;

END PRC_CONTR_PROCEDIM_INTERFACES;
/