CREATE OR REPLACE PROCEDURE PRC_FORMAS_PAGAMENTOS(V_ID_FORMA_PAGAMENTO  IN OUT FORMAS_PAGAMENTOS.ID_FORMA_PAGAMENTO%TYPE,
                                                  V_ALIAS               IN FORMAS_PAGAMENTOS.ALIAS%TYPE,
                                                  V_NOME                IN FORMAS_PAGAMENTOS.NOME%TYPE,
                                                  V_STATUS              IN FORMAS_PAGAMENTOS.STATUS%TYPE,
                                                  V_PARCELAMENTO        IN FORMAS_PAGAMENTOS.PARCELAMENTO%TYPE, 
                                                  V_FUNCAO              IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_FORMAS_PAGAMENTOS.NEXTVAL INTO V_ID_FORMA_PAGAMENTO FROM DUAL;
	 
     INSERT INTO FORMAS_PAGAMENTOS VALUES (V_ID_FORMA_PAGAMENTO, V_ALIAS, V_NOME, V_STATUS, V_PARCELAMENTO);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE FORMAS_PAGAMENTOS SET ALIAS = V_ALIAS, NOME = V_NOME, STATUS = V_STATUS, PARCELAMENTO = V_PARCELAMENTO
                      WHERE ID_FORMA_PAGAMENTO = V_ID_FORMA_PAGAMENTO;	
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE FORMAS_PAGAMENTOS WHERE ID_FORMA_PAGAMENTO = V_ID_FORMA_PAGAMENTO;

  END IF;

  COMMIT WORK;

END PRC_FORMAS_PAGAMENTOS;