CREATE OR REPLACE PROCEDURE PRC_MAP_CONTROLES_VARIAVEIS_INTERFACES(V_ID_CONTROLE_VARIAVEL_INTERFACE       IN OUT MAP_CONTROLES_VARIAVEIS_INTERFACES.ID_CONTROLE_VARIAVEL_INTERFACE%TYPE,
                                                                       V_ID_CONTROLE_PROCEDIMENTO         IN     MAP_CONTROLES_VARIAVEIS_INTERFACES.ID_CONTROLE_PROCEDIMENTO%TYPE,  
                                                                       V_ID_MAP_VARIAVEL_AUTOMACAO        IN     MAP_CONTROLES_VARIAVEIS_INTERFACES.ID_MAP_VARIAVEL_AUTOMACAO%TYPE,
                                                                       V_ID_MAP_VARIAVEL_INTEGRACAO       IN     MAP_CONTROLES_VARIAVEIS_INTERFACES.ID_MAP_VARIAVEL_INTEGRACAO%TYPE,
                                                                       V_FUNCAO      IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_MAP_CONTROLES_VARIAVEIS_INTERFACES.NEXTVAL INTO V_ID_CONTROLE_VARIAVEL_INTERFACE FROM DUAL;
	 
     INSERT INTO MAP_CONTROLES_VARIAVEIS_INTERFACES VALUES (V_ID_CONTROLE_VARIAVEL_INTERFACE, 
                                                                V_ID_CONTROLE_PROCEDIMENTO,
                                                                V_ID_MAP_VARIAVEL_AUTOMACAO,
                                                                V_ID_MAP_VARIAVEL_INTEGRACAO);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE MAP_CONTROLES_VARIAVEIS_INTERFACES SET ID_CONTROLE_VARIAVEL_INTERFACE = V_ID_CONTROLE_PROCEDIMENTO, 
                                                       ID_MAP_VARIAVEL_AUTOMACAO = V_ID_MAP_VARIAVEL_AUTOMACAO,
                                                       ID_MAP_VARIAVEL_INTEGRACAO = V_ID_MAP_VARIAVEL_INTEGRACAO
                                                   WHERE ID_CONTROLE_VARIAVEL_INTERFACE = V_ID_CONTROLE_VARIAVEL_INTERFACE;	
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE MAP_CONTROLES_VARIAVEIS_INTERFACES WHERE ID_CONTROLE_VARIAVEL_INTERFACE = V_ID_CONTROLE_VARIAVEL_INTERFACE;

  END IF;

  COMMIT WORK;

END PRC_MAP_CONTROLES_VARIAVEIS_INTERFACES;
/
