CREATE OR REPLACE PROCEDURE PRC_MAP_EQUIPAMENTOS_FORM_PAG(V_EQUIPAMENTO         IN MAP_EQUIPAMENTOS_FORMAS_PAG.EQUIPAMENTO%TYPE,
                                                          V_ID_FORMA_PAGAMENTO  IN MAP_EQUIPAMENTOS_FORMAS_PAG.ID_FORMA_PAGAMENTO%TYPE,
                                                          V_MAP_FORMA_PAGAMENTO IN MAP_EQUIPAMENTOS_FORMAS_PAG.MAP_FORMA_PAGAMENTO%TYPE,
                                                          V_FUNCAO              IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
    INSERT INTO MAP_EQUIPAMENTOS_FORMAS_PAG VALUES (V_EQUIPAMENTO, V_ID_FORMA_PAGAMENTO, V_MAP_FORMA_PAGAMENTO);           
  
  ELSIF V_FUNCAO = 2 THEN
    DELETE MAP_EQUIPAMENTOS_FORMAS_PAG WHERE EQUIPAMENTO = V_EQUIPAMENTO AND ID_FORMA_PAGAMENTO = V_ID_FORMA_PAGAMENTO;

  END IF;

  COMMIT WORK;

END PRC_MAP_EQUIPAMENTOS_FORM_PAG;
/