CREATE OR REPLACE PROCEDURE PRC_BANDEIRAS_OPERADORAS(V_ID_BANDEIRA  IN OUT BANDEIRAS_OPERADORAS.ID_BANDEIRA%TYPE,
                                                     V_ID_OPERADORA IN BANDEIRAS_OPERADORAS.ID_OPERADORA%TYPE,
                                                     V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
    INSERT INTO BANDEIRAS_OPERADORAS VALUES (V_ID_BANDEIRA, V_ID_OPERADORA);           
  
  ELSIF V_FUNCAO = 2 THEN
    DELETE BANDEIRAS_OPERADORAS WHERE ID_BANDEIRA = V_ID_BANDEIRA AND ID_OPERADORA = V_ID_OPERADORA;

  END IF;

  COMMIT WORK;

END PRC_BANDEIRAS_OPERADORAS;