CREATE OR REPLACE PROCEDURE PRC_MAP_EQUIPAMENTOS_OPERADORA(V_EQUIPAMENTO  IN MAP_EQUIPAMENTOS_OPERADORAS.EQUIPAMENTO%TYPE,
                                                           V_ID_OPERADORA  IN MAP_EQUIPAMENTOS_OPERADORAS.ID_OPERADORA%TYPE,
                                                           V_MAP_OPERADORA IN MAP_EQUIPAMENTOS_OPERADORAS.MAP_OPERADORA%TYPE,
                                                           V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
    INSERT INTO MAP_EQUIPAMENTOS_OPERADORAS VALUES (V_EQUIPAMENTO, V_ID_OPERADORA, V_MAP_OPERADORA);           
  
  ELSIF V_FUNCAO = 2 THEN
    DELETE MAP_EQUIPAMENTOS_OPERADORAS WHERE EQUIPAMENTO = V_EQUIPAMENTO AND ID_OPERADORA = V_ID_OPERADORA;

  END IF;

  COMMIT WORK;

END PRC_MAP_EQUIPAMENTOS_OPERADORA;
/