CREATE OR REPLACE PROCEDURE PRC_OPERADORAS( V_ID_OPERADORA IN OUT OPERADORAS.ID_OPERADORA%TYPE,
                                            V_NOME         IN OPERADORAS.NOME%TYPE,
                                            V_STATUS       IN OPERADORAS.STATUS%TYPE,
                                            V_PADRAO       IN OPERADORAS.PADRAO%TYPE,
                                            V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	  SELECT SQ_OPERADORAS.NEXTVAL INTO V_ID_OPERADORA FROM DUAL;
	 
    INSERT INTO OPERADORAS VALUES (V_ID_OPERADORA, V_NOME, V_STATUS, V_PADRAO);           
  
  ELSIF V_FUNCAO = 2 THEN
    UPDATE OPERADORAS SET NOME = V_NOME, STATUS = V_STATUS, PADRAO = V_PADRAO
                      WHERE ID_OPERADORA = V_ID_OPERADORA;	
  
  ELSIF V_FUNCAO = 3 THEN
    DELETE OPERADORAS WHERE ID_OPERADORA = V_ID_OPERADORA;

  ELSIF V_FUNCAO = 4 THEN
    UPDATE OPERADORAS SET PADRAO = 'N' WHERE PADRAO = 'S';

    UPDATE OPERADORAS SET PADRAO = V_PADRAO WHERE ID_OPERADORA = V_ID_OPERADORA;

  END IF;

  COMMIT WORK;

END PRC_OPERADORAS;