CREATE OR REPLACE PROCEDURE PRC_OPERADORAS( V_ID_OPERADORA IN OUT OPERADORAS.ID_OPERADORA%TYPE,
                                            V_NOME         IN OPERADORAS.NOME%TYPE,
                                            V_STATUS       IN OPERADORAS.STATUS%TYPE,
                                            V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	  SELECT SQ_OPERADORAS.NEXTVAL INTO V_ID_OPERADORA FROM DUAL;
	 
    INSERT INTO OPERADORAS VALUES (V_ID_OPERADORA, V_NOME, V_STATUS);           
  
  ELSIF V_FUNCAO = 2 THEN
    UPDATE OPERADORAS SET NOME = V_NOME, STATUS = V_STATUS
                      WHERE V_ID_OPERADORA = V_ID_OPERADORA;	
  
  ELSIF V_FUNCAO = 3 THEN
    DELETE OPERADORAS WHERE V_ID_OPERADORA = V_ID_OPERADORA;

  END IF;

  COMMIT WORK;

END PRC_OPERADORAS;
/