CREATE OR REPLACE PROCEDURE PRC_FORMAS_PAG_OPERADORAS(V_ID_FORMA_PAGAMENTO IN FORMAS_PAGAMENTOS_OPERADORAS.ID_FORMA_PAGAMENTO%TYPE,
                                                      V_ID_OPERADORA IN FORMAS_PAGAMENTOS_OPERADORAS.ID_OPERADORA%TYPE,
                                                      V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN

  INSERT INTO FORMAS_PAGAMENTOS_OPERADORAS VALUES (V_ID_FORMA_PAGAMENTO, V_ID_OPERADORA);           
  
  ELSIF V_FUNCAO = 2 THEN
    DELETE FORMAS_PAGAMENTOS_OPERADORAS WHERE ID_FORMA_PAGAMENTO = V_ID_FORMA_PAGAMENTO AND ID_OPERADORA = V_ID_OPERADORA;

  END IF;

  COMMIT WORK;

END PRC_FORMAS_PAG_OPERADORAS;