CREATE OR REPLACE PROCEDURE PRC_CONTROLES_PROCEDIMENTOS(V_ID_CONTROLE_PROCEDIMENTO   IN OUT CONTROLES_PROCEDIMENTOS.ID_CONTROLE_PROCEDIMENTO%TYPE,
                                                        V_ID_CONTROLE                IN CONTROLES_PROCEDIMENTOS.ID_CONTROLE%TYPE, 
                                                        MNEMONICO                    IN CONTROLES_PROCEDIMENTOS.MNEMONICO%TYPE,
                                                        V_FUNCAO                     IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_CONTROLES_PROCEDIMENTOS.NEXTVAL INTO V_ID_CONTROLE_PROCEDIMENTO FROM DUAL;
	 
     INSERT INTO CONTROLES_PROCEDIMENTOS VALUES (V_ID_CONTROLE_PROCEDIMENTO, V_ID_CONTROLE, MNEMONICO);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONTROLES_PROCEDIMENTOS SET ID_CONTROLE = V_ID_CONTROLE, MNEMONICO = MNEMONICO
                                    WHERE ID_CONTROLE_PROCEDIMENTO = V_ID_CONTROLE_PROCEDIMENTO;	
  ELSIF V_FUNCAO = 3 THEN
     DELETE CONTROLES_PROCEDIMENTOS WHERE ID_CONTROLE_PROCEDIMENTO = V_ID_CONTROLE_PROCEDIMENTO;

  END IF;

  COMMIT WORK;

END PRC_CONTROLES_PROCEDIMENTOS;
/