CREATE OR REPLACE PROCEDURE PRC_BANDEIRAS(V_ID_BANDEIRA  IN OUT BANDEIRAS.ID_BANDEIRA%TYPE,
                                          V_NOME      IN BANDEIRAS.NOME%TYPE,
                                          V_STATUS     IN BANDEIRAS.STATUS%TYPE,
                                          V_FUNCAO    IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	  SELECT SQ_BANDEIRAS.NEXTVAL INTO V_ID_BANDEIRA FROM DUAL;
	 
    INSERT INTO BANDEIRAS VALUES (V_ID_BANDEIRA, V_NOME, V_STATUS);           
  
  ELSIF V_FUNCAO = 2 THEN
    UPDATE BANDEIRAS SET NOME = V_NOME, STATUS = V_STATUS
                      WHERE ID_BANDEIRA = V_ID_BANDEIRA;	
  
  ELSIF V_FUNCAO = 3 THEN
    DELETE BANDEIRAS WHERE ID_BANDEIRA = V_ID_BANDEIRA;

  END IF;

  COMMIT WORK;

END PRC_BANDEIRAS;
/