CREATE OR REPLACE PROCEDURE PRC_CONTROLES_CORRIDAS(V_ID_CONTROLE_CORRIDA IN OUT CONTROLES_CORRIDAS.ID_CONTROLE_CORRIDA%TYPE,
                                          V_ID_CONTROLE   IN CONTROLES_CORRIDAS.ID_CONTROLE%TYPE,  
                                          V_EQUIPAMENTO       IN CONTROLES_CORRIDAS.EQUIPAMENTO%TYPE,
                                          V_RESULTADO   IN CONTROLES.RESULTADO%TYPE,
                                          V_DATA_HORA   IN CONTROLES.DATA_HORA%TYPE,
                                          V_VERSAO      IN CONTROLES.VERSAO%TYPE,
                                          V_FUNCAO      IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_CONTROLES_CORRIDAS.NEXTVAL INTO V_ID_CONTROLE_CORRIDA FROM DUAL;
	 
     INSERT INTO CONTROLES_CORRIDAS VALUES (V_ID_CONTROLE_CORRIDA, V_ID_CONTROLE, V_EQUIPAMENTO, V_RESULTADO, V_DATA_HORA, V_VERSAO);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONTROLES_CORRIDAS SET ID_CONTROLE = V_ID_CONTROLE, EQUIPAMENTO = V_EQUIPAMENTO, RESULTADO = V_RESULTADO,
                          DATA_HORA = V_DATA_HORA, VERSAO = V_VERSAO
                      WHERE ID_CONTROLE = V_ID_CONTROLE;	
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE CONTROLES_CORRIDAS WHERE ID_CONTROLE_CORRIDA = V_ID_CONTROLE_CORRIDA;

  END IF;

  COMMIT WORK;

END PRC_CONTROLES_CORRIDAS;