create or replace PROCEDURE PRC_EQUIPAMENTOS_VARIAVEIS(V_ID_EQUIPAMENTO_VARIAVEL    IN OUT EQUIPAMENTOS_VARIAVEIS.ID_EQUIPAMENTO_VARIAVEL%TYPE,
                                                       V_EQUIPAMENTO                IN EQUIPAMENTOS_VARIAVEIS.EQUIPAMENTO%TYPE,
                                                       V_MNEMONICO                  IN EQUIPAMENTOS_VARIAVEIS.MNEMONICO%TYPE,
                                                       V_NUMERO                     IN EQUIPAMENTOS_VARIAVEIS.NUMERO%TYPE,
                                                       V_VARIAVEL                   IN EQUIPAMENTOS_VARIAVEIS.VARIAVEL%TYPE,
                                                       V_VARIAVEL_EQUIPAMENTO       IN EQUIPAMENTOS_VARIAVEIS.VARIAVEL_EQUIPAMENTO%TYPE,
                                                       V_POSTO_REA                  IN EQUIPAMENTOS_VARIAVEIS.POSTO_REA%TYPE,
                                                       V_FUNCAO                     IN  NUMBER) IS
BEGIN
  IF V_FUNCAO = 1 THEN
    SELECT SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL INTO V_ID_EQUIPAMENTO_VARIAVEL FROM DUAL;

     INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES (V_EQUIPAMENTO, V_MNEMONICO, V_NUMERO,
                                                V_VARIAVEL, V_VARIAVEL_EQUIPAMENTO,
                                                V_POSTO_REA, V_ID_EQUIPAMENTO_VARIAVEL);

  ELSIF V_FUNCAO = 2 THEN
     UPDATE EQUIPAMENTOS_VARIAVEIS SET VARIAVEL_EQUIPAMENTO = V_VARIAVEL_EQUIPAMENTO
            WHERE EQUIPAMENTO = V_EQUIPAMENTO AND MNEMONICO = V_MNEMONICO AND POSTO_REA = V_POSTO_REA
              AND NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  ELSIF V_FUNCAO = 3 THEN
     DELETE EQUIPAMENTOS_VARIAVEIS
            WHERE EQUIPAMENTO = V_EQUIPAMENTO AND MNEMONICO = V_MNEMONICO AND POSTO_REA = V_POSTO_REA
              AND NUMERO = V_NUMERO AND VARIAVEL = V_VARIAVEL;

  END IF;

  COMMIT WORK;

END PRC_EQUIPAMENTOS_VARIAVEIS;