CREATE OR REPLACE PROCEDURE PRC_MAP_EQUIPAMENTOS_BANDEIRAS(V_EQUIPAMENTO  IN MAP_EQUIPAMENTOS_BANDEIRAS.EQUIPAMENTO%TYPE,
                                                           V_ID_BANDEIRA  IN MAP_EQUIPAMENTOS_BANDEIRAS.ID_BANDEIRA%TYPE,
                                                           V_MAP_BANDEIRA IN MAP_EQUIPAMENTOS_BANDEIRAS.MAP_BANDEIRA%TYPE,
                                                           V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
    INSERT INTO MAP_EQUIPAMENTOS_BANDEIRAS VALUES (V_EQUIPAMENTO, V_ID_BANDEIRA, V_MAP_BANDEIRA);           
  
  ELSIF V_FUNCAO = 2 THEN
    DELETE MAP_EQUIPAMENTOS_BANDEIRAS WHERE EQUIPAMENTO = V_EQUIPAMENTO AND ID_BANDEIRA = V_ID_BANDEIRA;

  END IF;

  COMMIT WORK;

END PRC_MAP_EQUIPAMENTOS_BANDEIRAS;