CREATE OR REPLACE PROCEDURE PRC_TRANSACOES_INTEGRACOES(V_ID_TRANSACAO_INTEGRACAO IN OUT TRANSACOES_INTEGRACOES.ID_TRANSACAO_INTEGRACAO%TYPE,
                                            V_ID_INTEGRACAO         IN TRANSACOES_INTEGRACOES.ID_INTEGRACAO%TYPE,
                                            V_DATA_TRANSACAO       IN TRANSACOES_INTEGRACOES.DATA_TRANSACAO%TYPE,
                                            V_STATUS_TRANSACAO       IN TRANSACOES_INTEGRACOES.STATUS_TRANSACAO%TYPE,
                                            V_TRANSACAO       IN TRANSACOES_INTEGRACOES.TRANSACAO%TYPE,
                                            V_ESTACAO_TRANSACAO       IN TRANSACOES_INTEGRACOES.ESTACAO_TRANSACAO%TYPE,
                                            V_TIPO_INTEGRACAO       IN TRANSACOES_INTEGRACOES.TIPO_INTEGRACAO%TYPE,
                                            V_FUNCAO       IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	  SELECT SQ_TRANSACOES_INTEGRACOES.NEXTVAL INTO V_ID_TRANSACAO_INTEGRACAO FROM DUAL;
	 
    INSERT INTO TRANSACOES_INTEGRACOES VALUES (V_ID_TRANSACAO_INTEGRACAO, V_ID_INTEGRACAO, V_DATA_TRANSACAO, 
                                               V_STATUS_TRANSACAO, V_TRANSACAO, V_ESTACAO_TRANSACAO, V_TIPO_INTEGRACAO);           
  
  ELSIF V_FUNCAO = 2 THEN
    UPDATE TRANSACOES_INTEGRACOES SET ID_INTEGRACAO = V_ID_INTEGRACAO, DATA_TRANSACAO = V_DATA_TRANSACAO, 
                                      STATUS_TRANSACAO = V_STATUS_TRANSACAO, TRANSACAO = V_TRANSACAO, ESTACAO_TRANSACAO = V_ESTACAO_TRANSACAO,
                                      V_TIPO_INTEGRACAO = TIPO_INTEGRACAO
                                  WHERE ID_TRANSACAO_INTEGRACAO = V_ID_TRANSACAO_INTEGRACAO;	
  
  ELSIF V_FUNCAO = 3 THEN
    DELETE TRANSACOES_INTEGRACOES WHERE ID_TRANSACAO_INTEGRACAO = V_ID_TRANSACAO_INTEGRACAO;

  END IF;

  COMMIT WORK;

END PRC_TRANSACOES_INTEGRACOES;