CREATE OR REPLACE PROCEDURE PRC_CONTROLES_LOTES(V_ID_CONTROLE_LOTE IN OUT CONTROLES_LOTES.ID_CONTROLE_LOTE%TYPE,
                                          V_ID_CONTROLE   IN CONTROLES_LOTES.ID_CONTROLE%TYPE,  
                                          V_LOTE       IN CONTROLES_LOTES.LOTE%TYPE,
                                          V_VALIDADE      IN CONTROLES_LOTES.VALIDADE%TYPE,
                                          V_FUNCAO      IN NUMBER) IS      
BEGIN
  IF V_FUNCAO = 1 THEN
	 SELECT SQ_CONTROLES_LOTES.NEXTVAL INTO V_ID_CONTROLE_LOTE FROM DUAL;
	 
     INSERT INTO CONTROLES_LOTES VALUES (V_ID_CONTROLE_LOTE, V_ID_CONTROLE, V_LOTE, V_VALIDADE);           
  
  ELSIF V_FUNCAO = 2 THEN
     UPDATE CONTROLES_LOTES SET ID_CONTROLE = V_ID_CONTROLE, LOTE = V_LOTE, VALIDADE = V_VALIDADE
                      WHERE ID_CONTROLE_LOTE = V_ID_CONTROLE_LOTE;	
  
  ELSIF V_FUNCAO = 3 THEN
     DELETE CONTROLES_LOTES WHERE ID_CONTROLE_LOTE = V_ID_CONTROLE_LOTE;

  END IF;

  COMMIT WORK;

END PRC_CONTROLES_LOTES;
/