CREATE TABLE SINALIZACOES_EVOLUCAO
(ID_SINALIZACAO  SMALLINT      NOT NULL,
 NOME            VARCHAR(20)   NOT NULL,
 DESCRICAO       VARCHAR(50)   NOT NULL,
 TAG_MARCACAO    VARCHAR(30)   NOT NULL,
 COR_MARCACAO    BIGINT     NOT NULL,
 TIPO_MARCACAO   VARCHAR(1)    NOT NULL)
;