-- INSERCAO DO PROCEDIMENTO INTEGRA
INSERT INTO PROCEDIMENTOS VALUES(0,'INTEGRACAO-GENÉRICA','INTEGRA',1,0,0,0,0,'N',0,0,'N',0,'A','N','D','R',0,0,'H','R',NULL,'N','N','*','CR','N','N','N','N',NULL,'N',0,'N','N','N');

-- INSERCAO DO TEXTO GENERICO PARA INTEGRACAO
INSERT INTO TEXTOS VALUES('INTEGRA',1,'LAUDO GENÉRICO PARA INTEGRAÇÕES',
'{\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 Consolas;}{\f1\fnil\fcharset0 Courier New;}{\f2\fnil\fcharset0 Square721 BT;}{\f3\fnil\fcharset0 Courier;}}
{\colortbl ;\red255\green0\blue0;\red0\green0\blue0;}
\viewkind4\uc1\pard\cf1\lang1046\b\f0\fs24 [5000                                              ]:\f1\fs20 [5002      ] [5004      ]\fs22  \fs16  \cf0\f0\fs24\par
\pard\tx7280\cf2\b0\f1\fs16 Materiais:\cf1  [5001                          ]\cf0\f0\fs14                           Método: \cf1\f1 [5008                     ]\fs22  \cf0\f0\fs14  \par
\pard\par
\cf1 [5005]\cf0  \par
\f2\fs20\par
\f0\fs16 Obs.:\cf1\f1 [5006]\par
\par
[5007]\par
\cf0\f3\par
}','C','A','N');

-- INSERCAO NO TEXTOS_COMPARTILHADO
INSERT INTO TEXTOS_COMPARTILHADOS VALUES('INTEGRA',1,'INTEGRA',1);

-- INSERCAO DAS VARIAVEIS
INSERT INTO VARIAVEIS VALUES(5000,'#PROCEDIMENTO','E','AN',50,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,'S','.');
INSERT INTO VARIAVEIS VALUES(5001,'#MATERIAL','E','AN',30,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,1,NULL,NULL,NULL,NULL,'S',NULL);
INSERT INTO VARIAVEIS VALUES(5002,'#VALOR_QUANTITATIVO','E','AN',10,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,2,NULL,NULL,NULL,NULL,'S',NULL);
INSERT INTO VARIAVEIS VALUES(5003,'#VALOR_QUALITATIVO','E','AN',10,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,3,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5004,'#UNIDADE','E','AN',10,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,4,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5005,'#REFERENCIA','E','ME',800,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,5,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5006,'#OBS','E','ME',200,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,6,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5007,'#NOTA','E','ME',200,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,7,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5008,'#METODO1','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,8,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5009,'#METODO2','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,9,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5010,'#METODO3','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,10,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5011,'#METODO4','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,11,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5012,'#METODO5','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,12,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5013,'#METODO6','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,13,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5014,'#METODO7','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,14,NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO VARIAVEIS VALUES(5015,'#METODO8','E','AN',25,0,NULL,NULL,NULL,'S','S',NULL,0,NULL,NULL,15,NULL,NULL,NULL,NULL,'N',NULL);

-- INSERCAO DAS VARIAVEIS_TEXTOS 
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5000,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5001,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5002,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5003,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5004,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5005,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5006,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5007,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5008,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5009,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5010,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5011,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5012,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5013,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5014,'N');
INSERT INTO VARIAVEIS_TEXTOS VALUES('INTEGRA',1,5015,'N');


--
-- POR CADA PROCEDIMENTO INTEGRADO
--
V_MNEMONICO
V_NUMERO
V_EQUIPAMENTO
V_POSTO_REA

INSERT INTO TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,':V_MNEMONICO-INTEGRADO','','C','A','N');

INSERT INTO TEXTOS_COMPARTILHADOS VALUES(:V_MNEMONICO,:V_NUMERO,'INTEGRA',1);

INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5000,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5001,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5002,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5003,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5004,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5005,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5006,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5007,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5008,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5009,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5010,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5011,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5012,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5013,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5014,'S');
INSERT INTO VARIAVEIS_TEXTOS VALUES(:V_MNEMONICO,:V_NUMERO,5015,'S');


INSERT INTO EQUIPAMENTOS_TEXTOS VALUES(:V_EQUIPAMENTO, :V_MNEMONICO, :V_NUMERO, :V_POSTO_REA, V_MAP_EQUIPAMENTO, 'A', 'N', SQ_EQUIPAMENTOS_TEXTOS.NEXTVAL);

INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5000,'#PROCEDIMENTO',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5001,'#MATERIAL',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5002,'#VALOR_QUANTITATIVO',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5003,'#VALOR_QUALITATIVO',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5004,'#UNIDADE',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5005,'#REFERENCIA',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5006,'#OBS',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5007,'#NOTA',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5008,'#METODO',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5009,'#METODO2',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5010,'#METODO3',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5011,'#METODO4',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5012,'#METODO5',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5013,'#METODO6',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5014,'#METODO7',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(:V_EQUIPAMENTO,:V_MNEMONICO,:V_NUMERO,5015,'#METODO8',:V_POSTO_REA,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);


INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5000,'#PROCEDIMENTO',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5001,'#MATERIAL',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5002,'BNP^1^1^1^1',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5003,'#VALOR_QUALITATIVO',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5004,'#UNIDADE',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5005,'#REFERENCIA',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5006,'#OBS',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5007,'#NOTA',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5008,'#METODO1',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5009,'#METODO2',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5010,'#METODO3',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5011,'#METODO4',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5012,'#METODO5',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5013,'#METODO6',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5014,'#METODO7',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
INSERT INTO EQUIPAMENTOS_VARIAVEIS VALUES(232,'HER1G',1,5015,'#METODO8',52,SQ_EQUIPAMENTOS_VARIAVEIS.NEXTVAL);
